//! Public Swagger UI served at `GET /api/docs/`.
//!
//! The OpenAPI 3.1 spec itself is generated by `api_openapi_spec` in
//! `server_handlers_rest2.inc`. This module only ships the HTML shell that loads the
//! pinned Swagger UI bundle and points it at `/api/openapi.json`.

use axum::http::{header, HeaderValue, StatusCode};
use axum::response::{Html, IntoResponse, Response};

const SWAGGER_HTML: &str = include_str!("api_docs_swagger.html");

/// `GET /api/docs/` — interactive Swagger UI.
pub async fn api_docs_swagger() -> Response {
    let mut resp = (StatusCode::OK, Html(SWAGGER_HTML)).into_response();
    resp.headers_mut().insert(
        header::CACHE_CONTROL,
        HeaderValue::from_static("public, max-age=3600"),
    );
    // Allow embedding only on our own origin (the global CSP already covers this — this
    // header is a defence-in-depth for old browsers).
    resp.headers_mut().insert(
        header::X_FRAME_OPTIONS,
        HeaderValue::from_static("SAMEORIGIN"),
    );
    resp
}
