//! Public Swagger UI served at `GET /api/docs/`.
//!
//! The OpenAPI 3.1 spec itself is generated by `api_openapi_spec` in
//! `server_handlers_rest2.inc`. This module only ships the HTML shell that loads the
//! pinned Swagger UI bundle and points it at `/api/openapi.json`.

use axum::http::{header, HeaderValue, StatusCode};
use axum::response::{Html, IntoResponse, Response};

const SWAGGER_HTML: &str = include_str!("api_docs_swagger.html");

/// `GET /api/docs/` — interactive Swagger UI.
pub async fn api_docs_swagger() -> Response {
    let mut resp = (StatusCode::OK, Html(SWAGGER_HTML)).into_response();
    resp.headers_mut().insert(
        header::CACHE_CONTROL,
        HeaderValue::from_static("public, max-age=3600"),
    );
    // NOTE: X-Frame-Options is set authoritatively by the global security-headers layer
    // (`SetResponseHeaderLayer::overriding` → DENY). A per-handler value here would be silently
    // overwritten before reaching the client, so it is intentionally not set.
    resp
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn swagger_response_sets_status_and_security_headers() {
        let resp = api_docs_swagger().await;
        assert_eq!(resp.status(), StatusCode::OK);
        assert_eq!(
            resp.headers()
                .get(header::CACHE_CONTROL)
                .unwrap()
                .to_str()
                .unwrap(),
            "public, max-age=3600"
        );
    }
}
