//! Per-engine onboarding requirements — derived from `shared/engine_requirements.json`
//! (generated by `scripts/generate_engine_requirements.mjs` from live source).

use serde::Serialize;
use serde_json::{json, Value};
use std::collections::HashMap;
use std::sync::OnceLock;

static REQUIREMENTS_JSON: &str = include_str!("../../shared/engine_requirements.json");

static CATALOG: OnceLock<Value> = OnceLock::new();
static TAXONOMY: OnceLock<HashMap<String, EngineTaxon>> = OnceLock::new();

fn catalog_cached() -> &'static Value {
    CATALOG.get_or_init(|| {
        serde_json::from_str(REQUIREMENTS_JSON).unwrap_or_else(|e| {
            tracing::error!(target: "engine_requirements", error = %e, "parse requirements json");
            json!({"error": "requirements catalog unavailable"})
        })
    })
}

/// Authoritative per-engine taxonomy row derived from the embedded catalog's
/// `engines` map. `group` is one of the 15 canonical groups (recon, web,
/// network, cloud, ot, crypto, ai, apt, stealth, supply_chain, data, malware,
/// mobile, social, defense); `kind` is `real_probe` | `agent_required` |
/// `special`.
#[derive(Debug, Clone)]
pub struct EngineTaxon {
    pub id: String,
    pub group: String,
    pub kind: String,
    pub label: String,
}

fn taxonomy() -> &'static HashMap<String, EngineTaxon> {
    TAXONOMY.get_or_init(|| {
        let mut map = HashMap::new();
        if let Some(engines) = catalog_cached().get("engines").and_then(Value::as_object) {
            for (id, def) in engines {
                let group = def
                    .get("group")
                    .and_then(Value::as_str)
                    .unwrap_or("")
                    .to_string();
                let kind = def
                    .get("kind")
                    .and_then(Value::as_str)
                    .unwrap_or("real_probe")
                    .to_string();
                let label = def
                    .get("label")
                    .and_then(Value::as_str)
                    .unwrap_or(id.as_str())
                    .to_string();
                map.insert(
                    id.clone(),
                    EngineTaxon {
                        id: id.clone(),
                        group,
                        kind,
                        label,
                    },
                );
            }
        }
        map
    })
}

/// Full taxonomy row for an engine id, resolving legacy aliases to the
/// canonical id first so callers can pass either form.
pub fn engine_taxon(id: &str) -> Option<&'static EngineTaxon> {
    let t = taxonomy();
    if let Some(row) = t.get(id) {
        return Some(row);
    }
    let canonical = weissman_core::models::engine::resolve_engine_id(id);
    t.get(canonical)
}

/// Authoritative group for an engine id (alias-resolving), if known.
pub fn engine_group(id: &str) -> Option<&'static str> {
    engine_taxon(id).map(|t| t.group.as_str())
}

/// Authoritative kind (`real_probe` | `agent_required` | `special`) for an
/// engine id (alias-resolving), if known.
pub fn engine_kind(id: &str) -> Option<&'static str> {
    engine_taxon(id).map(|t| t.kind.as_str())
}

#[derive(Debug, Clone, Serialize)]
pub struct RequirementStatus {
    pub id: String,
    pub satisfied: bool,
    pub scope: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
}

/// Full catalog for `/api/engines/requirements`.
pub fn catalog_json() -> Value {
    catalog_cached().clone()
}

fn req_def(id: &str) -> Option<&Value> {
    catalog_cached().get("requirements")?.get(id)
}

fn non_empty_str(v: Option<&Value>) -> bool {
    v.and_then(Value::as_str)
        .map(|s| !s.trim().is_empty())
        .unwrap_or(false)
}

fn non_empty_array(v: Option<&Value>) -> bool {
    v.and_then(Value::as_array)
        .map(|a| {
            !a.is_empty()
                && a.iter()
                    .any(|x| x.as_str().is_some_and(|s| !s.trim().is_empty()))
        })
        .unwrap_or(false)
}

fn get_path<'a>(root: &'a Value, path: &str) -> Option<&'a Value> {
    let mut cur = root;
    for part in path.split('.') {
        cur = cur.get(part)?;
    }
    Some(cur)
}

/// Evaluate a single requirement against client snapshot + tenant facts.
pub fn eval_requirement(req_id: &str, client: &Value, tenant: &Value) -> RequirementStatus {
    let scope = req_def(req_id)
        .and_then(|d| d.get("scope"))
        .and_then(Value::as_str)
        .unwrap_or("client")
        .to_string();

    let satisfied = match req_id {
        "msa_acknowledged" => get_path(client, "onboarding.msa_acknowledged")
            .and_then(Value::as_bool)
            .unwrap_or(false),
        "emergency_contact" => {
            non_empty_str(get_path(client, "onboarding.emergency_contact_phone"))
        }
        "scope_domains" => {
            let domains = client.get("domains");
            if let Some(s) = domains.and_then(Value::as_str) {
                serde_json::from_str::<Vec<String>>(s)
                    .map(|v| !v.is_empty())
                    .unwrap_or_else(|_| !s.trim().is_empty())
            } else {
                non_empty_array(domains)
            }
        }
        "scope_ips" => {
            let ips = client.get("ip_ranges");
            if let Some(s) = ips.and_then(Value::as_str) {
                serde_json::from_str::<Vec<String>>(s)
                    .map(|v| !v.is_empty())
                    .unwrap_or(false)
            } else {
                non_empty_array(ips)
            }
        }
        "scope_exclusions" => true,
        "contact_email" => non_empty_str(client.get("contact_email")),
        "aws_cross_account" => {
            non_empty_str(client.get("aws_cross_account_role_arn"))
                && non_empty_str(client.get("aws_external_id"))
        }
        "gcp_project" => non_empty_str(client.get("gcp_project_id")),
        "azure_subscription" => {
            non_empty_str(get_path(client, "onboarding.azure_subscription_id"))
                && non_empty_str(get_path(client, "onboarding.azure_tenant_id"))
        }
        "ad_domain" => non_empty_str(get_path(client, "onboarding.ad_domain")),
        "iac_repos" => non_empty_array(get_path(client, "onboarding.repo_urls")),
        "endpoint_agent" => {
            non_empty_array(get_path(client, "onboarding.agent_platforms"))
                || client
                    .get("agents_online")
                    .and_then(Value::as_u64)
                    .is_some_and(|n| n > 0)
        }
        "industrial_ot" => {
            let ot = get_path(client, "client_configs.industrial_ot_enabled")
                .or_else(|| get_path(client, "onboarding.industrial_ot_enabled"))
                .and_then(Value::as_bool)
                .unwrap_or(false);
            ot && eval_requirement("scope_ips", client, tenant).satisfied
        }
        "llm_secops_endpoints" => {
            let endpoints = get_path(client, "onboarding.llm_secops.endpoints")
                .or_else(|| get_path(client, "client_configs.onboarding.llm_secops.endpoints"));
            endpoints
                .and_then(Value::as_array)
                .map(|a| {
                    !a.is_empty()
                        && a.iter().any(|ep| {
                            ep.get("url")
                                .and_then(Value::as_str)
                                .is_some_and(|s| !s.trim().is_empty())
                                || ep.as_str().is_some_and(|s| !s.trim().is_empty())
                        })
                })
                .unwrap_or(false)
        }
        "tenant_llm" => tenant
            .get("llm_configured")
            .and_then(Value::as_bool)
            .unwrap_or(false),
        "tenant_oast" => tenant
            .get("oast_configured")
            .and_then(Value::as_bool)
            .unwrap_or(false),
        "tenant_ai_entitlement" => tenant
            .get("ai_heavy_entitled")
            .and_then(Value::as_bool)
            .unwrap_or(true),
        _ => false,
    };

    RequirementStatus {
        id: req_id.to_string(),
        satisfied,
        scope,
        detail: None,
    }
}

/// Aggregate requirements for selected engagement modules.
pub fn module_requirements(module_ids: &[String]) -> Vec<String> {
    let cat = catalog_cached();
    let modules = cat.get("modules").and_then(Value::as_object);
    let mut set = std::collections::BTreeSet::new();
    for mid in module_ids {
        if let Some(reqs) = modules
            .and_then(|m| m.get(mid))
            .and_then(|m| m.get("requirements"))
            .and_then(Value::as_array)
        {
            for r in reqs {
                if let Some(s) = r.as_str() {
                    set.insert(s.to_string());
                }
            }
        }
    }
    set.into_iter().collect()
}

fn is_hard_required(req_id: &str, module_ids: &[String]) -> bool {
    match req_id {
        "scope_exclusions" | "llm_secops_endpoints" => false,
        "scope_ips" => module_ids.iter().any(|m| m == "industrial_ot"),
        _ => true,
    }
}

/// Readiness report for a client + selected modules.
pub fn readiness_report(client: &Value, tenant: &Value, module_ids: &[String]) -> Value {
    let req_ids = if module_ids.is_empty() {
        vec![
            "msa_acknowledged".to_string(),
            "emergency_contact".to_string(),
            "contact_email".to_string(),
            "scope_domains".to_string(),
        ]
    } else {
        module_requirements(module_ids)
    };

    let items: Vec<RequirementStatus> = req_ids
        .iter()
        .map(|id| eval_requirement(id, client, tenant))
        .collect();

    let required: Vec<&RequirementStatus> = items
        .iter()
        .filter(|i| is_hard_required(&i.id, module_ids))
        .collect();

    let satisfied_count = required.iter().filter(|i| i.satisfied).count();
    let total = required.len().max(1);
    let pct = (satisfied_count * 100) / total;

    json!({
        "ready": required.iter().all(|i| i.satisfied),
        "percent": pct,
        "satisfied": satisfied_count,
        "total": total,
        "modules": module_ids,
        "requirements": items,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_loads() {
        let c = catalog_json();
        assert!(c["production_engine_count"].as_u64().unwrap_or(0) > 400);
    }

    #[test]
    fn taxonomy_resolves_group_and_kind() {
        // Known production engines carry their authoritative group + kind.
        assert_eq!(engine_group("osint"), Some("recon"));
        assert_eq!(engine_group("bola_idor"), Some("web"));
        assert_eq!(engine_group("scada_ics"), Some("ot"));
        assert_eq!(engine_kind("osint"), Some("real_probe"));
        // Unknown ids resolve to nothing rather than panicking.
        assert_eq!(engine_group("definitely_not_an_engine"), None);
    }

    #[test]
    fn domains_required() {
        let client = json!({"domains": "[\"example.com\"]", "contact_email": "a@b.com"});
        let tenant = json!({});
        assert!(eval_requirement("scope_domains", &client, &tenant).satisfied);
    }

    #[test]
    fn llm_secops_requires_endpoints_when_module_selected() {
        let client = json!({
            "onboarding": {
                "llm_secops": { "endpoints": [{ "url": "https://api.example.com/v1/chat" }] }
            }
        });
        let tenant = json!({});
        assert!(eval_requirement("llm_secops_endpoints", &client, &tenant).satisfied);
        let empty = json!({"onboarding": { "llm_secops": { "endpoints": [] } }});
        assert!(!eval_requirement("llm_secops_endpoints", &empty, &tenant).satisfied);
    }
}
