//! Canonical `requiresTarget` contract — must match `frontend/src/lib/enginesRegistry.js`
//! and `shared/engine_target_contract.json` (generated by
//! `scripts/generate_engine_target_contract.mjs`).
//!
//! Scan enqueue (`scan_routing`) uses this so UI catalog flags and HTTP 400s cannot drift.

use serde::Deserialize;
use std::collections::HashSet;
use std::sync::OnceLock;

const CONTRACT_JSON: &str = include_str!("../../shared/engine_target_contract.json");

#[derive(Debug, Deserialize)]
struct TargetContractFile {
    targetless_ids: Vec<String>,
}

fn targetless_ids() -> &'static HashSet<String> {
    static SET: OnceLock<HashSet<String>> = OnceLock::new();
    SET.get_or_init(|| {
        let parsed: TargetContractFile = serde_json::from_str(CONTRACT_JSON).unwrap_or_else(|e| {
            tracing::error!(target: "engine_target_contract", error = %e, "parse engine_target_contract.json");
            TargetContractFile {
                targetless_ids: vec![],
            }
        });
        parsed.targetless_ids.into_iter().collect()
    })
}

/// Whether enqueue requires a non-empty URL/domain (or an assigned client domain).
///
/// Unknown engines fail closed (`true`) so a missing catalog row cannot skip scope.
#[must_use]
pub fn engine_requires_target(engine_id: &str) -> bool {
    let id = engine_id.trim();
    if id.is_empty() {
        return true;
    }
    !targetless_ids().contains(id)
}

/// Normalize a client-authorized domain into a scan target URL.
#[must_use]
pub fn normalize_assigned_target(raw: &str) -> String {
    let t = raw.trim();
    if t.is_empty() {
        return String::new();
    }
    if t.starts_with("http://") || t.starts_with("https://") {
        return t.to_string();
    }
    format!("https://{}", t.trim_start_matches('/'))
}

/// Parse `clients.domains` JSON (array or comma/newline text) into ordered hosts.
#[must_use]
pub fn parse_client_domain_list(raw: &str) -> Vec<String> {
    let s = raw.trim();
    if s.is_empty() {
        return Vec::new();
    }
    if let Ok(arr) = serde_json::from_str::<Vec<serde_json::Value>>(s) {
        return arr
            .into_iter()
            .filter_map(|v| v.as_str().map(|d| d.trim().to_string()))
            .filter(|d| !d.is_empty())
            .collect();
    }
    s.split(|c| c == ',' || c == '\n')
        .map(str::trim)
        .filter(|d| !d.is_empty())
        .map(str::to_string)
        .collect()
}

/// First usable authorized domain, normalized to a scan URL.
#[must_use]
pub fn first_assigned_target(domains: &[String]) -> Option<String> {
    domains
        .iter()
        .map(|d| normalize_assigned_target(d))
        .find(|d| !d.is_empty())
}

/// Resolve the target that will be enqueued.
///
/// * Targetless engines: keep a typed target if present; never 400 on empty.
/// * Target-required engines: typed target wins; otherwise bind the client's
///   first authorized domain (scoped users auto-aim — no picker).
/// * Target-required + empty + no domains: 400 with a clear contract message.
#[must_use]
pub fn resolve_enqueue_target(
    engine_id: &str,
    provided_target: &str,
    client_domains: &[String],
) -> Result<Option<String>, String> {
    let typed = provided_target.trim();
    if !engine_requires_target(engine_id) {
        if !typed.is_empty() {
            return Ok(Some(typed.to_string()));
        }
        // Optional bind: never 400, but prefer the assigned client domain when present
        // so engines that *can* use a host (cloud probes) still auto-aim.
        return Ok(first_assigned_target(client_domains));
    }
    if !typed.is_empty() {
        return Ok(Some(typed.to_string()));
    }
    if let Some(bound) = first_assigned_target(client_domains) {
        return Ok(Some(bound));
    }
    Err(missing_target_detail(engine_id))
}

/// Stable 400 detail — UI and tests match on the `target required for engine '` prefix.
#[must_use]
pub fn missing_target_detail(engine_id: &str) -> String {
    format!(
        "target required for engine '{engine_id}' — provide a URL/domain or bind a client with authorized domains"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_osint_requires_target() {
        assert!(engine_requires_target("osint"));
        assert!(engine_requires_target("asm"));
        assert!(engine_requires_target("bola_idor"));
    }

    #[test]
    fn catalog_cloud_and_intel_are_targetless() {
        assert!(!engine_requires_target("aws_attack"));
        assert!(!engine_requires_target("cloud_posture"));
        assert!(!engine_requires_target("azure_attack"));
        assert!(!engine_requires_target("gcp_attack"));
        assert!(!engine_requires_target("k8s_container"));
        assert!(!engine_requires_target("iac_misconfig"));
        assert!(!engine_requires_target("zero_day_prediction"));
        assert!(!engine_requires_target("zero_day_radar"));
    }

    #[test]
    fn unknown_engine_fails_closed() {
        assert!(engine_requires_target("definitely_not_an_engine"));
        assert!(engine_requires_target(""));
    }

    #[test]
    fn targetless_does_not_400_without_target() {
        let r = resolve_enqueue_target("aws_attack", "", &[]);
        assert_eq!(r, Ok(None));
    }

    #[test]
    fn targetless_still_auto_binds_assigned_domain() {
        let got = resolve_enqueue_target("aws_attack", "", &["acme.example".into()]).unwrap();
        assert_eq!(got.as_deref(), Some("https://acme.example"));
    }

    #[test]
    fn required_engine_400s_without_target_or_domains() {
        let err = resolve_enqueue_target("osint", "  ", &[]).unwrap_err();
        assert!(err.starts_with("target required for engine 'osint'"));
    }

    #[test]
    fn scoped_user_auto_binds_assigned_domain() {
        let got = resolve_enqueue_target("osint", "", &["acme.example".into()]).unwrap();
        assert_eq!(got.as_deref(), Some("https://acme.example"));
    }

    #[test]
    fn typed_target_wins_over_assigned_domain() {
        let got = resolve_enqueue_target(
            "osint",
            "https://app.acme.example",
            &["acme.example".into()],
        )
        .unwrap();
        assert_eq!(got.as_deref(), Some("https://app.acme.example"));
    }

    #[test]
    fn parse_domains_json_array() {
        let d = parse_client_domain_list(r#"["a.test","b.test"]"#);
        assert_eq!(d, vec!["a.test", "b.test"]);
    }

    #[test]
    fn normalize_keeps_https() {
        assert_eq!(
            normalize_assigned_target("https://x.test/"),
            "https://x.test/"
        );
        assert_eq!(normalize_assigned_target("x.test"), "https://x.test");
    }
}
