//! Board-grade Excel workbooks for Weissman exports.

use crate::pdf::copy as t;
use crate::pdf::doc::Lang;
use crate::pdf::spec::{ColumnSpec, SheetSpec, WorkbookSpec};
use rust_xlsxwriter::{
    Chart, ChartType, Color, ConditionalFormatText, ConditionalFormatTextRule, DocProperties,
    Format, FormatAlign, FormatBorder, Workbook, XlsxError,
};
use sha2::{Digest, Sha256};

const BRAND_DEEP: u32 = 0x07_3A40;
const BRAND: u32 = 0x0E_7C86;
const PAPER: u32 = 0xFF_FFFF;
const INK: u32 = 0x0A_1626;
const MUTED: u32 = 0x5A_6B7B;
const LINE: u32 = 0xE4_EAF1;
const ROSE: u32 = 0x9B_1C2E;
const AMBER: u32 = 0xC2_410C;
const GOLD: u32 = 0xC7_7A12;
const TEAL: u32 = 0x0E_7C86;
const ZEBRA: u32 = 0xEE_F3F8;

fn rgb(v: u32) -> Color {
    Color::RGB(v)
}

/// Render a validated [`WorkbookSpec`] to `.xlsx` bytes.
pub fn render_workbook(spec: &WorkbookSpec) -> Result<Vec<u8>, String> {
    let spec = spec.sanitized()?;
    render_inner(&spec).map_err(|e| e.to_string())
}

fn render_inner(spec: &WorkbookSpec) -> Result<Vec<u8>, XlsxError> {
    let lang = Lang::parse(&spec.lang);
    let mut workbook = Workbook::new();
    let org = if spec.org.is_empty() {
        "Weissman Cybersecurity"
    } else {
        spec.org.as_str()
    };
    workbook.set_properties(
        &DocProperties::new()
            .set_title(&spec.title)
            .set_subject(&spec.subtitle)
            .set_author(org)
            .set_company(org)
            .set_category(if spec.classification.is_empty() {
                "Confidential"
            } else {
                &spec.classification
            })
            .set_keywords("Weissman, cybersecurity, findings, live")
            .set_comment("Generated by the Weissman Cybersecurity platform. Live data only."),
    );

    let title_fmt = Format::new()
        .set_bold()
        .set_font_size(18)
        .set_font_color(rgb(PAPER))
        .set_background_color(rgb(BRAND_DEEP));
    let band_fmt = Format::new()
        .set_font_color(rgb(PAPER))
        .set_background_color(rgb(BRAND_DEEP));
    let label_fmt = Format::new().set_bold().set_font_color(rgb(MUTED));
    let value_fmt = Format::new().set_font_color(rgb(INK));
    let header_fmt = Format::new()
        .set_bold()
        .set_font_color(rgb(PAPER))
        .set_background_color(rgb(BRAND_DEEP))
        .set_align(FormatAlign::Center)
        .set_border(FormatBorder::Thin)
        .set_text_wrap();
    let cell_fmt = Format::new()
        .set_border(FormatBorder::Thin)
        .set_border_color(rgb(LINE))
        .set_text_wrap()
        .set_align(FormatAlign::Top);
    let zebra_fmt = Format::new()
        .set_border(FormatBorder::Thin)
        .set_border_color(rgb(LINE))
        .set_background_color(rgb(ZEBRA))
        .set_text_wrap()
        .set_align(FormatAlign::Top);
    let number_fmt = Format::new()
        .set_border(FormatBorder::Thin)
        .set_border_color(rgb(LINE))
        .set_align(FormatAlign::Right);
    let crit_fmt = Format::new()
        .set_bold()
        .set_font_color(rgb(PAPER))
        .set_background_color(rgb(ROSE));
    let high_fmt = Format::new()
        .set_bold()
        .set_font_color(rgb(PAPER))
        .set_background_color(rgb(AMBER));
    let med_fmt = Format::new()
        .set_bold()
        .set_font_color(rgb(PAPER))
        .set_background_color(rgb(GOLD));
    let low_fmt = Format::new()
        .set_bold()
        .set_font_color(rgb(PAPER))
        .set_background_color(rgb(TEAL));

    // ---- Overview -----------------------------------------------------------------
    {
        let sheet = workbook.add_worksheet();
        sheet.set_name(t::OVERVIEW_SHEET.get(lang))?;
        if lang.is_rtl() {
            sheet.set_right_to_left(true);
        }
        sheet.set_landscape();
        sheet.set_paper_size(9); // A4
        sheet.set_print_fit_to_pages(1, 0);
        sheet.set_header("&LWeissman Cybersecurity&C&A&RConfidential");
        sheet.set_footer("&CPage &P of &N");
        sheet.set_column_width(0, 28)?;
        sheet.set_column_width(1, 56)?;
        sheet.merge_range(0, 0, 0, 3, &spec.title, &title_fmt)?;
        sheet.write_with_format(1, 0, spec.subtitle.as_str(), &band_fmt)?;
        let mut row = 3u32;
        let fields = [
            (t::ORGANIZATION.get(lang), org),
            (t::SCOPE.get(lang), spec.client.as_str()),
            (t::ACTOR.get(lang), spec.actor.as_str()),
            (
                t::CLASSIFICATION.get(lang),
                if spec.classification.is_empty() {
                    "Confidential"
                } else {
                    spec.classification.as_str()
                },
            ),
        ];
        for (k, v) in fields {
            if v.is_empty() {
                continue;
            }
            sheet.write_with_format(row, 0, k, &label_fmt)?;
            sheet.write_with_format(row, 1, v, &value_fmt)?;
            row += 1;
        }
        row += 1;
        sheet.write_with_format(row, 0, t::COL_SEVERITY.get(lang), &header_fmt)?;
        sheet.write_with_format(row, 1, t::ROW_COUNT.get(lang), &header_fmt)?;
        let summary = severity_summary(spec);
        let summary_start = row + 1;
        for (i, (label, count)) in summary.iter().enumerate() {
            sheet.write_with_format(summary_start + i as u32, 0, *label, &cell_fmt)?;
            sheet.write_with_format(summary_start + i as u32, 1, i64::from(*count), &number_fmt)?;
        }
        if !summary.is_empty() {
            let mut chart = Chart::new(ChartType::Column);
            chart
                .add_series()
                .set_categories((
                    t::OVERVIEW_SHEET.get(lang),
                    summary_start,
                    0,
                    summary_start + summary.len() as u32 - 1,
                    0,
                ))
                .set_values((
                    t::OVERVIEW_SHEET.get(lang),
                    summary_start,
                    1,
                    summary_start + summary.len() as u32 - 1,
                    1,
                ))
                .set_name(t::SEVERITY_MIX.get(lang));
            chart.title().set_name(t::SEVERITY_MIX.get(lang));
            sheet.insert_chart(summary_start, 3, &chart)?;
        }
        let hash = integrity_hash(spec);
        let hash_row = summary_start + summary.len() as u32 + 2;
        sheet.write_with_format(hash_row, 0, t::INTEGRITY_HASH.get(lang), &label_fmt)?;
        sheet.write_with_format(hash_row, 1, hash.as_str(), &value_fmt)?;
    }

    // ---- Data sheets --------------------------------------------------------------
    for sheet_spec in &spec.sheets {
        let sheet = workbook.add_worksheet();
        let name = if sheet_spec.name.is_empty() {
            t::DATA_SHEET.get(lang)
        } else {
            &sheet_spec.name
        };
        sheet.set_name(name)?;
        if lang.is_rtl() {
            sheet.set_right_to_left(true);
        }
        sheet.set_landscape();
        sheet.set_paper_size(9);
        sheet.set_print_fit_to_pages(1, 0);
        sheet.set_repeat_rows(0, 0)?;
        sheet.set_header("&LWeissman Cybersecurity&C&A&RConfidential");
        sheet.set_footer("&CPage &P of &N");
        let ncols = sheet_spec.columns.len().max(1);
        for (c, col) in sheet_spec.columns.iter().enumerate() {
            let width = (18.0_f64 * col.weight).clamp(12.0, 48.0);
            sheet.set_column_width(c as u16, width)?;
            sheet.write_with_format(0, c as u16, col.title.as_str(), &header_fmt)?;
        }
        let mut sev_col: Option<u16> = None;
        for (c, col) in sheet_spec.columns.iter().enumerate() {
            if col.style.eq_ignore_ascii_case("severity")
                || col.title.to_ascii_lowercase().contains("sev")
            {
                sev_col = Some(c as u16);
            }
        }
        for (r, row) in sheet_spec.rows.iter().enumerate() {
            let excel_row = (r as u32) + 1;
            let zebra = r % 2 == 1;
            for (c, col) in sheet_spec.columns.iter().enumerate() {
                let raw = row.get(c).map(String::as_str).unwrap_or("");
                let fmt = if col.style.eq_ignore_ascii_case("number") {
                    &number_fmt
                } else if zebra {
                    &zebra_fmt
                } else {
                    &cell_fmt
                };
                if col.style.eq_ignore_ascii_case("number") {
                    if let Ok(n) = raw.replace([',', '%', ' '], "").parse::<f64>() {
                        sheet.write_with_format(excel_row, c as u16, n, fmt)?;
                        continue;
                    }
                }
                sheet.write_with_format(excel_row, c as u16, raw, fmt)?;
            }
            let _ = ncols;
        }
        let last_row = sheet_spec.rows.len() as u32;
        if last_row > 0 {
            sheet.autofilter(0, 0, last_row, (ncols as u16).saturating_sub(1))?;
            sheet.set_freeze_panes(1, 0)?;
            if let Some(col) = sev_col {
                for (needle, fmt) in [
                    ("critical", &crit_fmt),
                    ("high", &high_fmt),
                    ("medium", &med_fmt),
                    ("low", &low_fmt),
                ] {
                    let cf = ConditionalFormatText::new()
                        .set_rule(ConditionalFormatTextRule::Contains(needle.to_string()))
                        .set_format(fmt);
                    sheet.add_conditional_format(1, col, last_row, col, &cf)?;
                }
            }
        }
    }

    workbook.save_to_buffer()
}

fn severity_summary(spec: &WorkbookSpec) -> Vec<(&'static str, u32)> {
    let mut crit = 0u32;
    let mut high = 0u32;
    let mut med = 0u32;
    let mut low = 0u32;
    for sheet in &spec.sheets {
        let sev_idx = sheet.columns.iter().position(|c| {
            c.style.eq_ignore_ascii_case("severity") || c.title.to_ascii_lowercase().contains("sev")
        });
        let Some(idx) = sev_idx else { continue };
        for row in &sheet.rows {
            let s = row
                .get(idx)
                .map(|v| v.to_ascii_lowercase())
                .unwrap_or_default();
            if s.contains("crit") {
                crit += 1;
            } else if s.contains("high") {
                high += 1;
            } else if s.contains("med") {
                med += 1;
            } else {
                low += 1;
            }
        }
    }
    vec![
        ("Critical", crit),
        ("High", high),
        ("Medium", med),
        ("Low / Info", low),
    ]
}

fn integrity_hash(spec: &WorkbookSpec) -> String {
    let mut h = Sha256::new();
    h.update(spec.title.as_bytes());
    for sheet in &spec.sheets {
        h.update(sheet.name.as_bytes());
        for row in &sheet.rows {
            for cell in row {
                h.update(cell.as_bytes());
                h.update(b"\x1f");
            }
            h.update(b"\x1e");
        }
    }
    format!("{:x}", h.finalize())
}

/// Convenience: wrap a single table as a branded workbook.
pub fn table_workbook(
    title: &str,
    client: &str,
    actor: &str,
    lang: Lang,
    columns: Vec<ColumnSpec>,
    rows: Vec<Vec<String>>,
) -> Result<Vec<u8>, String> {
    let spec = WorkbookSpec {
        title: title.to_string(),
        subtitle: String::new(),
        org: "Weissman Cybersecurity".into(),
        client: client.to_string(),
        classification: "Confidential".into(),
        lang: match lang {
            Lang::He => "he".into(),
            Lang::En => "en".into(),
        },
        actor: actor.to_string(),
        sheets: vec![SheetSpec {
            name: t::DATA_SHEET.get(lang).to_string(),
            columns,
            rows,
        }],
    };
    render_workbook(&spec)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> WorkbookSpec {
        WorkbookSpec {
            title: "Findings export".into(),
            subtitle: "Live tenant findings".into(),
            org: "Weissman Cybersecurity".into(),
            client: "Acme".into(),
            classification: "Confidential".into(),
            lang: "en".into(),
            actor: "analyst@weissman".into(),
            sheets: vec![SheetSpec {
                name: "Findings".into(),
                columns: vec![
                    ColumnSpec {
                        title: "ID".into(),
                        weight: 1.0,
                        style: "mono".into(),
                    },
                    ColumnSpec {
                        title: "Title".into(),
                        weight: 3.0,
                        style: "strong".into(),
                    },
                    ColumnSpec {
                        title: "Severity".into(),
                        weight: 1.0,
                        style: "severity".into(),
                    },
                    ColumnSpec {
                        title: "Count".into(),
                        weight: 1.0,
                        style: "number".into(),
                    },
                ],
                rows: vec![
                    vec![
                        "VLN-1".into(),
                        "Open admin".into(),
                        "critical".into(),
                        "4".into(),
                    ],
                    vec!["VLN-2".into(), "Weak TLS".into(), "high".into(), "2".into()],
                ],
            }],
        }
    }

    #[test]
    fn renders_an_xlsx_zip() {
        let bytes = render_workbook(&sample()).expect("xlsx");
        assert_eq!(&bytes[0..2], b"PK", "xlsx is a zip package");
        assert!(bytes.len() > 2_000);
    }

    #[test]
    fn hebrew_workbook_is_still_a_zip() {
        let mut spec = sample();
        spec.lang = "he".into();
        spec.title = "ייצוא ממצאים".into();
        let bytes = render_workbook(&spec).expect("xlsx");
        assert_eq!(&bytes[0..2], b"PK");
    }

    #[test]
    fn empty_rows_still_produce_headers() {
        let mut spec = sample();
        spec.sheets[0].rows.clear();
        let bytes = render_workbook(&spec).expect("xlsx");
        assert_eq!(&bytes[0..2], b"PK");
    }
}
