apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weissman
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: weissman.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weissman-gateway
                port:
                  number: 80
