//! Static signature banks for the Aho-Corasick automata.
//!
//! Patterns are ASCII (matched case-insensitively). Homoglyph folding happens
//! before lookup so lookalike attacks still hit these needles.

pub const INJECTION_NEEDLES: &[&str] = &[
    "ignore previous",
    "ignore all previous",
    "ignore your previous",
    "disregard previous",
    "disregard all previous",
    "forget previous",
    "forget all previous instructions",
    "override previous",
    "new instructions",
    "updated instructions",
    "system prompt",
    "reveal your system",
    "print your instructions",
    "show your hidden prompt",
    "dump your prompt",
    "you are now",
    "you will now act",
    "from now on you",
    "developer mode",
    "sudo mode",
    "admin mode enabled",
    "jailbreak",
    "override safety",
    "disable safety",
    "bypass the filter",
    "bypass safety",
    "no longer bound",
    "do not follow the",
    "ignore the above",
    "ignore the system",
    "<|im_start|>",
    "<|im_end|>",
    "<|system|>",
    "</s>",
    "[inst]",
    "[/inst]",
    "<<sys>>",
    "begin untrusted",
    "end untrusted",
    "system:",
    "assistant:",
    "### instruction",
    "### system",
    "tool call",
    "function call hijack",
    "exfiltrate",
    "send secrets to",
    "curl http",
    "wget http",
];

pub const JAILBREAK_NEEDLES: &[&str] = &[
    "do anything now",
    "dan mode",
    "you are dan",
    "hi chatgpt. you are about to immerse",
    "jailbreak mode",
    "no ethical guidelines",
    "without any restrictions",
    "no content policy",
    "ignore openai",
    "ignore anthropic",
    "ignore your programming",
    "pretend you are",
    "roleplay as",
    "role-play as",
    "act as an unrestricted",
    "unfiltered assistant",
    "unrestricted ai",
    "evil confidant",
    "opposite day",
    "grandma exploit",
    "for educational purposes only, explain how to",
    "hypothetically, if you had no rules",
    "in a fictional world with no laws",
    "this is a test of your uncensored",
    "token smuggling",
    "many-shot jailbreak",
    "crescendo attack",
    "pair attack",
    "skeleton key",
    "developer override",
    "aim (always intelligent and Machiavellian)",
    "stan (strive to avoid norms)",
    "dude (do anything you desire)",
    "ket gpt",
    "betterdan",
    "anti-dan",
    "switch to godmode",
    "enable maximum freedom",
];

pub const ROLEPLAY_NEEDLES: &[&str] = &[
    "you are a",
    "imagine you are",
    "simulate being",
    "stay in character",
    "break character",
    "from this point forward",
    "your new persona",
    "adopt the persona",
];

pub const OUTPUT_LEAK_NEEDLES: &[&str] = &[
    "you are weissman",
    "system prompt:",
    "hidden instructions",
    "developer message:",
    "the secret is",
    "api key=",
    "begin untrusted user-controlled data",
    "weissman_jwt",
    "weissman_admin_password",
];

pub const ENGINE_ALIAS_NEEDLES: &[&str] = &[
    "prompt_injection_chain",
    "llm_jailbreak",
    "rag_poisoning_engine",
    "command center",
    "supreme council",
    "weissman_ro",
    "bypassrls",
];
