import { useCallback, useEffect, useState } from 'react'
import { apiUrl } from '../lib/apiBase'

/**
 * Workspace options for the login form's tenant picker.
 *
 * Reads `GET /api/auth/tenant-directory` — public, because the field is filled in before any session
 * exists. The endpoint may legitimately refuse to list (multi-tenant production instances withhold
 * the slug list unless the operator opts in), and it may be unreachable, so this hook always reports
 * whether the user still needs a way to type a slug by hand rather than assuming a list exists.
 *
 * Status meanings:
 *   `loading`    — request in flight; the caller should keep whatever slug it already has.
 *   `ready`      — at least one selectable workspace in `tenants`.
 *   `restricted` — the server answered but will not list (or listed nothing): free-text entry only.
 *   `error`      — transport/HTTP failure: free-text entry only, and `reload` is worth offering.
 */

/** Slug `api_login` falls back to when the request omits one. */
export const FALLBACK_TENANT_SLUG = 'default'

/** Defensive cap; the server caps too, but a client should not render an unbounded option list. */
const MAX_OPTIONS = 200

const TENANT_DIRECTORY_PATH = '/api/auth/tenant-directory'

function cleanSlug(raw) {
  if (typeof raw !== 'string') return ''
  // Slugs are generated by `slugify` on signup: lowercase alphanumerics plus dashes. Anything else
  // could not resolve to a tenant, so drop it rather than render an option that cannot log in.
  const trimmed = raw.trim().toLowerCase()
  return /^[a-z0-9][a-z0-9-]{0,63}$/.test(trimmed) ? trimmed : ''
}

function cleanName(raw, slug) {
  if (typeof raw !== 'string') return slug
  const trimmed = raw.trim().replace(/\s+/g, ' ')
  return trimmed ? trimmed.slice(0, 120) : slug
}

/**
 * Wire payload → hook state. Exported for tests: this is where every hostile/degenerate shape
 * (missing fields, duplicate slugs, non-array `tenants`, a restricted listing) is flattened into the
 * four statuses the UI knows how to render.
 */
export function normalizeDirectory(payload) {
  const raw = Array.isArray(payload?.tenants) ? payload.tenants : []
  const seen = new Set()
  const tenants = []
  for (const entry of raw) {
    const slug = cleanSlug(entry?.slug)
    if (!slug || seen.has(slug)) continue
    seen.add(slug)
    tenants.push({ slug, name: cleanName(entry?.name, slug) })
    if (tenants.length >= MAX_OPTIONS) break
  }
  const defaultSlug = cleanSlug(payload?.default_slug) || FALLBACK_TENANT_SLUG
  const restricted = payload?.listing === 'restricted' || tenants.length === 0
  return {
    status: restricted ? 'restricted' : 'ready',
    tenants,
    defaultSlug,
    // A restricted or truncated list means the slug the user needs may not be in it.
    allowCustom: restricted || payload?.allow_custom === true,
  }
}

const INITIAL_STATE = {
  status: 'loading',
  tenants: [],
  defaultSlug: FALLBACK_TENANT_SLUG,
  allowCustom: false,
}

export default function useTenantDirectory() {
  const [state, setState] = useState(INITIAL_STATE)
  const [attempt, setAttempt] = useState(0)

  const reload = useCallback(() => {
    setState((prev) => ({ ...prev, status: 'loading' }))
    setAttempt((n) => n + 1)
  }, [])

  useEffect(() => {
    const controller = new AbortController()
    let alive = true

    ;(async () => {
      try {
        const response = await fetch(apiUrl(TENANT_DIRECTORY_PATH), {
          method: 'GET',
          headers: { Accept: 'application/json' },
          signal: controller.signal,
        })
        const payload = await response.json().catch(() => null)
        if (!alive) return
        if (!response.ok) {
          // 503 still carries the fallback fields; anything else is treated the same way.
          setState({
            status: 'error',
            tenants: [],
            defaultSlug: cleanSlug(payload?.default_slug) || FALLBACK_TENANT_SLUG,
            allowCustom: true,
          })
          return
        }
        setState(normalizeDirectory(payload))
      } catch {
        if (!alive) return
        setState({
          status: 'error',
          tenants: [],
          defaultSlug: FALLBACK_TENANT_SLUG,
          allowCustom: true,
        })
      }
    })()

    return () => {
      alive = false
      controller.abort()
    }
  }, [attempt])

  return { ...state, reload }
}
