apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ include "weissman.namespace" . }}
  labels:
    {{- include "weissman.labels" . | nindent 4 }}
spec:
  selector:
    app: weissman-backend
  ports:
    - port: 8000
      targetPort: 8000
