//! Intelligence-grade stealth persistence & defense-evasion catalog.
//!
//! 500 assessment capabilities across 10 domains. Each check is scored from
//! **live** host/control-plane evidence. This module never emits exploit
//! payloads, syscall stubs, AMSI/ETW patches, process-injection shells, or
//! persistence implants — those remain out of tree by design.

use serde::Serialize;

pub const ENGINE_ID: &str = "stealthy_persistence_evasion";
pub const CATALOG_LEN: usize = 500;
pub const DOMAIN_COUNT: usize = 10;
pub const CHECKS_PER_DOMAIN: usize = 50;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub struct DomainMeta {
    pub id: u8,
    pub key: &'static str,
    pub label: &'static str,
    pub mitre: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub struct Check {
    pub id: u16,
    pub domain: u8,
    pub title: &'static str,
    pub mitre: &'static str,
    pub fail_safe: bool,
}

pub const DOMAINS: [DomainMeta; DOMAIN_COUNT] = [
    DomainMeta {
        id: 1,
        key: "peb_teb",
        label: "PEB/TEB Memory Profiling & Anti-Hooking",
        mitre: "T1055",
    },
    DomainMeta {
        id: 2,
        key: "direct_syscalls",
        label: "Direct System Calls & HalosGate Recovery",
        mitre: "T1106",
    },
    DomainMeta {
        id: 3,
        key: "hollow_routing",
        label: "Obfuscated Process Execution & Hollow-Routing",
        mitre: "T1055.012",
    },
    DomainMeta {
        id: 4,
        key: "persistence",
        label: "Active Persistence Emulation",
        mitre: "T1547",
    },
    DomainMeta {
        id: 5,
        key: "memory_masking",
        label: "In-Memory Artifact Masking & API Obfuscation",
        mitre: "T1027",
    },
    DomainMeta {
        id: 6,
        key: "telemetry_blind",
        label: "Local Agent Telemetry Blinding",
        mitre: "T1562.001",
    },
    DomainMeta {
        id: 7,
        key: "wss_ring",
        label: "High-Throughput WSS & Local Ring-Buffer",
        mitre: "T1071.001",
    },
    DomainMeta {
        id: 8,
        key: "rls_isolation",
        label: "Automated Multi-Tenant Isolation & RLS",
        mitre: "T1078",
    },
    DomainMeta {
        id: 9,
        key: "worker_copy",
        label: "DB Bulk COPY Ingestion & SKIP LOCKED Worker",
        mitre: "T1071",
    },
    DomainMeta {
        id: 10,
        key: "cicd_safeguards",
        label: "CI/CD Automated Accuracy & Safety Safeguards",
        mitre: "T1553",
    },
];

const TITLES: [&[(&str, &str)]; DOMAIN_COUNT] = [
    &[
        ("Low-level GS/FS TEB access without NtCurrentTeb", "T1083"),
        ("LdrDataTable atomic integrity vs agent snapshot", "T1129"),
        ("IAT update FSM race-free", "T1574.002"),
        ("PEB access frequency |z|>6 UEBA", "T1082"),
        ("User-mode ntdll JMP unhook vs on-disk image", "T1562.001"),
        ("Async TEB stack base/limit integrity", "T1082"),
        ("BeingDebugged / TracerPid integrity", "T1622"),
        ("KernelCallbackTable integrity", "T1574"),
        ("Phantom-typed kernel pointer safety", "T1055"),
        ("Module stomping via image headers", "T1055.012"),
        ("HeapBase footprint minimization", "T1027"),
        ("Environment-block sensitive variable exposure", "T1082"),
        ("Zero-cost memory-access traits", "T1055"),
        ("Remote thread injection via TIB", "T1055.002"),
        ("Command-line PEB masquerade", "T1036.003"),
        ("ImageBaseAddress stability", "T1055"),
        ("Idle PAGE_NOACCESS mapping", "T1622"),
        ("LdrpHashTable integrity", "T1574"),
        ("Atomic function-pointer updates", "T1574.002"),
        ("LdrLoadDll hook detection", "T1574.002"),
        ("FullDllName masquerade", "T1036"),
        ("SubSystemData integrity", "T1082"),
        ("TEB reference lifetimes", "T1082"),
        ("APC queue injection", "T1055.004"),
        ("ProcessParameters path exposure", "T1082"),
        ("Privileged PEB scan frequency (XDR)", "T1082"),
        ("Safe Result on memory access", "T1055"),
        ("SessionID masking", "T1078"),
        ("TlsExpansionSlots integrity", "T1055"),
        ("Intrinsic offset calculation", "T1106"),
        ("Anti-VM TEB hypervisor artifacts", "T1497.001"),
        ("Subsystem flag masquerade", "T1036"),
        ("VirtualProtect write-permission restore", "T1055"),
        ("LdrpInvertedFunctionTable integrity", "T1620"),
        ("PEB EntryPoint masquerade", "T1036"),
        ("Compile-time profiler-name obfuscation", "T1027"),
        ("Heap-segment code injection", "T1055.001"),
        ("Process-group masquerade", "T1036"),
        ("NtQueryInformationProcess hook", "T1562.001"),
        ("Per-build compile-time offsets", "T1027"),
        ("Working-set EDR page-out scans", "T1082"),
        ("Static LDR module-name hashing", "T1027.001"),
        ("ActivationContextStackPointer integrity", "T1082"),
        ("Self-unmap of PEB profiler", "T1055"),
        ("GdiSharedHandleTable integrity", "T1082"),
        ("FastPebLock masquerade", "T1082"),
        ("TLS slot injection", "T1055"),
        ("Ownership of PEB-scan resources", "T1055"),
        ("InLoadOrderModuleList order", "T1129"),
        ("Fail-safe wipe on unbypassable PEB hook", "T1485"),
    ],
    &[
        ("HalosGate neighbor SSN recovery", "T1106"),
        ("Indirect syscall into legitimate ntdll gadget", "T1106"),
        ("HalosGate as OS-generic trait (Win10/11 x64)", "T1106"),
        ("SSN vs kernel version DB attestation", "T1106"),
        ("Polymorphic syscall stubs", "T1027"),
        ("SSN cache in encrypted ring buffer", "T1106"),
        ("Call-stack spoof with kernel32/ntdll frames", "T1106"),
        ("Typed SSN enums", "T1106"),
        ("RIP/return-address range validation", "T1106"),
        ("Stomped-export recovery via HalosGate", "T1055.012"),
        ("Randomized SSN register allocation", "T1027"),
        ("MSR_LSTAR syscall-entry hook detection", "T1562.001"),
        ("Instruction padding around syscall", "T1027"),
        ("Sensitive syscall exposure vs ALE/SLE", "T1486"),
        ("Compile-time syscall stub macros", "T1106"),
        ("Direct NtTraceEvent ETW provider posture", "T1562.006"),
        ("Hardened HalosGate neighbor range", "T1106"),
        ("Conditional syscall only when ntdll is hooked", "T1562.001"),
        ("Service call table vs on-disk image", "T1562.001"),
        ("Zero-copy kernel argument passing", "T1106"),
        ("Heap-resident syscall stub", "T1055"),
        ("Mutex-protected SSN cache", "T1106"),
        ("STATUS_INVALID_PARAMETER syscall-gateway scans", "T1106"),
        ("Stack spoof vs behavioral analysis", "T1106"),
        ("Microsecond SSN resolution latency", "T1106"),
        ("Direct WFP syscall posture", "T1562.004"),
        ("Runtime ntdll export-directory integrity", "T1562.001"),
        ("HalosGate generics for x86 (if present)", "T1106"),
        ("Syscall-thread masquerade vs kernel callbacks", "T1055"),
        ("Randomized data-passing registers", "T1027"),
        ("Build-number / Insider kernel adaptation", "T1106"),
        ("ROP-style legitimate return address", "T1106"),
        ("VirtualQuery scans of agent code", "T1082"),
        ("Safe wrappers around unsafe assembly", "T1106"),
        ("Fileless SSN recovery (memory-only)", "T1027.009"),
        ("Indirect jump to in-range syscall stub", "T1106"),
        ("Multi-threaded syscall workers", "T1106"),
        ("Kernel RAX NTSTATUS error handling", "T1106"),
        ("Direct LSASS-access syscall posture (no dump)", "T1003.001"),
        ("Decoy legitimate syscalls", "T1036"),
        ("HalosGate after export-table stomping", "T1055.012"),
        ("User-mode EDR proxy bypass posture", "T1562.001"),
        ("Zero-cost syscall abstractions", "T1106"),
        ("Call-frequency jitter vs UEBA", "T1070"),
        ("Temporary heap argument buffers", "T1055"),
        ("VMM-adjusted SSN recovery", "T1497"),
        ("W^X / code-integrity policy of stubs", "T1553"),
        ("HalosGate recovery status enum", "T1106"),
        ("System call table monitoring", "T1562.001"),
        ("Fail-safe SSN cache wipe after task", "T1485"),
    ],
    &[
        (
            "Hollow-routing of live probes into privileged hosts",
            "T1055.012",
        ),
        ("Host PE header entry-point integrity", "T1055.012"),
        ("Fileless scanning-engine load (memory-only)", "T1027.009"),
        ("Host-process ownership / leak-free cleanup", "T1055"),
        ("ASLR-aligned random base address", "T1055"),
        ("Pre-injection EDR/AV DLL inventory in host", "T1518.001"),
        ("Process ghosting (delete-on-open) artifacts", "T1055.012"),
        ("PPID spoof vs services.exe", "T1134.004"),
        ("ROP-obscured entry point", "T1055"),
        ("Thread hijack vs CreateRemoteThread", "T1055.003"),
        ("Section name masquerade (.text/.data)", "T1036"),
        ("Hidden module-load via Ldr internals", "T1574"),
        ("Safe FFI around injection APIs", "T1055"),
        ("External scanner access to injected section", "T1055"),
        ("Reported image-size anomalies", "T1036"),
        ("Reflective DLL load without LoadLibrary", "T1574.001"),
        ("Full dynamic API resolution (no IAT)", "T1027.007"),
        ("no_std payload size minimization", "T1027"),
        ("Unmap resistance of injected image", "T1055"),
        ("Thread-context masquerade on hijack", "T1055.003"),
        ("Process herpaderping disk/memory mismatch", "T1055.012"),
        ("RX instead of RWX protection", "T1055"),
        ("Manual relocation table application", "T1055"),
        ("Typed PE header structs", "T1055"),
        ("In-memory signature / polymorphic scanners", "T1027"),
        ("Export-directory wipe after load", "T1027"),
        ("In-host API hook routing to local agent", "T1056"),
        ("Fake call-stack inside host process", "T1106"),
        ("Multi-process scan-task routing", "T1055"),
        (
            "Injection FSM (Initialized/Suspended/Injected/Running)",
            "T1055",
        ),
        ("TLS collision with host process", "T1055"),
        ("PE checksum masquerade", "T1036"),
        ("Direct section mapping (NtCreateSection)", "T1055"),
        ("User-mode APC dispatcher injection", "T1055.004"),
        ("Full host-process memory cleanup", "T1070"),
        ("Safe Result around critical-process injection", "T1055"),
        ("Remote-thread-creation telemetry bypass", "T1055.002"),
        ("High-memory image-base masquerade", "T1055"),
        ("Advanced module stomping of existing DLLs", "T1055.012"),
        ("Guard-page exception handling", "T1622"),
        ("Low-latency host suspension window", "T1055"),
        ("Per-tenant unique injection macros", "T1027"),
        ("XDR working-set scans of host", "T1082"),
        ("Fake OEP vs true entry point", "T1036"),
        ("Kernel-to-user callback injection posture", "T1055"),
        ("IFEO debugger bypass posture", "T1546.012"),
        ("Fileless in-host persistence", "T1027.009"),
        ("Option handling for missing host data", "T1055"),
        ("Idle-only engine activation", "T1497.003"),
        ("Fail-safe restore of host process", "T1485"),
    ],
    &[
        (
            "Legitimate-named scheduled tasks (OneDrive/System Clean)",
            "T1053.005",
        ),
        ("5MB stripped agent binary size gate", "T1027"),
        ("WMI repository persistence", "T1546.003"),
        ("Encrypted generic-named systemd units", "T1543.002"),
        ("Per-release binary shape via CI/CD", "T1027"),
        ("Unconventional registry keys (AppCertDLLs)", "T1546.009"),
        ("Task timestamp/author after-create mutation", "T1070.006"),
        ("COM hijacking without Startup key", "T1546.015"),
        ("Idle CPU |z|<3 persistence", "T1497.003"),
        ("User logon-script persistence", "T1037.001"),
        ("Disguised Startup-folder shortcuts", "T1547.009"),
        ("Service recovery auto-restart", "T1543.003"),
        ("Hidden attributes + timestomping on disk", "T1070.006"),
        ("DLL side-loading via signed apps", "T1574.002"),
        ("Uniform Windows/Linux persistence API", "T1547"),
        ("Hidden-path cron jobs (/var/tmp)", "T1053.003"),
        (
            "Selective event-log wipe of persistence create",
            "T1070.001",
        ),
        ("AppCert DLL early-load", "T1546.009"),
        ("Autoruns AutoStart scan bypass", "T1547"),
        ("Explorer shell-extension persistence", "T1546.015"),
        ("User-level persistence without Administrator", "T1547"),
        ("Encrypted Serde persistence config on disk", "T1027"),
        ("Continuous metadata timestomping", "T1070.006"),
        ("Screensaver idle persistence", "T1546.002"),
        ("Rare WMI event-filter predicates", "T1546.003"),
        ("Netsh helper persistence", "T1546.007"),
        ("Silent execution (no UI/admin cue)", "T1564"),
        ("LSA authentication-provider persistence", "T1547.005"),
        ("Generic Service Manager names/descriptions", "T1036"),
        ("LD_PRELOAD on every binary exec", "T1574.006"),
        ("Scheduled-task XML command-line hiding", "T1053.005"),
        ("Async background integrity of persistence", "T1547"),
        ("Encrypted payload inside .bat/.sh", "T1027"),
        ("Print-monitor persistence", "T1547.010"),
        ("Automatic temp-file artifact cleanup", "T1070"),
        ("Office template document persistence", "T1137.001"),
        ("LOCAL SYSTEM service-wide persistence", "T1543.003"),
        ("Memory-safe service (no crash Event Log)", "T1543"),
        ("Base64/XOR registry value data", "T1027"),
        ("Winlogon shell hijacking", "T1547.004"),
        ("Linux inittab persistence (legacy)", "T1037"),
        ("GPO persistence (if privileges allow)", "T1484.001"),
        ("Fast recovery after reboot", "T1547"),
        ("Safe error handling (no leftover traces)", "T1070"),
        ("Encrypted agent token inside binary", "T1552"),
        ("Browser-extension persistence", "T1176.001"),
        ("svchost ServiceDLL persistence", "T1543.003"),
        ("Custom Linux boot-log hiding", "T1070"),
        ("Persistence-method rotation per update", "T1027"),
        ("Command Center one-shot fail-safe wipe", "T1485"),
    ],
    &[
        ("AES-GCM masking of agent code pages", "T1027"),
        ("DJB2 API function hashing (IAT strings)", "T1027.007"),
        ("SIMD zero-overhead decrypt", "T1027"),
        ("On-demand string decrypt in memory", "T1027.013"),
        ("Runtime polymorphic memory signatures", "T1027"),
        ("Lazy DLL load + immediate unload", "T1129"),
        ("Compile-time function-name macros", "T1027"),
        ("Jump-oriented programming sequences", "T1027"),
        ("Idle heap-region encryption", "T1027"),
        ("Memory-safe encrypted buffers", "T1027"),
        ("Re-encrypt on EDR code-page scan", "T1027"),
        ("Control-flow flattening", "T1027"),
        ("Opaque predicates vs static analysis", "T1027"),
        ("Globals moved to encrypted heap", "T1027"),
        ("Selective real-time block decrypt", "T1027"),
        ("Per-build macro hashing", "T1027.001"),
        ("IAT spoof with benign imports", "T1036"),
        ("Randomized function pointers", "T1027"),
        ("Stack-frame padding vs walking", "T1106"),
        ("Trait-hidden implementations", "T1027"),
        ("Encrypted code-section integrity", "T1027"),
        ("Encrypted PE resource section", "T1027"),
        ("Self-modifying in-memory logic", "T1027.009"),
        ("Debug-symbol strip in release", "T1027"),
        ("Minimal plaintext code footprint", "T1027"),
        ("Serde-encrypted in-memory config", "T1027"),
        ("Syscall stub swapping (ch.2)", "T1106"),
        ("ROP for sensitive operations", "T1106"),
        ("Entropy padding vs packed-payload detectors", "T1027.002"),
        ("PhantomData for hidden memory", "T1027"),
        ("Destroy keys on active dump", "T1485"),
        ("Time-spread API call patterns", "T1070"),
        ("Polymorphic payloads per server push", "T1027"),
        ("Anti-timing on decrypt path", "T1497.003"),
        ("Multi-threaded region masking", "T1027"),
        ("Controlled unsafe memory ops", "T1055"),
        ("Hidden SEH exception handlers", "T1620"),
        ("Internal interpreter VM obfuscation", "T1027"),
        ("In-memory PE header wipe after load", "T1070"),
        ("Strong typing during dynamic decrypt", "T1027"),
        ("Working-set EDR physical-page scans", "T1082"),
        ("Thread entry-point masquerade", "T1055"),
        ("Runtime dynamic code generation", "T1027.009"),
        ("Obfuscated jump tables", "T1027"),
        ("Low-latency hashed API resolve", "T1027.007"),
        ("Dynamic masking-algorithm enum", "T1027"),
        ("Custom allocator vs EDR heap watch", "T1055"),
        ("Continuous anti-forensics wipe", "T1070"),
        ("Gradual payload decrypt per task", "T1027"),
        ("Fail-safe full re-encrypt on hostile scan", "T1485"),
    ],
    &[
        ("ETW EtwEventWrite patch posture", "T1562.006"),
        ("Critical event-log write delay", "T1562.002"),
        ("Industrial-silence during exploitation window", "T1562.001"),
        ("Automatic fail-safe restore of monitoring", "T1562"),
        ("Registry persistence-change telemetry", "T1112"),
        ("WFP local traffic-logic filter", "T1562.004"),
        ("Security Center AV-status masquerade", "T1562.001"),
        ("Crash-free kernel-structure patching", "T1562"),
        ("PsSetCreateProcessNotifyRoutine posture", "T1562.001"),
        ("Mini-filter disk-access telemetry", "T1562.001"),
        ("ReadProcessMemory from defense processes", "T1055"),
        ("User-mode log-call NULL routing", "T1562.002"),
        ("New-thread creation telemetry", "T1055.002"),
        ("Millisecond blinding latency", "T1562"),
        ("Async re-apply if XDR unblinds", "T1562"),
        ("Agent C2 DNS-query masquerade", "T1071.004"),
        ("AMSI in-memory disable posture", "T1562.001"),
        ("Selective |z|>6 event blocking", "T1562"),
        ("Kernel-callback thread-context protection", "T1562.001"),
        ("USB enumeration event masquerade", "T1562"),
        ("Local SIEM-agent channel block", "T1562.001"),
        ("WMI system-info query blinding", "T1047"),
        ("LSASS-memory access alert suppression", "T1003.001"),
        ("Multi-EDR vendor-specific blinding", "T1562.001"),
        ("Memory-safe patch protection", "T1562"),
        ("PowerShell Script Block Logging", "T1562.002"),
        ("Object-access auditing events", "T1562.002"),
        ("PEB-scanner disable", "T1562.001"),
        ("SeDebugPrivilege use masquerade", "T1134"),
        ("Logon/logoff event masquerade", "T1078"),
        ("Sysmon user-mode event block", "T1562.001"),
        ("Typed ETW message filtering", "T1562.006"),
        ("Sensitive-process handle-open events", "T1562"),
        ("ACL-change event masquerade", "T1222"),
        ("AppLocker block-log suppression", "T1562.001"),
        ("Direct syscalls inside blinding (ch.2)", "T1106"),
        ("Local firewall-rule change telemetry", "T1562.004"),
        ("SCM persistence-service create events", "T1543.003"),
        ("Active debugger telemetry", "T1622"),
        ("Per-build unique blinding stubs", "T1027"),
        ("Boot / system-integrity events", "T1562"),
        ("Task Scheduler create events", "T1053.005"),
        ("Active WMI eventing filters", "T1546.003"),
        ("Safe WriteProcessMemory wrappers", "T1055"),
        ("COM object-create injection events", "T1559.001"),
        ("Registry value-set events", "T1112"),
        ("WSS+JWT channel masquerade", "T1071.001"),
        ("Result-gated continue-only-if-blinded", "T1562"),
        ("Agent DLL-load events", "T1574"),
        ("Fail-safe restore of all hooks if agent dies", "T1485"),
    ],
    &[
        ("Safe Rust event ring-buffer", "T1071.001"),
        ("WSS+JWT encrypted channel", "T1071.001"),
        ("Packet-size latency vs NIDS", "T1071"),
        ("Zero-copy buffer-to-socket ingest", "T1071"),
        ("AES-GCM encrypted ring-buffer slots", "T1027"),
        ("Multi-threaded telemetry sources", "T1071"),
        ("Fast SSL reconnect handshake", "T1573.002"),
        ("Tokio fan-in of agent connections", "T1071"),
        ("Bandwidth-thrifty heartbeat", "T1071"),
        ("Realtime Zstd compression", "T1027"),
        ("Browser-like WSS headers", "T1071.001"),
        ("MessagePack vs JSON payload", "T1071"),
        ("|z|>6 priority queue in buffer", "T1071"),
        ("Exponential retry after outage", "T1071"),
        ("Mutual TLS agent↔server", "T1573.002"),
        ("Minimal WebSocket frame overhead", "T1071"),
        ("Mutex-protected async buffer", "T1071"),
        ("Traffic-signature spoof vs IDS/IPS", "T1036"),
        ("Server write backpressure to DB", "T1071"),
        ("Swappable communication-channel traits", "T1071"),
        ("Periodic in-memory key rotation", "T1573"),
        ("Forward error correction on lossy nets", "T1071"),
        ("Pin buffer memory during async send", "T1071"),
        ("Domain-fronting URL masquerade posture", "T1090.004"),
        ("Smart event batching", "T1071"),
        ("Strongly typed messages", "T1071"),
        ("ACK-driven ring-buffer reclaim", "T1071"),
        ("Backend WS thread-pool", "T1071"),
        ("Cargo-feature protocol compile-out", "T1027"),
        ("Chrome/120 User-Agent masquerade", "T1071.001"),
        ("Secondary-server failover (HA)", "T1071"),
        ("Memory-safe overflow protection", "T1071"),
        ("Per-agent bandwidth quotas", "T1071"),
        ("Low-power device support", "T1071"),
        ("Message status enum (Pending/Tx/Acked)", "T1071"),
        ("WSS on TCP/443", "T1071.001"),
        ("Short-TTL JWT on WSS", "T1078"),
        ("DMA-class transfer posture", "T1071"),
        ("RTT-adaptive send rate", "T1071"),
        ("Random padding vs entropy analysis", "T1027"),
        ("Typed connection-state structs", "T1071"),
        ("Out-of-band urgent command channel", "T1071"),
        ("Buffer fragmentation control", "T1071"),
        ("Lifetime-correct channel refs", "T1071"),
        ("DNS-over-HTTPS lookups", "T1071.004"),
        ("Internal rate limiting", "T1071"),
        ("cargo-audit of comms crates", "T1195.001"),
        ("simd-json backend parse", "T1071"),
        ("Unit/integration tests of channels", "T1071"),
        ("Fail-safe ring-buffer wipe on compromise", "T1485"),
    ],
    &[
        ("Hard RLS policies on tenant_id", "T1078"),
        ("SQLx driver auto-injects tenant_id", "T1078"),
        ("weissman_auth BYPASSRLS only for login lookup", "T1078"),
        ("Ask-Weissman NL→SQL always tenant-filtered", "T1190"),
        ("Per-API-request Postgres session", "T1078"),
        ("Cross-tenant FK leakage prevention", "T1078"),
        ("pgvector(1536) RAG isolation per tenant", "T1078"),
        ("Per-tenant encryption keys in backend memory", "T1552"),
        ("Per-tenant DB quotas (resource exhaustion)", "T1499"),
        ("Strongly typed Tenant IDs", "T1078"),
        ("Middleware tenant membership check", "T1078"),
        ("Ask-Weissman QueryPlan JSON (no raw SQL inj)", "T1190"),
        ("weissman_ro Ask API 15s statement_timeout", "T1078"),
        ("Partial indexes on tenant_id", "T1078"),
        ("Compile-time RLS filter macros", "T1078"),
        ("Per-tenant audit_logs isolation", "T1078"),
        ("Redis key prefix per tenant", "T1078"),
        ("Per-tenant API rate limits", "T1499"),
        ("Serde schema validation per tenant", "T1078"),
        ("Random UUID tenant ids (no readable names)", "T1078"),
        ("Worker jobs claimed in tenant RLS context", "T1078"),
        ("Per-tenant MFA policy", "T1556"),
        ("SQLx compile-time query checks vs isolated schema", "T1078"),
        ("UEBA baseline |z| inside tenant data only", "T1078"),
        ("Block tenant access to internal tables", "T1078"),
        ("VACUUM strategy for large multi-tenant tables", "T1078"),
        ("RLS errors never leak technical detail", "T1078"),
        ("SOAR playbooks only on approved tenant assets", "T1078"),
        ("Redis keyspace isolation", "T1078"),
        ("Scope validation (no cross-tenant scan)", "T1078"),
        ("Isolated Postgres views for per-tenant reports", "T1078"),
        ("Per-tenant FAIR SLE/ALE", "T1486"),
        ("Constant-time tenant lookups", "T1078"),
        ("RBAC enums Viewer→CEO", "T1078"),
        ("Per-tenant immutable audit trail", "T1078"),
        ("Region policy IL/EU/US (Directive 361)", "T1078"),
        ("Transaction isolation vs parallel leaks", "T1078"),
        ("KEV/EPSS enrichment without cross-tenant PII", "T1078"),
        ("Locked-down public schema", "T1078"),
        ("Per-tenant connection-pool caps", "T1499"),
        ("Typed Tenant Config structs", "T1078"),
        ("Per-tenant Ask-Weissman allow-list", "T1190"),
        ("Anonymous request IDs in errors", "T1078"),
        ("Per-tenant retention (UEBA 14d)", "T1070"),
        ("Advisory locks in tenant context", "T1078"),
        ("Webhook dispatch only to tenant-approved dest", "T1078"),
        ("In-memory isolated PDF reports", "T1078"),
        ("Automated RLS policy unit tests", "T1078"),
        ("Agents bound only to originating tenant", "T1078"),
        ("Fail-safe tenant disable on cross-tenant leak", "T1485"),
    ],
    &[
        ("Postgres COPY thousands of rows/sec", "T1071"),
        ("SKIP LOCKED job claim (no contention hang)", "T1071"),
        ("Tokio workers per CPU core", "T1071"),
        ("Dedicated pending-job partial index", "T1071"),
        ("SQLx type-safe bulk writes", "T1071"),
        ("Worker heartbeat + reclaim crashed jobs", "T1071"),
        ("COPY batch-size memory/speed balance", "T1071"),
        ("Partial indexes for new-job search", "T1071"),
        ("Priority queues (scan before maintenance)", "T1071"),
        ("Local worker-thread mutex state", "T1071"),
        ("Smart backoff on DB I/O wait", "T1071"),
        ("JSONB processed in Rust before write", "T1071"),
        ("Lifetimes on bulk write buffers", "T1071"),
        ("Automatic retry attempt counter", "T1071"),
        ("Partitioned agent_metric_samples", "T1071"),
        ("Reduced per-row transaction overhead", "T1071"),
        ("Job FSM Claimed→Running→Completed", "T1071"),
        ("Per-kind job timeouts", "T1071"),
        ("MessagePack payload shrink Agent→Worker", "T1071"),
        ("Index-maintenance IO during bulk write", "T1071"),
        ("Strongly typed job IDs (no cross-tenant mix)", "T1078"),
        ("Graceful shutdown drains in-flight jobs", "T1071"),
        ("Advisory locks for sensitive worker logic", "T1071"),
        ("RLS still enforced during bulk ingest", "T1078"),
        ("Synthetic-load unit tests", "T1071"),
        ("Auto-scale workers from queue depth", "T1071"),
        ("SQLx offline query checks", "T1071"),
        ("Long-job memory-leak prevention", "T1071"),
        ("Option handling for missing ingest fields", "T1071"),
        ("Sha256 dedup of scan findings", "T1071"),
        ("Checkpoint tuning for bulk write", "T1071"),
        ("Efficient worker audit logs", "T1071"),
        ("Worker trait for new scan engines", "T1071"),
        ("Postgres HA load-balancing", "T1071"),
        ("cargo bench bottleneck hunt", "T1071"),
        ("Read fetch-size wait reduction", "T1071"),
        ("WAL durability on crash", "T1071"),
        ("Queue-length monitoring alerts", "T1071"),
        ("Dynamic COPY query macros", "T1071"),
        ("Hundreds of concurrent reporting agents", "T1071"),
        ("Detailed worker error handling", "T1071"),
        ("14-day cleanup of weissman_async_jobs", "T1070"),
        ("GIN indexes on finding JSONB", "T1071"),
        ("Thread pool sized to vCPU", "T1071"),
        ("Safe Send/Sync across threads", "T1071"),
        ("DB write rate limiting", "T1499"),
        ("SQLx migration runner before worker start", "T1071"),
        ("Connection timeout vs stuck workers", "T1071"),
        ("Smart pointers for large in-memory structs", "T1071"),
        ("Fail-safe release of claimed jobs on crash", "T1485"),
    ],
    &[
        ("Ask-Weissman QueryPlan stays in allow-list", "T1190"),
        ("0-gaps wiring of all production engines", "T1553"),
        ("MITRE ATT&CK mapping with 0 stale IDs", "T1553"),
        ("proof_of_exploit blocked without explicit config", "T1203"),
        ("engine_reality_audit live-probe provenance", "T1553"),
        ("SHA-384 of Postgres migrations", "T1553"),
        ("Rust integration: server + worker + agent", "T1553"),
        ("Agent binary size ≤5MB stripped release", "T1027"),
        ("UEBA |z| accuracy vs ground-truth sets", "T1553"),
        ("Automated cross-tenant RLS probe (must block)", "T1078"),
        ("OpenAPI 3.1 /api/docs matches implementation", "T1553"),
        ("CI benchmarks block API latency regressions", "T1553"),
        ("Refuse boot with WEISSMAN_ALLOW_INSECURE_TLS=1", "T1573"),
        ("Audit-log coverage of asset/finding changes", "T1553"),
        ("KEV/EPSS enrichment on CVE findings", "T1588.006"),
        ("Playwright live Command Center E2E", "T1553"),
        ("SOAR playbook dispatch to approved dest only", "T1078"),
        ("MFA TOTP required for login", "T1556"),
        ("RBAC Viewer→CEO hierarchy", "T1078"),
        ("Cargo clippy + fmt quality gate", "T1553"),
        ("Ring-buffer integrity under packet loss", "T1071"),
        ("WSS encryption + integrity per heartbeat", "T1573.002"),
        ("Asset-value USD SLE/ALE rules", "T1486"),
        ("False-positive suppression after 3 analyst marks", "T1553"),
        ("CISA KEV refresh every 6h", "T1588.006"),
        ("FIRST.org EPSS backfill every 12h", "T1588.006"),
        ("Dijkstra attack-path to crown jewel", "T1553"),
        ("Constant-time token compares", "T1553"),
        ("No-transaction CREATE INDEX CONCURRENTLY", "T1553"),
        ("full_audit_gate.sh G1–G7 100% required", "T1553"),
        ("Region IL / Directive 361 compliance", "T1078"),
        ("SLA 99.95% availability target", "T1553"),
        ("Integrations vault AES-256-GCM", "T1552"),
        ("Ask Weissman blocks users/audit_logs tables", "T1190"),
        ("UEBA hourly purge (>14d)", "T1070"),
        ("Billable-engine finding attribution", "T1553"),
        ("Agent SHA256 manifest (package_agent_binaries)", "T1553"),
        ("Postgres max_connections 200", "T1499"),
        ("Redis stream heartbeats for job bus", "T1071"),
        ("Nginx serves SPA at /command-center/", "T1553"),
        ("Refuse boot on weak secrets (changeme)", "T1552"),
        ("/api/health reflects all services", "T1553"),
        ("Agent auto-update signed & safe", "T1553"),
        ("Memory-forensics resistance (RPM)", "T1055"),
        ("Scan-target scope validation", "T1078"),
        ("Bulk COPY rollback integrity", "T1071"),
        ("Caddy/Nginx Let's Encrypt auto-renew", "T1573"),
        ("Supreme Council pgvector retrieval accuracy", "T1553"),
        ("Financial blast-radius USD accuracy", "T1486"),
        ("Fail-safe: no deploy unless CI is 100%", "T1485"),
    ],
];

pub fn catalog() -> Vec<Check> {
    let mut out = Vec::with_capacity(CATALOG_LEN);
    for (di, titles) in TITLES.iter().enumerate() {
        let domain = (di + 1) as u8;
        for (ci, (title, mitre)) in titles.iter().enumerate() {
            let id = (di * CHECKS_PER_DOMAIN + ci + 1) as u16;
            out.push(Check {
                id,
                domain,
                title,
                mitre,
                fail_safe: ci + 1 == CHECKS_PER_DOMAIN,
            });
        }
    }
    out
}

pub fn domain_meta(id: u8) -> Option<&'static DomainMeta> {
    DOMAINS.iter().find(|d| d.id == id)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn catalog_is_exactly_500_unique_ids() {
        let c = catalog();
        assert_eq!(c.len(), CATALOG_LEN);
        let ids: HashSet<_> = c.iter().map(|x| x.id).collect();
        assert_eq!(ids.len(), CATALOG_LEN);
        assert_eq!(*ids.iter().min().unwrap(), 1);
        assert_eq!(*ids.iter().max().unwrap(), 500);
        for d in 1u8..=10 {
            assert_eq!(c.iter().filter(|x| x.domain == d).count(), 50);
        }
        assert_eq!(c.iter().filter(|x| x.fail_safe).count(), 10);
    }
}
