//! Scan engine identifiers — canonical list matches orchestrator `ALL_ENGINES` / client config.

use serde::{Deserialize, Serialize};
use std::fmt;
use utoipa::ToSchema;

/// Known SOC engines (`snake_case` in JSON and `client_configs.enabled_engines`).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "snake_case")]
#[schema(description = "Registered scan engine id (snake_case)")]
pub enum EngineId {
    Osint,
    Asm,
    SupplyChain,
    LeakHunter,
    BolaIdor,
    LlmPathFuzz,
    SemanticAiFuzz,
    MicrosecondTiming,
    AiAdversarialRedteam,
}

impl EngineId {
    #[must_use]
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Osint => "osint",
            Self::Asm => "asm",
            Self::SupplyChain => "supply_chain",
            Self::LeakHunter => "leak_hunter",
            Self::BolaIdor => "bola_idor",
            Self::LlmPathFuzz => "llm_path_fuzz",
            Self::SemanticAiFuzz => "semantic_ai_fuzz",
            Self::MicrosecondTiming => "microsecond_timing",
            Self::AiAdversarialRedteam => "ai_adversarial_redteam",
        }
    }

    #[must_use]
    pub fn parse(s: &str) -> Option<Self> {
        match s.trim() {
            "osint" => Some(Self::Osint),
            "asm" => Some(Self::Asm),
            "supply_chain" => Some(Self::SupplyChain),
            "leak_hunter" => Some(Self::LeakHunter),
            "bola_idor" => Some(Self::BolaIdor),
            "llm_path_fuzz" | "ollama_fuzz" => Some(Self::LlmPathFuzz),
            "semantic_ai_fuzz" => Some(Self::SemanticAiFuzz),
            "microsecond_timing" => Some(Self::MicrosecondTiming),
            "ai_adversarial_redteam" => Some(Self::AiAdversarialRedteam),
            _ => None,
        }
    }
}

impl fmt::Display for EngineId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Stable list for validation / defaults (same order as legacy `ALL_ENGINES`).
pub const KNOWN_ENGINE_IDS: &[&str] = &[
    "osint",
    "asm",
    "supply_chain",
    "leak_hunter",
    "bola_idor",
    "llm_path_fuzz",
    "semantic_ai_fuzz",
    "microsecond_timing",
    "ai_adversarial_redteam",
];

/// Full ordered registry of all 303 engines in proper execution order.
/// Matches frontend/src/lib/enginesRegistry.js
pub const FULL_ENGINE_REGISTRY_ORDER: &[&str] = &[
    // Recon & OSINT (run first to discover attack surface)
    "osint",
    "asm",
    "leak_hunter",
    "discovery_engine",
    "recon",
    // Web / API attacks
    "bola_idor",
    "graphql_attack",
    "jwt_attack",
    "oauth_oidc",
    "http_smuggling",
    "prototype_pollution",
    "ssrf_advanced",
    "xxe",
    "ssti",
    "file_upload",
    "websocket_attack",
    "cache_poisoning",
    // AI / LLM
    "llm_path_fuzz",
    "semantic_ai_fuzz",
    "ai_adversarial_redteam",
    "llm_redteam",
    "adversarial_ml",
    "autonomous_pentest",
    // Cloud / Infra
    "aws_attack",
    "azure_attack",
    "gcp_attack",
    "k8s_container",
    "iac_misconfig",
    "serverless_attack",
    // OT / ICS / IoT
    "scada_ics",
    "iot_firmware",
    "ble_rf",
    // Stealth / Evasion
    "edr_evasion",
    "waf_bypass",
    "timing_sidechannel",
    "antiforensics",
    "stealth_engine",
    // Crypto / Identity
    "pki_tls",
    "pqc_scanner",
    "password_spray",
    "kerberoasting",
    "saml_attack",
    "crypto_engine",
    // Network / Protocol
    "bgp_dns_hijacking",
    "ipv6_attack",
    "mtls_grpc",
    "smb_netbios",
    // Supply Chain
    "supply_chain",
    "cicd_pipeline",
    "container_registry",
    "sbom_analyzer",
    "typosquatting_monitor",
    // APT / Top-Tier (run last as they may depend on previous findings)
    "kill_chain",
    "oast_oob",
    "deception_honeypot",
    "digital_twin",
    "zero_day_prediction",
    "threat_emulation",
    "poe_synthesis",
    "satellite_recon",
    "darkweb_intel",
    "financial_osint",
    "blockchain_trace",
    "metadata_harvest",
    "patent_recon",
    "telecom_osint",
    "iot_shodan_scan",
    "job_posting_osint",
    "github_secret_scan",
    "graphql_deep_attack",
    "grpc_reflection_attack",
    "http2_attack",
    "swagger_abuse",
    "soap_injection",
    "odata_injection",
    "css_injection",
    "template_injection_adv",
    "http_parameter_pollution",
    "api_mass_assignment",
    "web_cache_poison_adv",
    "clickjacking_engine",
    "subdomain_takeover",
    "file_inclusion_rfi",
    "deserialization_net",
    "nosql_deep_injection",
    "jwt_advanced_attack",
    "api_rate_limit_bypass",
    "idor_advanced",
    "prompt_injection_chain",
    "model_inversion_attack",
    "ai_supply_chain_attack",
    "rag_poisoning_engine",
    "adversarial_examples",
    "data_poisoning_engine",
    "deepfake_synthesis",
    "llm_dos_attack",
    "gpt_plugin_attack",
    "autonomous_ai_escape",
    "llm_memory_extraction",
    "neural_backdoor_detect",
    "federated_learning_attack",
    "llm_red_team_advanced",
    "model_stealing_engine",
    "cloud_metadata_ssrf",
    "s3_bucket_attack",
    "lambda_escape",
    "cloud_iam_escalation",
    "kubernetes_rbac_escape",
    "azure_devops_attack",
    "gcp_privilege_attack",
    "terraform_state_attack",
    "cloudformation_injection",
    "service_mesh_attack",
    "cloud_audit_evasion",
    "ecr_registry_attack",
    "cloud_worm_propagation",
    "serverless_injection",
    "cloud_data_exfil",
    "eks_attack",
    "cloud_network_attack",
    "secrets_manager_attack",
    "cloud_privilege_persistence",
    "modbus_attack",
    "mqtt_attack",
    "coap_attack",
    "opcua_attack",
    "plc_logic_attack",
    "hmi_attack",
    "satellite_comm_attack",
    "firmware_emulation_attack",
    "profinet_attack",
    "rfid_nfc_attack",
    "industrial_protocol_fuzz",
    "dll_hijacking_engine",
    "sandbox_evasion",
    "rootkit_simulation",
    "memory_forensics_evasion",
    "av_bypass_engine",
    "dns_tunneling_c2",
    "steganography_c2",
    "https_c2_masquerade",
    "icmp_covert",
    "rop_chain_engine",
    "timing_evasion_engine",
    "log_tampering_engine",
    "jit_spray",
    "com_hijacking",
    "network_traffic_masking",
    "anti_debug_evasion",
    "parent_pid_spoof",
    "padding_oracle_attack",
    "hash_extension_attack",
    "ecdsa_nonce_bias",
    "rsa_timing_attack",
    "mfa_bypass_engine",
    "kerberos_attack_suite",
    "pki_hierarchy_attack",
    "session_fixation_adv",
    "password_hash_crack",
    "oauth_advanced_attack",
    "saml_advanced_attack",
    "quantum_key_attack",
    "password_spray_advanced",
    "arp_spoofing_engine",
    "vlan_hopping_attack",
    "dhcp_attack_engine",
    "dns_cache_poisoning",
    "snmp_exploitation",
    "rdp_attack_engine",
    "ldap_injection_engine",
    "ss7_attack_simulation",
    "wifi_attack_engine",
    "bluetooth_attack_engine",
    "ospf_bgp_hijack",
    "mpls_vpn_attack",
    "lte_5g_attack",
    "ipv6_advanced_attack",
    "network_covert_channel",
    "wpa3_attack_engine",
    "tor_exit_attack",
    "protocol_downgrade",
    "npm_package_attack",
    "pypi_supply_chain",
    "github_actions_attack",
    "docker_image_poison",
    "maven_supply_chain",
    "compiler_backdoor",
    "cdn_poisoning_engine",
    "software_signing_attack",
    "build_system_compromise",
    "update_hijacking",
    "sbom_forgery_engine",
    "third_party_api_attack",
    "iac_supply_chain",
    "apt28_techniques",
    "apt29_techniques",
    "apt41_techniques",
    "lazarus_group_ttps",
    "volt_typhoon_ttps",
    "scattered_spider_ttps",
    "salt_typhoon_ttps",
    "fin7_techniques",
    "conti_ransomware_ttps",
    "lockbit_techniques",
    "cl0p_techniques",
    "blackcat_alphv_ttps",
    "midnight_blizzard_ttps",
    "earth_longzhi_ttps",
    "equation_group_ttps",
    "sandworm_techniques",
    "carbon_spider_ttps",
    "wizard_spider_ttps",
    "unc2452_ttps",
    "unc3944_ttps",
    "quantum_sovereign_nexus",
    "bootkit_uefi",
    "fileless_malware_engine",
    "polymorphic_engine",
    "botnet_c2_engine",
    "keylogger_engine",
    "spyware_stalkerware",
    "worm_propagation",
    "rce_exploit_engine",
    "persistence_mechanism",
    "lateral_movement_engine",
    "data_staging_engine",
    "exploit_kit_engine",
    "trojan_dropper",
    "macro_malware",
    "spear_phishing_engine",
    "vishing_engine",
    "smishing_engine",
    "qr_phishing",
    "deepfake_voice_engine",
    "business_email_compromise",
    "watering_hole_attack",
    "pretexting_engine",
    "insider_threat_engine",
    "brand_impersonation",
    "fake_update_engine",
    "linkedin_phishing",
    "callback_phishing",
    "physical_social_eng",
    "typosquatting_phishing",
    "android_malware_engine",
    "ios_exploit_engine",
    "mobile_mitm",
    "ssl_pinning_bypass",
    "android_intent_attack",
    "ios_url_scheme_attack",
    "mobile_overlay_attack",
    "sim_swap_engine",
    "mobile_banking_trojan",
    "app_store_attack",
    "mdm_bypass_engine",
    "bluetooth_mobile_attack",
    "nfc_relay_attack",
    "mobile_spyware_engine",
    "react_native_attack",
    "dns_exfil_engine",
    "http_covert_exfil",
    "cloud_exfil_engine",
    "encrypted_exfil",
    "acoustic_exfil",
    "em_exfil_engine",
    "optical_exfil",
    "cache_timing_exfil",
    "keyboard_acoustic",
    "screen_capture_exfil",
    "clipboard_hijack",
    "database_exfil",
    "email_exfil",
    "insider_exfil",
    "storage_covert_channel",
    "threat_intel_fusion",
    "attack_surface_quantify",
    "adversarial_simulation",
    "dark_web_monitor",
    "passive_dns_forensics",
    "network_baseline_anomaly",
    "packet_injection_engine",
    "network_tap_advanced",
    "multicast_attack",
    "nat_traversal_attack",
    "graphql_subscription_attack",
    "webrtc_attack",
    "web3_dapp_attack",
    "api_gateway_bypass",
];

#[must_use]
pub fn is_known_engine_id(s: &str) -> bool {
    KNOWN_ENGINE_IDS.iter().any(|&k| k == s.trim()) 
        || FULL_ENGINE_REGISTRY_ORDER.iter().any(|&k| k == s.trim())
}

#[must_use]
pub fn default_enabled_engine_ids() -> Vec<String> {
    KNOWN_ENGINE_IDS.iter().map(|s| (*s).to_string()).collect()
}

/// Order a list of engine IDs by their position in the registry.
/// Engines not in the registry are placed at the end.
#[must_use]
pub fn order_engines_by_registry(engines: &[String]) -> Vec<String> {
    let mut ordered: Vec<(usize, String)> = engines
        .iter()
        .map(|e| {
            let pos = FULL_ENGINE_REGISTRY_ORDER
                .iter()
                .position(|&r| r == e.as_str())
                .unwrap_or(usize::MAX);
            (pos, e.clone())
        })
        .collect();
    ordered.sort_by_key(|(pos, _)| *pos);
    ordered.into_iter().map(|(_, e)| e).collect()
}
