//! Scan engine identifiers — canonical list matches orchestrator `ALL_ENGINES` / client config.

use serde::{Deserialize, Serialize};
use std::fmt;
use utoipa::ToSchema;

/// Known SOC engines (`snake_case` in JSON and `client_configs.enabled_engines`).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "snake_case")]
#[schema(description = "Registered scan engine id (snake_case)")]
pub enum EngineId {
    Osint,
    Asm,
    SupplyChain,
    LeakHunter,
    BolaIdor,
    LlmPathFuzz,
    SemanticAiFuzz,
    MicrosecondTiming,
    AiAdversarialRedteam,
}

impl EngineId {
    #[must_use]
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Osint => "osint",
            Self::Asm => "asm",
            Self::SupplyChain => "supply_chain",
            Self::LeakHunter => "leak_hunter",
            Self::BolaIdor => "bola_idor",
            Self::LlmPathFuzz => "llm_path_fuzz",
            Self::SemanticAiFuzz => "semantic_ai_fuzz",
            Self::MicrosecondTiming => "microsecond_timing",
            Self::AiAdversarialRedteam => "ai_adversarial_redteam",
        }
    }

    #[must_use]
    pub fn parse(s: &str) -> Option<Self> {
        match s.trim() {
            "osint" => Some(Self::Osint),
            "asm" => Some(Self::Asm),
            "supply_chain" => Some(Self::SupplyChain),
            "leak_hunter" => Some(Self::LeakHunter),
            "bola_idor" => Some(Self::BolaIdor),
            "llm_path_fuzz" | "ollama_fuzz" => Some(Self::LlmPathFuzz),
            "semantic_ai_fuzz" => Some(Self::SemanticAiFuzz),
            "microsecond_timing" => Some(Self::MicrosecondTiming),
            "ai_adversarial_redteam" => Some(Self::AiAdversarialRedteam),
            _ => None,
        }
    }
}

impl fmt::Display for EngineId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Stable list for validation / defaults (core orchestrator cycle).
pub const KNOWN_ENGINE_IDS: &[&str] = &[
    "osint",
    "asm",
    "supply_chain",
    "leak_hunter",
    "bola_idor",
    "llm_path_fuzz",
    "semantic_ai_fuzz",
    "microsecond_timing",
    "ai_adversarial_redteam",
];

/// Engines with live Rust/Python probes (no simulated findings). UI Engine Room uses this list.
pub const PRODUCTION_ENGINE_IDS: &[&str] = &[
    // ── Core engines ──────────────────────────────────────────────────────────
    "osint",
    "asm",
    "leak_hunter",
    "discovery_engine",
    "recon",
    "supply_chain",
    "bola_idor",
    "graphql_attack",
    "jwt_attack",
    "oauth_oidc",
    "http_smuggling",
    "prototype_pollution",
    "ssrf_advanced",
    "xxe",
    "ssti",
    "file_upload",
    "websocket_attack",
    "cache_poisoning",
    "llm_path_fuzz",
    "semantic_ai_fuzz",
    "ai_adversarial_redteam",
    "llm_redteam",
    "adversarial_ml",
    "autonomous_pentest",
    "nexus_sovereign_swarm",
    "http_feedback_fuzz",
    "aws_attack",
    "cloud_posture",
    "azure_attack",
    "gcp_attack",
    "k8s_container",
    "iac_misconfig",
    "serverless_attack",
    "scada_ics",
    // Critical infrastructure (RoE-gated; `high_risk_engines` compile feature)
    "avionics_adsb_attack",
    "maritime_ais_attack",
    "ev_charging_ocpp_attack",
    "smart_grid_dlms_attack",
    "rail_signaling_attack",
    "building_automation_attack",
    "robotics_ros2_attack",
    "ot_sis_triton_attack",
    "iot_firmware",
    "ble_rf",
    "edr_evasion",
    "waf_bypass",
    "timing_sidechannel",
    "antiforensics",
    "stealth_engine",
    "pki_tls",
    "pqc_scanner",
    "password_spray",
    "kerberoasting",
    "saml_attack",
    "crypto_engine",
    "email_dns_posture",
    "bgp_dns_hijacking",
    "ipv6_attack",
    "mtls_grpc",
    "smb_netbios",
    "cicd_pipeline",
    "container_registry",
    "sbom_analyzer",
    "typosquatting_monitor",
    "kill_chain",
    "oast_oob",
    "deception_honeypot",
    "digital_twin",
    "zero_day_prediction",
    "threat_emulation",
    "poe_synthesis",
    "microsecond_timing",
    // ── Advanced AI / LLM engines ─────────────────────────────────────────────
    "llm_jailbreak",
    "prompt_injection_chain",
    "model_inversion_attack",
    "ai_supply_chain_attack",
    "llm_agent_hijack",
    "rag_poisoning_engine",
    "adversarial_examples",
    "data_poisoning_engine",
    "deepfake_synthesis",
    "llm_dos_attack",
    "multimodal_ai_attack",
    "ai_bias_exploit",
    "gpt_plugin_attack",
    "autonomous_ai_escape",
    "llm_memory_extraction",
    "neural_backdoor_detect",
    "ai_watermark_bypass",
    "federated_learning_attack",
    "llm_red_team_advanced",
    "model_stealing_engine",
    "prompt_injection_brake",
    "jailbreak_cognitive_engine",
    "rag_poisoning_guard",
    // ── Advanced APT / Top-Tier engines ───────────────────────────────────────
    "apt28_techniques",
    "apt29_techniques",
    "apt41_techniques",
    "lazarus_group_ttps",
    "volt_typhoon_ttps",
    "scattered_spider_ttps",
    "salt_typhoon_ttps",
    "fin7_techniques",
    "conti_ransomware_ttps",
    "lockbit_techniques",
    "cl0p_techniques",
    "blackcat_alphv_ttps",
    "midnight_blizzard_ttps",
    "earth_longzhi_ttps",
    "equation_group_ttps",
    "sandworm_techniques",
    "carbon_spider_ttps",
    "wizard_spider_ttps",
    "unc2452_ttps",
    "unc3944_ttps",
    "quantum_sovereign_nexus",
    // ── Advanced Cloud engines ────────────────────────────────────────────────
    "lambda_escape",
    "terraform_state_attack",
    "cloudformation_injection",
    "service_mesh_attack",
    "cloud_audit_evasion",
    "ecr_registry_attack",
    "multi_cloud_pivot",
    "cloud_worm_propagation",
    "serverless_injection",
    "cloud_data_exfil",
    "cloud_network_attack",
    "cloud_privilege_persistence",
    // ── Advanced Crypto / Identity engines ───────────────────────────────────
    "padding_oracle_attack",
    "hash_extension_attack",
    "ecdsa_nonce_bias",
    "rsa_timing_attack",
    "mfa_bypass_engine",
    "credential_stuffing",
    "kerberos_attack_suite",
    "zero_trust_bypass",
    "pki_hierarchy_attack",
    "session_fixation_adv",
    "password_hash_crack",
    "quantum_key_attack",
    "password_spray_advanced",
    // ── Advanced Data Exfiltration engines ───────────────────────────────────
    "dns_exfil_engine",
    "http_covert_exfil",
    "cloud_exfil_engine",
    "encrypted_exfil",
    "acoustic_exfil",
    "em_exfil_engine",
    "optical_exfil",
    "cache_timing_exfil",
    "keyboard_acoustic",
    "screen_capture_exfil",
    "clipboard_hijack",
    "database_exfil",
    "email_exfil",
    "insider_exfil",
    "storage_covert_channel",
    // ── Advanced Malware / Ransomware engines ─────────────────────────────────
    "bootkit_uefi",
    "fileless_malware_engine",
    "polymorphic_engine",
    "botnet_c2_engine",
    "keylogger_engine",
    "spyware_stalkerware",
    "worm_propagation",
    "rce_exploit_engine",
    "persistence_mechanism",
    "lateral_movement_engine",
    "data_staging_engine",
    "exploit_kit_engine",
    "trojan_dropper",
    "macro_malware",
    // ── Advanced Mobile engines ───────────────────────────────────────────────
    "android_malware_engine",
    "ios_exploit_engine",
    "mobile_mitm",
    "ssl_pinning_bypass",
    "android_intent_attack",
    "ios_url_scheme_attack",
    "mobile_overlay_attack",
    "sim_swap_engine",
    "mobile_banking_trojan",
    "app_store_attack",
    "mdm_bypass_engine",
    "bluetooth_mobile_attack",
    "nfc_relay_attack",
    "mobile_spyware_engine",
    "react_native_attack",
    // ── Advanced Network / Protocol engines ──────────────────────────────────
    "arp_spoofing_engine",
    "vlan_hopping_attack",
    "dhcp_attack_engine",
    "dns_cache_poisoning",
    "dns_rebinding",
    "can_bus_surface",
    "ntp_amplification",
    "snmp_exploitation",
    "rdp_attack_engine",
    "ldap_injection_engine",
    "voip_sip_attack",
    "ss7_signaling_probe",
    "wifi_attack_engine",
    "bluetooth_attack_engine",
    "ospf_bgp_hijack",
    "mpls_vpn_attack",
    "lte_5g_attack",
    "network_covert_channel",
    "wpa3_attack_engine",
    "tor_exit_attack",
    "protocol_downgrade",
    "network_baseline_anomaly",
    "packet_injection_engine",
    "network_tap_advanced",
    "multicast_attack",
    "nat_traversal_attack",
    // ── Advanced OT / ICS engines ─────────────────────────────────────────────
    "dnp3_attack",
    "bacnet_attack",
    "zigbee_attack",
    "iec61850_attack",
    "satellite_comm_attack",
    "rfid_nfc_attack",
    // ── Advanced Recon engines ────────────────────────────────────────────────
    "threat_intel_fusion",
    "attack_surface_quantify",
    "external_exposure_supreme",
    "fair_exposure_fusion",
    "identity_attack_chain",
    "pipeline_to_runtime_risk",
    "risk_superposition_collapse",
    "chronos",
    "cognitive_starvation",
    "liquid_matrix",
    "sovereign_active_defense_fusion",
    "adversarial_threat_emulation",
    "dark_web_monitor",
    "passive_dns_forensics",
    // ── Advanced Social Engineering engines ──────────────────────────────────
    "spear_phishing_engine",
    "vishing_engine",
    "smishing_engine",
    "qr_phishing",
    "deepfake_voice_engine",
    "business_email_compromise",
    "watering_hole_attack",
    "pretexting_engine",
    "insider_threat_engine",
    "brand_impersonation",
    "fake_update_engine",
    "linkedin_phishing",
    "callback_phishing",
    "physical_social_eng",
    "typosquatting_phishing",
    // ── Advanced Stealth / Evasion engines ───────────────────────────────────
    "process_hollowing",
    "process_inventory",
    "usb_enumeration",
    "living_off_land",
    "heap_exploitation",
    // ── Advanced Supply Chain engines ────────────────────────────────────────
    "github_actions_attack",
    "compiler_backdoor",
    "open_source_backdoor",
    "cdn_poisoning_engine",
    "software_signing_attack",
    "build_system_compromise",
    "dependency_confusion",
    "update_hijacking",
    "sbom_forgery_engine",
    "third_party_api_attack",
    "iac_supply_chain",
    // ── Advanced Web engines ──────────────────────────────────────────────────
    "cors_misconfiguration",
    "swagger_abuse",
    "soap_injection",
    "odata_injection",
    "css_injection",
    "template_injection_adv",
    "http_parameter_pollution",
    "api_mass_assignment",
    "clickjacking_engine",
    "subdomain_takeover",
    "file_inclusion_rfi",
    "deserialization_net",
    "api_rate_limit_bypass",
    "graphql_subscription_attack",
    "webrtc_attack",
    "browser_extension_attack",
    "web3_dapp_attack",
    "api_gateway_bypass",
    "liminal_boundary",
    // ── Catalog-tier engines promoted to production (dedicated live probes) ──
    "anti_debug_evasion",
    "av_bypass_engine",
    "azure_devops_attack",
    "blockchain_trace",
    "cloud_iam_escalation",
    "cloud_metadata_ssrf",
    "coap_attack",
    "com_hijacking",
    "darkweb_intel",
    "dll_hijacking_engine",
    "dns_tunneling_c2",
    "docker_image_poison",
    "eks_attack",
    "financial_osint",
    "firmware_emulation_attack",
    "gcp_privilege_attack",
    "github_secret_scan",
    "graphql_deep_attack",
    "grpc_reflection_attack",
    "hmi_attack",
    "http2_attack",
    "https_c2_masquerade",
    "icmp_covert",
    "idor_advanced",
    "industrial_protocol_fuzz",
    "iot_shodan_scan",
    "ipv6_advanced_attack",
    "jit_spray",
    "job_posting_osint",
    "jwt_advanced_attack",
    "kubernetes_rbac_escape",
    "log_tampering_engine",
    "maven_supply_chain",
    "memory_forensics_evasion",
    "metadata_harvest",
    "modbus_attack",
    "mqtt_attack",
    "network_traffic_masking",
    "nosql_deep_injection",
    "npm_package_attack",
    "oauth_advanced_attack",
    "ollama_fuzz",
    "opcua_attack",
    "parent_pid_spoof",
    "patent_recon",
    "plc_logic_attack",
    "profinet_attack",
    "pypi_supply_chain",
    "ransomware_emulation",
    "rootkit_surface_probe",
    "rop_chain_engine",
    "s3_bucket_attack",
    "saml_advanced_attack",
    "sandbox_evasion",
    "satellite_recon",
    "secrets_manager_attack",
    "steganography_c2",
    "telecom_osint",
    "timing_evasion_engine",
    "web_cache_poison_adv",
    // ── Frontend registry aliases (dedicated alias probes) ──
    "rce_chain",
    "active_directory",
    "c2_emulation",
    "lateral_movement",
    "data_exfiltration",
    "memory_corruption",
    "browser_exploitation",
    "deepfake_genai",
    "container_escape",
    "wireless_attack",
    "mobile_attack",
    "cloud_ransomware",
    "firmware_exploit",
    "physical_security",
    "vuln_chaining",
    "sqli_advanced",
    "log4shell_scan",
    "kernel_exploit",
    "spear_phishing",
    "vlan_bypass",
    "malware_persistence",
    "insider_threat",
    "post_exploitation",
    "cloud_lateral",
    "process_injection",
    "api_fuzzing",
    "smb_relay",
    "graphql_injection",
    "container_k8s_escape",
    "web_cache_poison",
    "xxe_injection",
    "ldap_injection",
    "side_channel",
    "ssrf_chain",
    "jwt_attacks",
    "bgp_hijacking",
    "rce_deserialization",
    "active_directory_enum",
    "ransomware_sim",
    "waf_ids_bypass",
    "siem_evasion",
    "mobile_pentest",
    "cors_exploit",
    "js_prototype_pollution",
    "ipsec_vpn_audit",
    "5g_security",
    "firmware_emulation",
    "cloud_storage_audit",
    "devsecops_scan",
    "wasm_reverse",
    "bluetooth_attack",
    "oauth_abuse",
    "clickjacking",
    "email_spoofing",
    "satellite_attack",
    "ai_poisoning",
    "smart_contract_audit",
    "automotive_can_bus",
    "zero_click_exploit",
    "biometric_spoofing",
    "quantum_attack",
    "devsecops_secrets",
    "threat_hunting_apt",
    "cloud_identity_attack",
    "ci_cd_poisoning",
    "api_gateway_attack",
    "deception_evasion",
    "rag_poisoning",
    "graphene_os_bypass",
    "obfuscated_c2",
    "hardware_implant",
    "serverless_cold_start",
    "active_directory_cs",
    "data_pipeline_attack",
    "exfil_ai_inference",
    "cloud_waf_bypass",
    "telco_ss7_attack",
    "deepweb_intel",
    "network_tap_implant",
    "gitops_attack",
    "compliance_gap_scan",
    "dns_enum",
    "social_media_recon",
    "shodan_mass_scan",
    "cert_transparency",
    "email_harvest",
    "github_recon",
    "geoint",
    "network_topology_map",
    "employee_profiling",
    "wayback_recon",
    "xss_advanced",
    "csrf_exploit",
    "path_traversal",
    "business_logic_flaw",
    "race_condition_web",
    "oauth_pkce_attack",
    "mass_assignment",
    "web_cache_deception",
    "api_versioning_attack",
    "nosql_injection",
    "deserialization_java",
    "open_redirect",
    "host_header_injection",
    "graphql_batching",
    "ai_model_backdoor",
    "llm_context_overflow",
    "ai_supply_chain",
    "adversarial_image",
    "llm_dos",
    "llm_privacy_leak",
    "agentic_ai_escape",
    "llm_system_prompt_leak",
    "s3_bucket_enum",
    "imds_ssrf",
    "lambda_layer_inject",
    "cloud_trail_disable",
    "cross_account_pivot",
    "gke_rbac_exploit",
    "azure_ad_attack",
    "terraform_state_steal",
    "cloud_cost_dos",
    "cloud_logging_blind",
    "ecr_image_poison",
    "cloud_function_escape",
    "modbus_exploit",
    "plc_logic_bomb",
    "lora_attack",
    "lorawan_attack",
    "hmi_exploit",
    "can_fd_attack",
    "ics_historian_attack",
    "rootkit_implant",
    "timestomping",
    "log_wiping",
    "dll_hijacking",
    "fileless_malware",
    "syscall_evasion",
    "amsi_bypass",
    "polymorphic_payload",
    "password_crack",
    "tls_downgrade",
    "totp_bruteforce",
    "ntlm_relay",
    "golden_ticket",
    "hsm_attack",
    "pki_cert_forge",
    "key_derivation_flaw",
    "arp_spoofing",
    "icmp_covert_channel",
    "snmp_attack",
    "ospf_bgp_manipulation",
    "rdp_exploit",
    "dns_tunneling",
    "dhcp_starvation",
    "wifi_attack",
    "npm_typosquatting",
    "build_artifact_tamper",
    "package_signing_bypass",
    "vendored_code_attack",
    "code_review_bypass",
    "update_mechanism_hijack",
    "advanced_persistence",
    "apt_lateral_movement",
    "nation_state_ttps",
    "zero_day_chain",
    "apt_c2_infra",
    "long_haul_exfil",
    "full_breach_sim",
    "watering_hole",
    "supply_chain_apt",
    "destructive_wiper",
    "tpm_firmware_attack",
    "cold_boot_attack",
    "evil_maid_engine",
    "thunderbolt_dma_attack",
    "voltage_glitch_attack",
    "badusb_hid_attack",
    "hardware_wallet_attack",
    "jtag_swd_exploitation",
    "medical_device_exploit",
    "implantable_device_hack",
    "hospital_hl7_attack",
    "agentic_framework_attack",
    "llm_function_call_hijack",
    "multi_agent_subversion",
    "llm_guardrail_bypass",
    "mcp_server_exploit",
    "synthetic_identity_fraud",
    "ai_model_provenance_attack",
    "sdn_controller_exploit",
    "nfv_mano_attack",
    "network_slice_isolation_bypass",
    "harvest_now_decrypt_later",
    "pqc_implementation_attack",
    "lattice_crypto_attack",
    "microsegmentation_bypass",
    "continuous_auth_evasion",
    "sase_security_bypass",
    "webauthn_fido2_bypass",
    "ai_cloud_escalation_chain",
    "social_supply_chain_attack",
    "ot_it_lateral_chain",
    "mobile_backend_chain",
    "data_deanonymization",
    "behavioral_biometric_attack",
    "location_pattern_analysis",
    "differential_privacy_exploit",
    "c2_rotation_engine",
    "detection_gap_exploiter",
    "opsec_intelligence_engine",
    "tactic_chain_synthesizer",
    "ar_vr_attack_engine",
    "edge_computing_exploit",
    "blockchain_bridge_exploit",
    "api_all_vectors_engine",
    "threat_model_automation",
    "attack_graph_traversal",
    "prometheus_hyperion_nexus",
    // ── Next-Gen Arsenal: enterprise core ──
    "sap_erp_attack",
    "mainframe_zos_attack",
    // ── Next-Gen Arsenal: initial access / endpoint ──
    "malvertising_seo_poison",
    "infostealer_emulation",
    "printer_mfp_attack",
    "radius_nac_bypass",
];

/// Default engines enabled for new clients (core continuous scan).
pub const DEFAULT_ORCHESTRATOR_ENGINES: &[&str] = KNOWN_ENGINE_IDS;

/// Full ordered registry of all production engines in proper execution order.
/// Matches frontend/src/lib/enginesRegistry.js (same count as `PRODUCTION_ENGINE_IDS`).
pub const FULL_ENGINE_REGISTRY_ORDER: &[&str] = &[
    // Recon & OSINT (run first to discover attack surface)
    "osint",
    "asm",
    "leak_hunter",
    "discovery_engine",
    "recon",
    // Web / API attacks
    "bola_idor",
    "graphql_attack",
    "jwt_attack",
    "oauth_oidc",
    "http_smuggling",
    "liminal_boundary",
    "prototype_pollution",
    "ssrf_advanced",
    "xxe",
    "ssti",
    "file_upload",
    "websocket_attack",
    "cache_poisoning",
    // AI / LLM
    "llm_path_fuzz",
    "semantic_ai_fuzz",
    "ai_adversarial_redteam",
    "llm_redteam",
    "adversarial_ml",
    "autonomous_pentest",
    "nexus_sovereign_swarm",
    // Cloud / Infra
    "aws_attack",
    "cloud_posture",
    "azure_attack",
    "gcp_attack",
    "k8s_container",
    "iac_misconfig",
    "serverless_attack",
    // OT / ICS / IoT
    "scada_ics",
    "avionics_adsb_attack",
    "maritime_ais_attack",
    "ev_charging_ocpp_attack",
    "smart_grid_dlms_attack",
    "rail_signaling_attack",
    "building_automation_attack",
    "robotics_ros2_attack",
    "ot_sis_triton_attack",
    "iot_firmware",
    "ble_rf",
    // Stealth / Evasion
    "edr_evasion",
    "waf_bypass",
    "timing_sidechannel",
    "antiforensics",
    "stealth_engine",
    // Crypto / Identity
    "pki_tls",
    "pqc_scanner",
    "password_spray",
    "kerberoasting",
    "saml_attack",
    "crypto_engine",
    "email_dns_posture",
    // Network / Protocol
    "bgp_dns_hijacking",
    "ipv6_attack",
    "mtls_grpc",
    "smb_netbios",
    // Supply Chain
    "supply_chain",
    "cicd_pipeline",
    "container_registry",
    "sbom_analyzer",
    "typosquatting_monitor",
    // APT / Top-Tier (run last as they may depend on previous findings)
    "kill_chain",
    "oast_oob",
    "deception_honeypot",
    "digital_twin",
    "zero_day_prediction",
    "threat_emulation",
    "poe_synthesis",
    "satellite_recon",
    "darkweb_intel",
    "financial_osint",
    "blockchain_trace",
    "metadata_harvest",
    "patent_recon",
    "telecom_osint",
    "iot_shodan_scan",
    "job_posting_osint",
    "github_secret_scan",
    "graphql_deep_attack",
    "grpc_reflection_attack",
    "http2_attack",
    "swagger_abuse",
    "soap_injection",
    "odata_injection",
    "css_injection",
    "template_injection_adv",
    "http_parameter_pollution",
    "api_mass_assignment",
    "web_cache_poison_adv",
    "clickjacking_engine",
    "subdomain_takeover",
    "file_inclusion_rfi",
    "deserialization_net",
    "nosql_deep_injection",
    "jwt_advanced_attack",
    "api_rate_limit_bypass",
    "idor_advanced",
    "prompt_injection_chain",
    "model_inversion_attack",
    "ai_supply_chain_attack",
    "rag_poisoning_engine",
    "adversarial_examples",
    "data_poisoning_engine",
    "deepfake_synthesis",
    "llm_dos_attack",
    "gpt_plugin_attack",
    "autonomous_ai_escape",
    "llm_memory_extraction",
    "neural_backdoor_detect",
    "federated_learning_attack",
    "llm_red_team_advanced",
    "model_stealing_engine",
    "prompt_injection_brake",
    "jailbreak_cognitive_engine",
    "rag_poisoning_guard",
    "cloud_metadata_ssrf",
    "s3_bucket_attack",
    "lambda_escape",
    "cloud_iam_escalation",
    "kubernetes_rbac_escape",
    "azure_devops_attack",
    "gcp_privilege_attack",
    "terraform_state_attack",
    "cloudformation_injection",
    "service_mesh_attack",
    "cloud_audit_evasion",
    "ecr_registry_attack",
    "cloud_worm_propagation",
    "serverless_injection",
    "cloud_data_exfil",
    "eks_attack",
    "cloud_network_attack",
    "secrets_manager_attack",
    "cloud_privilege_persistence",
    "modbus_attack",
    "mqtt_attack",
    "coap_attack",
    "opcua_attack",
    "modbus_exploit",
    "plc_logic_bomb",
    "lorawan_attack",
    "voltage_glitch_attack",
    "tpm_firmware_attack",
    "cold_boot_attack",
    "hospital_hl7_attack",
    "plc_logic_attack",
    "hmi_attack",
    "satellite_comm_attack",
    "firmware_emulation_attack",
    "profinet_attack",
    "rfid_nfc_attack",
    "industrial_protocol_fuzz",
    "dll_hijacking_engine",
    "sandbox_evasion",
    "rootkit_surface_probe",
    "memory_forensics_evasion",
    "av_bypass_engine",
    "dns_tunneling_c2",
    "steganography_c2",
    "https_c2_masquerade",
    "icmp_covert",
    "rop_chain_engine",
    "timing_evasion_engine",
    "log_tampering_engine",
    "jit_spray",
    "com_hijacking",
    "network_traffic_masking",
    "anti_debug_evasion",
    "parent_pid_spoof",
    "padding_oracle_attack",
    "hash_extension_attack",
    "ecdsa_nonce_bias",
    "rsa_timing_attack",
    "mfa_bypass_engine",
    "kerberos_attack_suite",
    "pki_hierarchy_attack",
    "session_fixation_adv",
    "password_hash_crack",
    "oauth_advanced_attack",
    "saml_advanced_attack",
    "quantum_key_attack",
    "password_spray_advanced",
    "arp_spoofing_engine",
    "vlan_hopping_attack",
    "dhcp_attack_engine",
    "dns_cache_poisoning",
    "dns_rebinding",
    "can_bus_surface",
    "snmp_exploitation",
    "rdp_attack_engine",
    "ldap_injection_engine",
    "ss7_signaling_probe",
    "wifi_attack_engine",
    "bluetooth_attack_engine",
    "ospf_bgp_hijack",
    "mpls_vpn_attack",
    "lte_5g_attack",
    "ipv6_advanced_attack",
    "network_covert_channel",
    "wpa3_attack_engine",
    "tor_exit_attack",
    "protocol_downgrade",
    "npm_package_attack",
    "pypi_supply_chain",
    "github_actions_attack",
    "docker_image_poison",
    "maven_supply_chain",
    "compiler_backdoor",
    "cdn_poisoning_engine",
    "software_signing_attack",
    "build_system_compromise",
    "update_hijacking",
    "sbom_forgery_engine",
    "third_party_api_attack",
    "iac_supply_chain",
    "apt28_techniques",
    "apt29_techniques",
    "apt41_techniques",
    "lazarus_group_ttps",
    "volt_typhoon_ttps",
    "scattered_spider_ttps",
    "salt_typhoon_ttps",
    "fin7_techniques",
    "conti_ransomware_ttps",
    "lockbit_techniques",
    "cl0p_techniques",
    "blackcat_alphv_ttps",
    "midnight_blizzard_ttps",
    "earth_longzhi_ttps",
    "equation_group_ttps",
    "sandworm_techniques",
    "carbon_spider_ttps",
    "wizard_spider_ttps",
    "unc2452_ttps",
    "unc3944_ttps",
    "quantum_sovereign_nexus",
    "bootkit_uefi",
    "fileless_malware_engine",
    "polymorphic_engine",
    "botnet_c2_engine",
    "keylogger_engine",
    "spyware_stalkerware",
    "worm_propagation",
    "rce_exploit_engine",
    "persistence_mechanism",
    "lateral_movement_engine",
    "data_staging_engine",
    "exploit_kit_engine",
    "trojan_dropper",
    "macro_malware",
    "spear_phishing_engine",
    "vishing_engine",
    "smishing_engine",
    "qr_phishing",
    "deepfake_voice_engine",
    "business_email_compromise",
    "watering_hole_attack",
    "pretexting_engine",
    "insider_threat_engine",
    "brand_impersonation",
    "fake_update_engine",
    "linkedin_phishing",
    "callback_phishing",
    "physical_social_eng",
    "typosquatting_phishing",
    "android_malware_engine",
    "ios_exploit_engine",
    "mobile_mitm",
    "ssl_pinning_bypass",
    "android_intent_attack",
    "ios_url_scheme_attack",
    "mobile_overlay_attack",
    "sim_swap_engine",
    "mobile_banking_trojan",
    "app_store_attack",
    "mdm_bypass_engine",
    "bluetooth_mobile_attack",
    "nfc_relay_attack",
    "mobile_spyware_engine",
    "react_native_attack",
    "dns_exfil_engine",
    "http_covert_exfil",
    "cloud_exfil_engine",
    "encrypted_exfil",
    "acoustic_exfil",
    "em_exfil_engine",
    "optical_exfil",
    "cache_timing_exfil",
    "keyboard_acoustic",
    "screen_capture_exfil",
    "clipboard_hijack",
    "database_exfil",
    "email_exfil",
    "insider_exfil",
    "storage_covert_channel",
    "threat_intel_fusion",
    "attack_surface_quantify",
    "external_exposure_supreme",
    "fair_exposure_fusion",
    "identity_attack_chain",
    "pipeline_to_runtime_risk",
    "risk_superposition_collapse",
    "chronos",
    "liquid_matrix",
    "sovereign_active_defense_fusion",
    "cognitive_starvation",
    "adversarial_threat_emulation",
    "dark_web_monitor",
    "passive_dns_forensics",
    "network_baseline_anomaly",
    "packet_injection_engine",
    "network_tap_advanced",
    "multicast_attack",
    "nat_traversal_attack",
    "graphql_subscription_attack",
    "webrtc_attack",
    "web3_dapp_attack",
    "api_gateway_bypass",
    // ── Production registry tail (auto-synced) ──
    "5g_security",
    "active_directory",
    "active_directory_cs",
    "active_directory_enum",
    "advanced_persistence",
    "adversarial_image",
    "agentic_ai_escape",
    "agentic_framework_attack",
    "ai_bias_exploit",
    "ai_cloud_escalation_chain",
    "ai_model_backdoor",
    "ai_model_provenance_attack",
    "ai_poisoning",
    "ai_supply_chain",
    "ai_watermark_bypass",
    "amsi_bypass",
    "api_all_vectors_engine",
    "api_fuzzing",
    "api_gateway_attack",
    "api_versioning_attack",
    "apt_c2_infra",
    "apt_lateral_movement",
    "ar_vr_attack_engine",
    "arp_spoofing",
    "attack_graph_traversal",
    "automotive_can_bus",
    "azure_ad_attack",
    "bacnet_attack",
    "badusb_hid_attack",
    "behavioral_biometric_attack",
    "bgp_hijacking",
    "biometric_spoofing",
    "blockchain_bridge_exploit",
    "bluetooth_attack",
    "browser_exploitation",
    "browser_extension_attack",
    "build_artifact_tamper",
    "business_logic_flaw",
    "c2_emulation",
    "c2_rotation_engine",
    "can_fd_attack",
    "cert_transparency",
    "ci_cd_poisoning",
    "clickjacking",
    "cloud_cost_dos",
    "cloud_function_escape",
    "cloud_identity_attack",
    "cloud_lateral",
    "cloud_logging_blind",
    "cloud_ransomware",
    "cloud_storage_audit",
    "cloud_trail_disable",
    "cloud_waf_bypass",
    "code_review_bypass",
    "compliance_gap_scan",
    "container_escape",
    "container_k8s_escape",
    "continuous_auth_evasion",
    "cors_exploit",
    "cors_misconfiguration",
    "credential_stuffing",
    "cross_account_pivot",
    "csrf_exploit",
    "data_deanonymization",
    "data_exfiltration",
    "data_pipeline_attack",
    "deception_evasion",
    "deepfake_genai",
    "deepweb_intel",
    "dependency_confusion",
    "deserialization_java",
    "destructive_wiper",
    "detection_gap_exploiter",
    "devsecops_scan",
    "devsecops_secrets",
    "dhcp_starvation",
    "differential_privacy_exploit",
    "dll_hijacking",
    "dnp3_attack",
    "dns_enum",
    "dns_tunneling",
    "ecr_image_poison",
    "edge_computing_exploit",
    "email_harvest",
    "email_spoofing",
    "employee_profiling",
    "evil_maid_engine",
    "exfil_ai_inference",
    "fileless_malware",
    "firmware_emulation",
    "firmware_exploit",
    "full_breach_sim",
    "geoint",
    "github_recon",
    "gitops_attack",
    "gke_rbac_exploit",
    "golden_ticket",
    "graphene_os_bypass",
    "graphql_batching",
    "graphql_injection",
    "hardware_implant",
    "hardware_wallet_attack",
    "harvest_now_decrypt_later",
    "heap_exploitation",
    "hmi_exploit",
    "host_header_injection",
    "hsm_attack",
    "http_feedback_fuzz",
    "icmp_covert_channel",
    "ics_historian_attack",
    "iec61850_attack",
    "imds_ssrf",
    "implantable_device_hack",
    "infostealer_emulation",
    "process_inventory",
    "usb_enumeration",
    "insider_threat",
    "ipsec_vpn_audit",
    "js_prototype_pollution",
    "jtag_swd_exploitation",
    "jwt_attacks",
    "kernel_exploit",
    "key_derivation_flaw",
    "lambda_layer_inject",
    "lateral_movement",
    "lattice_crypto_attack",
    "ldap_injection",
    "living_off_land",
    "llm_agent_hijack",
    "llm_context_overflow",
    "llm_dos",
    "llm_function_call_hijack",
    "llm_guardrail_bypass",
    "llm_jailbreak",
    "llm_privacy_leak",
    "llm_system_prompt_leak",
    "location_pattern_analysis",
    "log4shell_scan",
    "log_wiping",
    "long_haul_exfil",
    "lora_attack",
    "mainframe_zos_attack",
    "malvertising_seo_poison",
    "malware_persistence",
    "mass_assignment",
    "mcp_server_exploit",
    "medical_device_exploit",
    "memory_corruption",
    "microsecond_timing",
    "microsegmentation_bypass",
    "mobile_attack",
    "mobile_backend_chain",
    "mobile_pentest",
    "multi_agent_subversion",
    "multi_cloud_pivot",
    "multimodal_ai_attack",
    "nation_state_ttps",
    "network_slice_isolation_bypass",
    "network_tap_implant",
    "network_topology_map",
    "nfv_mano_attack",
    "nosql_injection",
    "npm_typosquatting",
    "ntlm_relay",
    "ntp_amplification",
    "oauth_abuse",
    "oauth_pkce_attack",
    "obfuscated_c2",
    "ollama_fuzz",
    "open_redirect",
    "open_source_backdoor",
    "opsec_intelligence_engine",
    "ospf_bgp_manipulation",
    "ot_it_lateral_chain",
    "package_signing_bypass",
    "password_crack",
    "path_traversal",
    "physical_security",
    "pki_cert_forge",
    "polymorphic_payload",
    "post_exploitation",
    "pqc_implementation_attack",
    "printer_mfp_attack",
    "process_hollowing",
    "process_injection",
    "prometheus_hyperion_nexus",
    "quantum_attack",
    "race_condition_web",
    "radius_nac_bypass",
    "rag_poisoning",
    "ransomware_emulation",
    "ransomware_sim",
    "rce_chain",
    "rce_deserialization",
    "rdp_exploit",
    "rootkit_implant",
    "s3_bucket_enum",
    "sap_erp_attack",
    "sase_security_bypass",
    "satellite_attack",
    "sdn_controller_exploit",
    "serverless_cold_start",
    "shodan_mass_scan",
    "side_channel",
    "siem_evasion",
    "smart_contract_audit",
    "smb_relay",
    "snmp_attack",
    "social_media_recon",
    "social_supply_chain_attack",
    "spear_phishing",
    "sqli_advanced",
    "ssrf_chain",
    "supply_chain_apt",
    "synthetic_identity_fraud",
    "syscall_evasion",
    "tactic_chain_synthesizer",
    "telco_ss7_attack",
    "terraform_state_steal",
    "threat_hunting_apt",
    "threat_model_automation",
    "thunderbolt_dma_attack",
    "timestomping",
    "tls_downgrade",
    "totp_bruteforce",
    "update_mechanism_hijack",
    "vendored_code_attack",
    "vlan_bypass",
    "voip_sip_attack",
    "vuln_chaining",
    "waf_ids_bypass",
    "wasm_reverse",
    "watering_hole",
    "wayback_recon",
    "web_cache_deception",
    "web_cache_poison",
    "webauthn_fido2_bypass",
    "wifi_attack",
    "wireless_attack",
    "xss_advanced",
    "xxe_injection",
    "zero_click_exploit",
    "zero_day_chain",
    "zero_trust_bypass",
    "zigbee_attack",
];

/// Map catalog-only registry IDs to a production engine implementation.
#[must_use]
pub fn resolve_engine_id(id: &str) -> &str {
    match id.trim() {
        // Live-only renames (legacy *simulation* production IDs → live probe names).
        "rootkit_simulation" => "rootkit_surface_probe",
        "ss7_attack_simulation" => "ss7_signaling_probe",
        "adversarial_simulation" => "adversarial_threat_emulation",
        // dedicated probe: graphql_deep_attack
        // dedicated probe: jwt_advanced_attack
        // dedicated probe: grpc_reflection_attack
        // dedicated probe: idor_advanced
        // dedicated probe: oauth_advanced_attack
        // dedicated probe: saml_advanced_attack
        // dedicated probe: ipv6_advanced_attack
        // dedicated probe: cloud_metadata_ssrf
        "cloud_iam_escalation" | "secrets_manager_attack" => "aws_attack",
        // dedicated probe: gcp_privilege_attack
        // dedicated probes: kubernetes_rbac_escape, eks_attack
        // dedicated probe: azure_devops_attack
        // Legacy APT / campaign aliases.
        "poe_synthesis" => "poe_synthesis",
        "rce_chain" | "vuln_chaining" => "kill_chain",
        "c2_emulation" | "apt_c2_infra" | "obfuscated_c2" | "c2_rotation_engine" => {
            "botnet_c2_engine"
        }
        "ransomware_sim" | "destructive_wiper" => "conti_ransomware_ttps",
        "active_directory" => "kerberos_attack_suite",
        "memory_corruption" => "heap_exploitation",
        "browser_exploitation" => "browser_extension_attack",
        "log4shell_scan" | "kernel_exploit" => "rce_exploit_engine",
        "post_exploitation" | "full_breach_sim" => "threat_emulation",
        "threat_hunting_apt" => "threat_intel_fusion",
        "advanced_persistence" => "bootkit_uefi",
        "apt_lateral_movement" | "ot_it_lateral_chain" => "lateral_movement_engine",
        "nation_state_ttps" | "prometheus_hyperion_nexus" => "quantum_sovereign_nexus",
        "zero_day_chain" => "zero_day_prediction",
        "long_haul_exfil" => "storage_covert_channel",
        "watering_hole" => "watering_hole_attack",
        "supply_chain_apt" | "social_supply_chain_attack" => "supply_chain",
        "mobile_backend_chain" | "ai_cloud_escalation_chain" => "kill_chain",
        // Legacy recon / OSINT aliases.
        "mobile_attack" | "mobile_pentest" => "mobile_mitm",
        "active_directory_enum" => "kerberos_attack_suite",
        "email_spoofing" => "business_email_compromise",
        "deepweb_intel" => "dark_web_monitor",
        "compliance_gap_scan"
        | "network_topology_map"
        | "threat_model_automation"
        | "attack_graph_traversal" => "attack_surface_quantify",
        "social_media_recon"
        | "github_recon"
        | "email_harvest"
        | "geoint"
        | "employee_profiling"
        | "data_deanonymization"
        | "location_pattern_analysis" => "osint",
        "wayback_recon" | "cert_transparency" => "recon",
        "dns_enum" => "passive_dns_forensics",
        "shodan_mass_scan" => "asm",
        "differential_privacy_exploit" => "model_inversion_attack",
        // Legacy web / appsec aliases.
        "sqli_advanced" | "api_fuzzing" | "xss_advanced" | "csrf_exploit"
        | "race_condition_web" | "nosql_injection" | "open_redirect" => "http_feedback_fuzz",
        "graphql_injection" | "graphql_batching" => "graphql_attack",
        "container_escape" | "container_k8s_escape" | "gke_rbac_exploit" => "k8s_container",
        "web_cache_poison" | "web_cache_deception" => "cache_poisoning",
        "xxe_injection" => "xxe",
        "ldap_injection" => "ldap_injection_engine",
        "ssrf_chain" | "imds_ssrf" => "ssrf_advanced",
        "jwt_attacks" => "jwt_attack",
        "rce_deserialization" | "deserialization_java" => "deserialization_net",
        "cors_exploit" => "cors_misconfiguration",
        "js_prototype_pollution" => "prototype_pollution",
        "oauth_pkce_attack" | "oauth_abuse" => "oauth_oidc",
        "clickjacking" => "clickjacking_engine",
        "smart_contract_audit" | "blockchain_bridge_exploit" => "web3_dapp_attack",
        "path_traversal" => "file_inclusion_rfi",
        "business_logic_flaw" => "bola_idor",
        "mass_assignment" => "api_mass_assignment",
        "api_versioning_attack" | "api_gateway_attack" | "api_all_vectors_engine" => {
            "api_gateway_bypass"
        }
        "host_header_injection" => "http_smuggling",
        "ar_vr_attack_engine" => "browser_extension_attack",
        // Legacy AI / LLM aliases.
        "deepfake_genai" | "synthetic_identity_fraud" => "deepfake_synthesis",
        "ai_poisoning" => "data_poisoning_engine",
        "rag_poisoning" => "rag_poisoning_engine",
        "exfil_ai_inference" => "model_inversion_attack",
        "ai_model_backdoor" => "neural_backdoor_detect",
        "llm_context_overflow" | "llm_dos" => "llm_dos_attack",
        "ai_supply_chain" | "ai_model_provenance_attack" => "ai_supply_chain_attack",
        "adversarial_image" => "adversarial_examples",
        "llm_privacy_leak" => "llm_memory_extraction",
        "agentic_ai_escape" => "autonomous_ai_escape",
        "agentic_framework_attack"
        | "llm_function_call_hijack"
        | "multi_agent_subversion"
        | "mcp_server_exploit" => "llm_agent_hijack",
        "llm_system_prompt_leak" => "prompt_injection_chain",
        "llm_guardrail_bypass" => "llm_jailbreak",
        // Legacy cloud aliases.
        "cloud_ransomware" => "cloud_worm_propagation",
        "cloud_lateral" | "cross_account_pivot" => "multi_cloud_pivot",
        "serverless_cold_start" => "serverless_attack",
        "cloud_identity_attack" => "cloud_privilege_persistence",
        "cloud_storage_audit" | "cloud_trail_disable" | "cloud_logging_blind" => {
            "cloud_audit_evasion"
        }
        "cloud_waf_bypass" => "waf_bypass",
        "s3_bucket_enum" => "aws_attack",
        "lambda_layer_inject" | "cloud_function_escape" | "edge_computing_exploit" => {
            "lambda_escape"
        }
        "azure_ad_attack" => "azure_attack",
        "terraform_state_steal" => "terraform_state_attack",
        "cloud_cost_dos"
        | "sdn_controller_exploit"
        | "nfv_mano_attack"
        | "sase_security_bypass" => "cloud_network_attack",
        "ecr_image_poison" => "ecr_registry_attack",
        // Legacy OT / embedded aliases.
        "firmware_exploit"
        | "firmware_emulation"
        | "medical_device_exploit"
        | "implantable_device_hack"
        | "jtag_swd_exploitation" => "iot_firmware",
        "satellite_attack" => "satellite_comm_attack",
        "automotive_can_bus" | "can_fd_attack" => "can_bus_surface",
        "hardware_implant" => "iot_firmware",
        "hmi_exploit" | "ics_historian_attack" => "scada_ics",
        "lora_attack" => "lorawan_attack",
        // Legacy stealth / evasion aliases.
        "data_exfiltration" => "http_covert_exfil",
        "physical_security" | "evil_maid_engine" | "badusb_hid_attack" => "physical_social_eng",
        "malware_persistence" => "persistence_mechanism",
        "process_injection" => "process_hollowing",
        "side_channel" => "timing_sidechannel",
        "waf_ids_bypass" => "waf_bypass",
        "siem_evasion" | "wasm_reverse" | "timestomping" | "log_wiping" => "antiforensics",
        "deception_evasion"
        | "syscall_evasion"
        | "amsi_bypass"
        | "detection_gap_exploiter"
        | "opsec_intelligence_engine" => "edr_evasion",
        "graphene_os_bypass" => "mdm_bypass_engine",
        "rootkit_implant" => "bootkit_uefi",
        "dll_hijacking" => "edr_evasion",
        "fileless_malware" => "fileless_malware_engine",
        "polymorphic_payload" => "polymorphic_engine",
        "thunderbolt_dma_attack" => "physical_social_eng",
        "continuous_auth_evasion" | "behavioral_biometric_attack" => "mfa_bypass_engine",
        "microsegmentation_bypass" => "zero_trust_bypass",
        // Legacy crypto / identity aliases.
        "biometric_spoofing" | "totp_bruteforce" | "webauthn_fido2_bypass" => "mfa_bypass_engine",
        "quantum_attack"
        | "harvest_now_decrypt_later"
        | "pqc_implementation_attack"
        | "lattice_crypto_attack" => "quantum_key_attack",
        "active_directory_cs" | "pki_cert_forge" | "hsm_attack" | "hardware_wallet_attack" => {
            "pki_hierarchy_attack"
        }
        "password_crack" => "password_hash_crack",
        "tls_downgrade" => "pki_tls",
        "ntlm_relay" => "smb_netbios",
        "golden_ticket" => "kerberos_attack_suite",
        "key_derivation_flaw" => "crypto_engine",
        // Legacy network aliases.
        "lateral_movement" => "lateral_movement_engine",
        "wireless_attack" | "wifi_attack" => "wifi_attack_engine",
        // dns_rebinding uses dedicated Host/TTL probe — not dns_cache_poisoning.
        "spear_phishing" => "spear_phishing_engine",
        "vlan_bypass" => "vlan_hopping_attack",
        "insider_threat" => "insider_threat_engine",
        "smb_relay" => "smb_netbios",
        "bgp_hijacking" => "bgp_dns_hijacking",
        "ipsec_vpn_audit" => "mpls_vpn_attack",
        "5g_security" | "network_slice_isolation_bypass" => "lte_5g_attack",
        "bluetooth_attack" => "bluetooth_attack_engine",
        "telco_ss7_attack" => "ss7_signaling_probe",
        "network_tap_implant" => "network_tap_advanced",
        "arp_spoofing" => "arp_spoofing_engine",
        "icmp_covert_channel" => "network_covert_channel",
        "snmp_attack" => "snmp_exploitation",
        "ospf_bgp_manipulation" => "ospf_bgp_hijack",
        "rdp_exploit" => "rdp_attack_engine",
        "dns_tunneling" => "dns_exfil_engine",
        "dhcp_starvation" => "dhcp_attack_engine",
        // Legacy supply-chain and orchestration aliases.
        "devsecops_scan" | "data_pipeline_attack" => "cicd_pipeline",
        "devsecops_secrets" => "leak_hunter",
        "ci_cd_poisoning" | "build_artifact_tamper" | "code_review_bypass" => {
            "build_system_compromise"
        }
        "gitops_attack" => "iac_supply_chain",
        "npm_typosquatting" => "typosquatting_monitor",
        "package_signing_bypass" => "software_signing_attack",
        "vendored_code_attack" => "open_source_backdoor",
        "update_mechanism_hijack" => "update_hijacking",
        "zero_click_exploit" => "zero_day_prediction",
        "tactic_chain_synthesizer" => "kill_chain",
        // OT engines: dedicated probes (modbus_attack, mqtt_attack, …)
        // Stealth engines: dedicated probes
        // Supply chain engines: dedicated probes
        // dedicated probe: web_cache_poison_adv
        // dedicated probe: nosql_deep_injection
        // Top-tier catalog aliases mapped to stable production engines.
        // Recon engines: dedicated probes (satellite_recon, darkweb_intel, …)
        // dedicated probe: http2_attack
        "protocol_schism_oracle" | "cache_vary_oracle" => "liminal_boundary",
        "quantum_risk_collapse" | "belief_fusion_engine" | "superposition_risk" => {
            "risk_superposition_collapse"
        }
        "chronos_engine" | "temporal_rollback" | "zero_day_chronos" => "chronos",
        "liquid-matrix" | "mtd_routing" | "moving_target_defense" => "liquid_matrix",
        "offensive_ai_poisoning" | "ai_starvation" | "cognitive_starvation_engine" => {
            "cognitive_starvation"
        }
        "sovereign-defense-fusion" | "active_defense_fusion" | "sovereign_defense_fusion" => {
            "sovereign_active_defense_fusion"
        }
        "fair-exposure-fusion" | "business_risk_exposure" | "fair_blast_radius" => {
            "fair_exposure_fusion"
        }
        other => other,
    }
}

/// True when `id` is a marketing/catalog alias that maps to a different canonical probe.
#[must_use]
pub fn is_engine_alias(id: &str) -> bool {
    let s = id.trim();
    resolve_engine_id(s) != s
}

/// Engine id used for dispatch: alias IDs keep their identity (dedicated alias runner);
/// dedicated production IDs run directly; unknown IDs resolve via legacy alias table.
#[must_use]
pub fn dispatch_engine_id(id: &str) -> &str {
    let s = id.trim();
    if is_engine_alias(s) {
        return s;
    }
    if PRODUCTION_ENGINE_IDS.contains(&s) {
        return s;
    }
    resolve_engine_id(s)
}

#[must_use]
pub fn is_production_engine_id(id: &str) -> bool {
    let s = id.trim();
    if PRODUCTION_ENGINE_IDS.contains(&s) {
        return true;
    }
    let canonical = resolve_engine_id(s);
    PRODUCTION_ENGINE_IDS.contains(&canonical)
}

#[must_use]
pub fn production_engine_ids() -> &'static [&'static str] {
    PRODUCTION_ENGINE_IDS
}

#[must_use]
pub fn is_known_engine_id(s: &str) -> bool {
    is_production_engine_id(s) || FULL_ENGINE_REGISTRY_ORDER.iter().any(|&k| k == s.trim())
}

#[must_use]
pub fn default_enabled_engine_ids() -> Vec<String> {
    KNOWN_ENGINE_IDS.iter().map(|s| (*s).to_string()).collect()
}

/// Order a list of engine IDs by their position in the registry.
/// Engines not in the registry are placed at the end.
#[must_use]
pub fn order_engines_by_registry(engines: &[String]) -> Vec<String> {
    let mut ordered: Vec<(usize, String)> = engines
        .iter()
        .map(|e| {
            let pos = FULL_ENGINE_REGISTRY_ORDER
                .iter()
                .position(|&r| r == e.as_str())
                .unwrap_or(usize::MAX);
            (pos, e.clone())
        })
        .collect();
    ordered.sort_by_key(|(pos, _)| *pos);
    ordered.into_iter().map(|(_, e)| e).collect()
}
