#!/usr/bin/env node
// deploy/maintenance/build.mjs — the canonical maintenance-page generator.
//
//   node deploy/maintenance/build.mjs           write every generated file
//   node deploy/maintenance/build.mjs --check   exit 1 if any generated file drifted from the sources
//
// Sources (edit these):  src/strings.mjs (ALL copy, contact address, year), src/template.mjs
// (markup + CSS), src/maintenance.js (behaviour), src/logo.svg (mark), src/k8s-default.conf.
// Fonts are inlined from deploy/public/fonts (Orbitron 700 latin, Heebo 500 hebrew).
//
// Output is deterministic: no timestamps, stable key order, LF newlines, one trailing
// newline. Node >= 22, zero dependencies.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { page, markInner } from './src/template.mjs';
import { EMAIL, API, STATUS_EXAMPLE } from './src/strings.mjs';

const major = Number(process.versions.node.split('.')[0]);
if (!(major >= 22)) {
  console.error(`build.mjs: node >= 22 required (running ${process.versions.node})`);
  process.exit(2);
}

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '..', '..');
const src = (f) => resolve(here, 'src', f);
const text = (p) => readFileSync(p, 'utf8');
const lf = (s) => {
  const t = String(s).replace(/\r\n?/g, '\n');
  return t.endsWith('\n') ? t : t + '\n';
};

// ---- inputs ---------------------------------------------------------------------
const fonts = {
  orbitron: readFileSync(resolve(repo, 'deploy/public/fonts/orbitron-700-latin.woff2')).toString('base64'),
  heebo: readFileSync(resolve(repo, 'deploy/public/fonts/heebo-500-hebrew.woff2')).toString('base64'),
};
const mark = markInner(text(src('logo.svg')));
const script = lf(text(src('maintenance.js')));
const nginxConf = lf(text(src('k8s-default.conf')));

// ---- render ---------------------------------------------------------------------
const HTML_EN = lf(page({ locale: 'en', fonts, mark }));
const HTML_HE = lf(page({ locale: 'he', fonts, mark }));
// Command Center variant: English only, served by the gateway fallback AND by the
// service worker for /command-center/* navigations, so every asset URL is absolute.
const HTML_CC = lf(page({ locale: 'en', variant: 'command-center', assetBase: '/maintenance/', fonts, mark }));

const API_JSON = JSON.stringify({
  status: 'maintenance',
  code: 503,
  message: API.message,
  retry_after_seconds: 30,
  contact: EMAIL,
  status_page: '/status',
}, null, 2) + '\n';

const STATUS_EXAMPLE_JSON = JSON.stringify({
  mode: 'planned',
  reason: STATUS_EXAMPLE.reason,
  until: STATUS_EXAMPLE.until,
}, null, 2) + '\n';

const GENERATED = 'generated by deploy/maintenance/build.mjs — do not edit';

const lit = (s) => JSON.stringify(s);
const WORKER_ASSETS = `// ${GENERATED}
// Maintenance-page assets for the Cloudflare Worker (deploy/cloudflare/maintenance-worker).
// Sources: deploy/maintenance/src/*. Rebuild with \`node deploy/maintenance/build.mjs\`.
export const HTML_EN = ${lit(HTML_EN)};
export const HTML_HE = ${lit(HTML_HE)};
export const MAINTENANCE_JS = ${lit(script)};
export const API_JSON = ${lit(API_JSON)};
`;

// YAML literal block scalar (|): content lines indented by 4, clip chomping keeps
// exactly the single trailing newline every artifact ends with.
function block(s) {
  const body = lf(s).slice(0, -1);
  const lines = body.split('\n');
  for (const l of lines) {
    if (l.startsWith('\t')) { throw new Error('ConfigMap: a content line starts with a tab (invalid YAML indentation)'); }
    if (/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(l)) { throw new Error('ConfigMap: control character in content'); }
  }
  return '|\n' + lines.map((l) => (l === '' ? '' : '    ' + l)).join('\n') + '\n';
}
const CONFIGMAP = `# ${GENERATED}
# Maintenance page for the ingress-nginx default backend: mount every key at
# /usr/share/nginx/html (default.conf -> /etc/nginx/conf.d/default.conf) in an
# nginxinc/nginx-unprivileged pod. See deploy/maintenance/README.md.
apiVersion: v1
kind: ConfigMap
metadata:
  name: weissman-maintenance-page
  namespace: weissman
  labels:
    app.kubernetes.io/name: weissman-maintenance-page
    app.kubernetes.io/part-of: weissman
data:
  index.html: ${block(HTML_EN)}  he.html: ${block(HTML_HE)}  maintenance.js: ${block(script)}  api.json: ${block(API_JSON)}  default.conf: ${block(nginxConf)}`;

// ---- outputs (stable order) ----------------------------------------------------
const OUTPUTS = [
  [resolve(here, 'dist/index.html'), HTML_EN],
  [resolve(here, 'dist/he/index.html'), HTML_HE],
  [resolve(here, 'dist/maintenance.js'), script],
  [resolve(here, 'dist/api.json'), API_JSON],
  [resolve(here, 'dist/status.example.json'), STATUS_EXAMPLE_JSON],
  [resolve(repo, 'frontend/public/offline.html'), HTML_CC],
  [resolve(repo, 'deploy/cloudflare/maintenance-worker/assets.generated.mjs'), WORKER_ASSETS],
  [resolve(repo, 'deploy/k8s/maintenance-page-configmap.yaml'), CONFIGMAP],
];

// ---- self-checks the outputs must always pass -----------------------------------
for (const [file, content] of OUTPUTS) {
  const name = relative(repo, file);
  if (/\r/.test(content)) { throw new Error(`${name}: CR found`); }
  if (!content.endsWith('\n') || content.endsWith('\n\n')) { throw new Error(`${name}: must end with exactly one newline`); }
  const mails = content.match(/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/g) || [];
  for (const m of mails) { if (m !== EMAIL) { throw new Error(`${name}: unexpected address ${m}`); } }
  if (name.endsWith('.html')) {
    const scripts = content.match(/<script\b/gi) || [];
    if (scripts.length !== 1 || !/<script defer src="\/maintenance\/maintenance\.js"><\/script>/.test(content)) {
      throw new Error(`${name}: expected exactly one <script defer src="/maintenance/maintenance.js">`);
    }
    if (/\son[a-z]+=/i.test(content)) { throw new Error(`${name}: inline event handler`); }
  }
}

const check = process.argv.includes('--check');
let drift = 0;
for (const [file, content] of OUTPUTS) {
  const name = relative(repo, file);
  const bytes = Buffer.byteLength(content, 'utf8');
  if (check) {
    if (!existsSync(file)) { drift++; console.log(`MISSING  ${name}`); continue; }
    const current = readFileSync(file, 'utf8');
    if (current === content) { console.log(`ok       ${name} (${bytes} B)`); }
    else { drift++; console.log(`DRIFT    ${name} (${Buffer.byteLength(current, 'utf8')} B on disk, ${bytes} B expected)`); }
  } else {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, content, 'utf8');
    console.log(`wrote    ${name} (${bytes} B)`);
  }
}
if (check) {
  if (drift) { console.log(`build.mjs --check: ${drift} file(s) drifted — run \`node deploy/maintenance/build.mjs\``); process.exit(1); }
  console.log('build.mjs --check: all generated files are up to date');
}
