/**
 * Route → dynamic import map for predictive prefetch.
 * Chunk names align with Vite manualChunks for cache-stable micro-bundles.
 *
 * Prefetch helpers live in routePrefetchMap.js (imported here) to avoid circular
 * init with app-context providers and lazy page chunks.
 */
import React from 'react'

export { normalizeRoutePath, matchRouteChunk } from './routePrefetchMap'

// ── Lazy route components (used by TacticalApp) ─────────────────────────────
export const Cockpit = React.lazy(() => import(/* webpackChunkName: "cockpit-shell" */ '../Cockpit'))
export const Login = React.lazy(() => import(/* webpackChunkName: "page-login" */ '../components/cockpit/Login'))
export const App = React.lazy(() => import(/* webpackChunkName: "page-intel-map" */ '../App'))
export const SystemCore = React.lazy(() => import('../components/SystemCore'))
export const ReportView = React.lazy(() => import('../components/ReportView'))
export const AttackSurfaceGraph = React.lazy(() => import('../components/AttackSurfaceGraph'))
export const SemanticLogicEngine = React.lazy(() => import('../components/SemanticLogicEngine'))
export const QuantumTimingProfiler = React.lazy(() => import('../components/QuantumTimingProfiler'))
export const AIRedteamArena = React.lazy(() => import('../components/AIRedteamArena'))
export const ZeroDayRadar = React.lazy(() => import('../components/ZeroDayRadar'))
export const CICDThreatMatrix = React.lazy(() => import('../components/CICDThreatMatrix'))
export const MemoryForensicsLab = React.lazy(() => import('../components/MemoryForensicsLab'))
export const AttackChainView = React.lazy(() => import('../components/cockpit/AttackChainView'))
export const EngineMatrix = React.lazy(() => import('../pages/EngineMatrix'))
export const EngineDetail = React.lazy(() => import('../pages/EngineDetail'))
export const OsintEngineProfile = React.lazy(() => import('../pages/OsintEngineProfile'))
export const TopTierEngineHub = React.lazy(() => import('../pages/TopTierEngineHub'))
export const TopTierEngineProfile = React.lazy(() => import('../pages/TopTierEngineProfile'))
export const StrategicEngineProgram = React.lazy(() => import('../pages/StrategicEngineProgram'))
export const BusinessEngineProfile = React.lazy(() => import('../pages/BusinessEngineProfile'))
export const ThreatEmulation = React.lazy(() => import('../pages/ThreatEmulation'))
export const SupplyChainHub = React.lazy(() => import('../pages/SupplyChainHub'))
export const NetworkIntelligence = React.lazy(() => import('../pages/NetworkIntelligence'))
export const CloudControlTower = React.lazy(() => import('../pages/CloudControlTower'))
export const CloudPostureCommandCenter = React.lazy(() => import('../pages/CloudPostureCommandCenter'))
export const IacSecurityCenter = React.lazy(() => import('../pages/IacSecurityCenter'))
export const AttackSurfaceManagement = React.lazy(() => import('../pages/AttackSurfaceManagement'))
export const DnsDomainPosture = React.lazy(() => import('../pages/DnsDomainPosture'))
export const WebCachePosture = React.lazy(() => import('../pages/WebCachePosture'))
export const TransportSecurityCommandCenter = React.lazy(() => import('../pages/TransportSecurityCommandCenter'))
export const HttpSmugglingPosture = React.lazy(() => import('../pages/HttpSmugglingPosture'))
export const PkiTlsCommandCenter = React.lazy(() => import('../pages/PkiTlsCommandCenter'))
export const EmailDnsPosture = React.lazy(() => import('../pages/EmailDnsPosture'))
export const PqcRadar = React.lazy(() => import('../pages/PqcRadar'))
export const EdDetectionSurface = React.lazy(() => import('../pages/EdDetectionSurface'))
export const WafBypassLab = React.lazy(() => import('../pages/WafBypassLab'))
export const WebSocketSecurityCommandCenter = React.lazy(() => import('../pages/WebSocketSecurityCommandCenter'))
export const JwtAttackLab = React.lazy(() => import('../pages/JwtAttackLab'))
export const FileUploadSecurityLab = React.lazy(() => import('../pages/FileUploadSecurityLab'))
export const OastDashboard = React.lazy(() => import('../pages/OastDashboard'))
export const OobVerification = React.lazy(() => import('../pages/OobVerification'))
export const TemplateEngineWorkbench = React.lazy(() => import('../pages/TemplateEngineWorkbench'))
export const AstFuzzingStudio = React.lazy(() => import('../pages/AstFuzzingStudio'))
export const FeedbackLoopVerification = React.lazy(() => import('../pages/FeedbackLoopVerification'))
export const CouncilHitlQueue = React.lazy(() => import('../pages/CouncilHitlQueue'))
export const SelfImprovementConsole = React.lazy(() => import('../pages/SelfImprovementConsole'))
export const RoeApprovals = React.lazy(() => import('../pages/RoeApprovals'))
export const SsoDashboard = React.lazy(() => import('../pages/SsoDashboard'))
export const NexusSovereignSwarm = React.lazy(() => import('../pages/NexusSovereignSwarm'))
export const RiskSuperpositionCollapse = React.lazy(() => import('../pages/RiskSuperpositionCollapse'))
export const SovereignDefenseMatrix = React.lazy(() => import('../pages/SovereignDefenseMatrix'))
export const GraphqlSecurityCommandCenter = React.lazy(() => import('../pages/GraphqlSecurityCommandCenter'))
export const CicdPipelineSecurityCommandCenter = React.lazy(() => import('../pages/CicdPipelineSecurityCommandCenter'))
export const ServerlessSecurityCommandCenter = React.lazy(() => import('../pages/ServerlessSecurityCommandCenter'))
export const DigitalTwinSimulator = React.lazy(() => import('../pages/DigitalTwinSimulator'))
export const FindingsCommandCenter = React.lazy(() => import('../pages/FindingsCommandCenter'))
export const AdminManagement = React.lazy(() => import('../pages/AdminManagement'))
export const DomainDiscovery = React.lazy(() => import('../pages/DomainDiscovery'))
export const ThreatIntelHub = React.lazy(() => import('../pages/ThreatIntelHub'))
export const IncidentResponseCenter = React.lazy(() => import('../pages/IncidentResponseCenter'))
export const VulnIntelDashboard = React.lazy(() => import('../pages/VulnIntelDashboard.jsx'))
export const FinancialRisk = React.lazy(() => import('../pages/FinancialRisk.jsx'))
export const AttackPaths = React.lazy(() => import('../pages/AttackPaths.jsx'))
export const AttackCoverage = React.lazy(() => import('../pages/AttackCoverage.jsx'))
export const SecurityPosture = React.lazy(() => import('../pages/SecurityPosture.jsx'))
export const IocFeed = React.lazy(() => import('../pages/IocFeed.jsx'))
export const UebaAnomalies = React.lazy(() => import('../pages/UebaAnomalies.jsx'))
export const FindingSuppressions = React.lazy(() => import('../pages/FindingSuppressions.jsx'))
export const CryptoPosture = React.lazy(() => import('../pages/CryptoPosture.jsx'))
export const LiveFeed = React.lazy(() => import('../pages/LiveFeed.jsx'))
export const ReportHistory = React.lazy(() => import('../pages/ReportHistory.jsx'))
export const ExecutiveOverview = React.lazy(() => import('../pages/ExecutiveOverview.jsx'))
export const AgentManagement = React.lazy(() => import('../pages/AgentManagement'))
export const DarkWebMonitor = React.lazy(() => import('../pages/DarkWebMonitor'))
export const TargetIntelligence = React.lazy(() => import('../pages/TargetIntelligence'))
export const StealthOperations = React.lazy(() => import('../pages/StealthOperations'))
export const ThreatHuntingWorkbench = React.lazy(() => import('../pages/ThreatHuntingWorkbench'))
export const ThreatAnalysisCenter = React.lazy(() => import('../pages/ThreatAnalysisCenter'))
export const EngineClientCatalog = React.lazy(() => import('../pages/EngineClientCatalog'))
export const RateLimitAnalytics = React.lazy(() => import('../pages/RateLimitAnalytics'))
export const MobileSecurity = React.lazy(() => import('../pages/MobileSecurity'))
export const OtIcsSecurity = React.lazy(() => import('../pages/OtIcsSecurity'))
export const NetworkProtocols = React.lazy(() => import('../pages/NetworkProtocols'))
export const SocialEngineering = React.lazy(() => import('../pages/SocialEngineering'))
export const RemediationHub = React.lazy(() => import('../pages/RemediationHub'))
export const RemediationAnalytics = React.lazy(() => import(/* webpackChunkName: "page-remediation-analytics" */ '../pages/RemediationAnalytics'))
export const EngineManagementConsole = React.lazy(() => import('../pages/EngineManagementConsole'))
export const EngineReliability = React.lazy(() => import('../pages/EngineReliability'))
export const SystemConfiguration = React.lazy(() => import('../pages/SystemConfiguration'))
export const MetricsDashboard = React.lazy(() => import('../pages/MetricsDashboard'))
export const CeoVault = React.lazy(() => import('../pages/CeoVault'))
export const CeoCommandCenter = React.lazy(() => import('../pages/CeoCommandCenter'))
export const SupremeNerveCenter = React.lazy(() => import('../pages/SupremeNerveCenter'))
export const RiskGraphVisualization = React.lazy(() => import('../pages/RiskGraphVisualization'))
export const ComplianceFrameworks = React.lazy(() => import('../pages/ComplianceFrameworks'))
export const SBOMBrowser = React.lazy(() => import('../pages/SBOMBrowser'))
export const IntegrationManager = React.lazy(() => import('../pages/IntegrationManager'))
export const AlertRulesEngine = React.lazy(() => import('../pages/AlertRulesEngine'))
export const ScanScheduler = React.lazy(() => import('../pages/ScanScheduler'))
export const ContainmentRulesBuilder = React.lazy(() => import('../pages/ContainmentRulesBuilder'))
export const BaselineAndDrift = React.lazy(() => import('../pages/BaselineAndDrift'))
export const IdentityContextManager = React.lazy(() => import('../pages/IdentityContextManager'))
export const IdentitySecurityCenter = React.lazy(() => import('../pages/IdentitySecurityCenter'))
export const KerberosSecurityCommandCenter = React.lazy(() => import('../pages/KerberosSecurityCommandCenter'))
export const SmbNetbiosCommandCenter = React.lazy(() => import('../pages/SmbNetbiosCommandCenter'))
export const PasswordSprayCommandCenter = React.lazy(() => import('../pages/PasswordSprayCommandCenter'))
export const SamlSecurityCommandCenter = React.lazy(() => import('../pages/SamlSecurityCommandCenter'))
export const KillChainOrchestrator = React.lazy(() => import('../pages/KillChainOrchestrator'))
export const AIAnalysisEngine = React.lazy(() => import('../pages/AIAnalysisEngine'))
export const ExploitResearchLab = React.lazy(() => import('../pages/ExploitResearchLab'))
export const Clients = React.lazy(() => import('../pages/Clients'))
export const ClientNew = React.lazy(() => import('../pages/ClientNew'))
export const ClientDetail = React.lazy(() => import('../pages/ClientDetail'))
export const ClientIntegrations = React.lazy(() => import('../pages/ClientIntegrations'))
export const ClientEngagements = React.lazy(() => import('../pages/ClientEngagements'))
export const ClientEvidenceVault = React.lazy(() => import('../pages/ClientEvidenceVault'))
export const ClientSaasIdpDiscovery = React.lazy(() => import('../pages/ClientSaasIdpDiscovery'))
export const JobsDashboard = React.lazy(() => import('../pages/JobsDashboard'))
export const StatusPage = React.lazy(() => import('../pages/StatusPage'))
export const AuditLog = React.lazy(() => import('../pages/AuditLog'))
export const PlaybookBuilder = React.lazy(() => import('../pages/PlaybookBuilder'))
export const AskWeissman = React.lazy(() => import('../pages/AskWeissman'))
export const Billing = React.lazy(() => import('../pages/Billing'))
