#!/usr/bin/env node
/**
 * Generates Hebrew engine encyclopedia appendix for WEISSMAN-COMMAND-CENTER-BOOK.md
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const AGENT_REQUIRED = new Set([
  'process_hollowing', 'dll_hijacking_engine', 'process_inventory', 'av_bypass_engine',
  'log_tampering_engine', 'anti_debug_evasion', 'rootkit_simulation', 'memory_forensics_evasion',
  'usb_enumeration', 'dns_tunneling_c2', 'icmp_covert', 'bootkit_uefi', 'persistence_mechanism',
  'polymorphic_engine', 'ransomware_emulation', 'acoustic_exfil', 'em_exfil_engine', 'optical_exfil',
  'keyboard_acoustic', 'screen_capture_exfil', 'clipboard_hijack', 'insider_exfil',
  'storage_covert_channel', 'arp_spoofing_engine', 'vlan_hopping_attack', 'dhcp_attack_engine',
  'wifi_attack_engine', 'bluetooth_attack_engine', 'lte_5g_attack', 'wpa3_attack_engine',
  'packet_injection_engine', 'network_tap_advanced', 'multicast_attack', 'nat_traversal_attack',
  'sim_swap_engine', 'bluetooth_mobile_attack', 'nfc_relay_attack', 'deepfake_voice_engine',
  'pretexting_engine', 'insider_threat_engine', 'physical_social_eng', 'lorawan_attack',
  'lora_attack', 'voltage_glitch_attack', 'tpm_firmware_attack', 'cold_boot_attack',
  'infostealer_emulation',
])

const GROUP_HE = {
  recon: 'מודיעין ו-Recon',
  web: 'Web / API',
  ai: 'AI / LLM',
  cloud: 'ענן ותשתית',
  ot: 'OT / ICS / IoT',
  stealth: 'Stealth / Evasion',
  crypto: 'קריפטו וזהות',
  network: 'רשת ופרוטוקולים',
  supply_chain: 'Supply Chain',
  apt: 'APT / Top-Tier',
  malware: 'Malware ו-Ransomware',
  social: 'הנדסה חברתית',
  mobile: 'מובייל',
  data: 'דליפת מידע',
}

const root = join(process.cwd())
const src = readFileSync(join(root, 'frontend/src/lib/enginesRegistry.js'), 'utf8')
const re =
  /id:\s*'([^']+)'[\s\S]*?label:\s*'([^']+)'[\s\S]*?group:\s*'([^']+)'[\s\S]*?mitre:\s*'([^']*)'[\s\S]*?description:\s*'([^']*)'[\s\S]*?requiresTarget:\s*(true|false)/g

const engines = []
let m
while ((m = re.exec(src))) {
  engines.push({
    id: m[1],
    label: m[2],
    group: m[3],
    mitre: m[4],
    description: m[5],
    requiresTarget: m[6] === 'true',
    agent: AGENT_REQUIRED.has(m[1]),
  })
}

const byGroup = {}
for (const e of engines) {
  ;(byGroup[e.group] ||= []).push(e)
}

let md = `<!-- AUTO-GENERATED by scripts/generate_system_book_engines.mjs — ${engines.length} engines -->\n\n`

for (const groupId of Object.keys(byGroup).sort()) {
  const list = byGroup[groupId].sort((a, b) => a.id.localeCompare(b.id))
  const title = GROUP_HE[groupId] || groupId
  md += `### ${title} (\`${groupId}\`) — ${list.length} מנועים\n\n`
  md += `| # | מזהה | שם | MITRE | Remote | Agent | יעד | מה עושה (תמצית) |\n`
  md += `|---|------|-----|-------|--------|-------|-----|------------------|\n`
  list.forEach((e, i) => {
    const remote = e.agent ? '—' : '✓'
    const ag = e.agent ? '**חובה**' : '—'
    const tgt = e.requiresTarget ? 'כן' : 'לא'
    const desc = e.description.replace(/\|/g, '/').replace(/\n/g, ' ').slice(0, 100)
    md += `| ${i + 1} | \`${e.id}\` | ${e.label} | ${e.mitre || '—'} | ${remote} | ${ag} | ${tgt} | ${desc} |\n`
  })
  md += '\n'
}

const out = join(root, 'docs/manuals/he/_engines-appendix-generated.md')
writeFileSync(out, md)
console.log(`Wrote ${engines.length} engines → ${out}`)
