#!/usr/bin/env node
/**
 * Generates Hebrew engine encyclopedia appendix for WEISSMAN-COMMAND-CENTER-BOOK.md
 *
 * Reads the engine catalog and the agent-required set from source-of-truth modules
 * instead of regex-scraping enginesRegistry.js. The old single-quote-only regex
 * silently dropped any engine whose `description` used double quotes (it contained
 * an apostrophe) and mis-attributed the following engine's description; the
 * hard-coded AGENT_REQUIRED set had also drifted from the Rust array.
 */
import { writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadEngineReality } from './lib/engine_reality.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

const GROUP_HE = {
  recon: 'מודיעין ו-Recon',
  web: 'Web / API',
  ai: 'AI / LLM',
  cloud: 'ענן ותשתית',
  ot: 'OT / ICS / IoT',
  stealth: 'Stealth / Evasion',
  crypto: 'קריפטו וזהות',
  network: 'רשת ופרוטוקולים',
  supply_chain: 'Supply Chain',
  apt: 'APT / Top-Tier',
  malware: 'Malware ו-Ransomware',
  social: 'הנדסה חברתית',
  mobile: 'מובייל',
  data: 'דליפת מידע',
  defense: 'הגנה ו-Blue Team',
}

const { registry, agentRequired } = await loadEngineReality(root)

const engines = registry.map((e) => ({
  id: e.id,
  label: e.label,
  group: e.group,
  mitre: e.mitre,
  description: e.description ?? '',
  requiresTarget: Boolean(e.requiresTarget),
  agent: agentRequired.has(e.id),
}))

if (engines.length !== registry.length) {
  throw new Error(`engine count mismatch: ${engines.length} generated vs ${registry.length} in registry`)
}

const byGroup = {}
for (const e of engines) {
  ;(byGroup[e.group] ||= []).push(e)
}

let md = `<!-- AUTO-GENERATED by scripts/generate_system_book_engines.mjs — ${engines.length} engines -->\n\n`

for (const groupId of Object.keys(byGroup).sort()) {
  const list = byGroup[groupId].sort((a, b) => a.id.localeCompare(b.id))
  const title = GROUP_HE[groupId] || groupId
  md += `### ${title} (\`${groupId}\`) — ${list.length} מנועים\n\n`
  md += `| # | מזהה | שם | MITRE | Remote | Agent | יעד | מה עושה (תמצית) |\n`
  md += `|---|------|-----|-------|--------|-------|-----|------------------|\n`
  list.forEach((e, i) => {
    const remote = e.agent ? '—' : '✓'
    const ag = e.agent ? '**חובה**' : '—'
    const tgt = e.requiresTarget ? 'כן' : 'לא'
    const desc = e.description.replace(/\|/g, '/').replace(/\n/g, ' ').slice(0, 100)
    md += `| ${i + 1} | \`${e.id}\` | ${e.label} | ${e.mitre || '—'} | ${remote} | ${ag} | ${tgt} | ${desc} |\n`
  })
  md += '\n'
}

const out = join(root, 'docs/manuals/he/_engines-appendix-generated.md')
writeFileSync(out, md)
console.log(`Wrote ${engines.length} engines → ${out}`)
