#!/usr/bin/env node
/**
 * Generates live engine encyclopedia appendices for the Command Center books.
 *
 * Reads the engine catalog and the agent-required set from source-of-truth modules
 * instead of regex-scraping enginesRegistry.js. The old single-quote-only regex
 * silently dropped any engine whose `description` used double quotes (it contained
 * an apostrophe) and mis-attributed the following engine's description; the
 * hard-coded AGENT_REQUIRED set had also drifted from the Rust array.
 */
import { writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadEngineReality } from './lib/engine_reality.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

const GROUP_HE = {
  recon: 'מודיעין ו-Recon',
  web: 'Web / API',
  ai: 'AI / LLM',
  cloud: 'ענן ותשתית',
  ot: 'OT / ICS / IoT',
  stealth: 'Stealth / Evasion',
  crypto: 'קריפטו וזהות',
  network: 'רשת ופרוטוקולים',
  supply_chain: 'Supply Chain',
  apt: 'APT / Top-Tier',
  malware: 'Malware ו-Ransomware',
  social: 'הנדסה חברתית',
  mobile: 'מובייל',
  data: 'דליפת מידע',
  defense: 'הגנה ו-Blue Team',
  deception: 'הטעיה / Honeynet',
}

const GROUP_EN = {
  recon: 'Recon & OSINT',
  web: 'Web / API',
  ai: 'AI / LLM',
  cloud: 'Cloud & infrastructure',
  ot: 'OT / ICS / IoT',
  stealth: 'Stealth / Evasion',
  crypto: 'Crypto & identity',
  network: 'Network & protocols',
  supply_chain: 'Supply chain',
  apt: 'APT / Top-tier',
  malware: 'Malware & ransomware',
  social: 'Social engineering',
  mobile: 'Mobile',
  data: 'Data leakage',
  defense: 'Defense / blue team',
  deception: 'Deception / honeynet',
}

const { registry, agentRequired } = await loadEngineReality(root)

const engines = registry.map((e) => ({
  id: e.id,
  label: e.label,
  group: e.group,
  mitre: e.mitre,
  description: e.description ?? '',
  requiresTarget: Boolean(e.requiresTarget),
  agent: agentRequired.has(e.id),
}))

if (engines.length !== registry.length) {
  throw new Error(`engine count mismatch: ${engines.length} generated vs ${registry.length} in registry`)
}

const byGroup = {}
for (const e of engines) {
  ;(byGroup[e.group] ||= []).push(e)
}

function render(lang) {
  const he = lang === 'he'
  const titles = he ? GROUP_HE : GROUP_EN
  const enginesWord = he ? 'מנועים' : 'engines'
  const targetYes = he ? 'כן' : 'yes'
  const targetNo = he ? 'לא' : 'no'
  const agentReq = he ? '**חובה**' : '**Required**'
  const header = he
    ? `| # | מזהה | שם | MITRE | Remote | Agent | יעד | מה עושה (תמצית) |`
    : `| # | ID | Name | MITRE | Remote | Agent | Target | Summary |`
  let md = `<!-- AUTO-GENERATED by scripts/generate_system_book_engines.mjs — ${engines.length} engines -->\n\n`
  for (const groupId of Object.keys(byGroup).sort()) {
    const list = byGroup[groupId].sort((a, b) => a.id.localeCompare(b.id))
    const title = titles[groupId] || groupId
    md += `### ${title} (\`${groupId}\`) — ${list.length} ${enginesWord}\n\n`
    md += `${header}\n`
    md += `|---|------|-----|-------|--------|-------|-----|------------------|\n`
    list.forEach((e, i) => {
      const remote = e.agent ? '—' : '✓'
      const ag = e.agent ? agentReq : '—'
      const tgt = e.requiresTarget ? targetYes : targetNo
      const desc = e.description.replace(/\|/g, '/').replace(/\n/g, ' ').slice(0, 100)
      md += `| ${i + 1} | \`${e.id}\` | ${e.label} | ${e.mitre || '—'} | ${remote} | ${ag} | ${tgt} | ${desc} |\n`
    })
    md += '\n'
  }
  return md
}

const heOut = join(root, 'docs/manuals/he/_engines-appendix-generated.md')
const enOut = join(root, 'docs/manuals/en/_engines-appendix-generated-en.md')
writeFileSync(heOut, render('he'))
writeFileSync(enOut, render('en'))
console.log(`Wrote ${engines.length} engines → ${heOut}`)
console.log(`Wrote ${engines.length} engines → ${enOut}`)
