/**
 * Sales-grade metadata for Weissman Platform Encyclopedia (Hebrew).
 * Keys match route patterns from main.jsx (basename-relative).
 */

export const INTRO_PAGES = [
  {
    id: 'cover',
    title: 'שער — Weissman Cybersecurity',
    what: 'מסמך מוצר רשמי לחברה, למכירות, ללקוחות ולשותפים — מיפוי מלא של כל יכולת הפלטפורמה.',
    why: 'מאפשר להציג את Weissman כפלטפורמת אבטחת מידע ברמה עולמית עם שקיפות מלאה: כל לוח, כל מנוע, כל שירות.',
    when: 'לפני demo, RFP, due diligence, onboarding מנהלים, או הדרכת צוות מכירות.',
    where: 'PDF / Markdown — `docs/sales/WEISSMAN-PLATFORM-ENCYCLOPEDIA.md`',
    how: 'פתחו את תוכן העניינים → קפצו לעמוד לפי מספר → קראו את ששת הממדים (מה·למה·מתי·איפה·איך·כמה).',
    howMuch: '533+ מנועים · 94+ מסכי Command Center · 9 crates Rust · multi-tenant SaaS',
    who: 'CEO, VP Sales, Pre-Sales, CISO, MSSP',
    output: 'הבנה מלאה של היקף המוצר ללא גישה לסביבה',
  },
  {
    id: 'how-to-read',
    title: 'איך קוראים את האנציקלופedia',
    what: 'מדריך קריאה לששת הממדים שמופיעים בכל עמוד.',
    why: 'אחידות — כל אדם במערכת מוצר מדבר באותה שפה.',
    when: 'לפני קריאה ראשונה.',
    where: 'עמוד זה.',
    how: '|**מה**| תפקיד היכולת | **למה**| ערך עסקי | **מתי**| שלב engagement | **איפה**| URL / שירות | **איך**| צעדים ב-UI | **כמה**| מכסות, תפקידים, זמן |',
    howMuch: '6 ממדים × כל יכולת',
    who: 'כולם',
    output: 'מסוגלות לנווט במסמך ב-30 שניות',
  },
  {
    id: 'platform-map',
    title: 'מפת הפלטפורמה — 30 שניות',
    what: 'Weissman = Command Center (React) + API (Rust/Axum) + Worker (jobs) + Agent (endpoint) + PostgreSQL + Redis.',
    why: 'הלקוח רואה findings אמיתיים מ-probes חיים — לא דמו.',
    when: 'פתיחת כל שיחת מכירה.',
    where: 'https://<host>/command-center/',
    how: 'Login → Cockpit → Client → Scan → Job → Finding → Report. מנועים ב-Engine Matrix או Hub ייעודי.',
    howMuch: '533 מנועים · strict billing ב-production · RLS per tenant',
    who: 'Pre-Sales, Architect',
    output: 'תמונה מental של זרימת הנתונים',
  },
  {
    id: 'complexity-ladder',
    title: 'סולם מורכבות — מקטן לגדול',
    what: 'מדרג 0–5: Login → KPI → רשימות → Hub יחיד → Hub רב-מנועי → Cockpit/CEO.',
    why: 'מכירות מתחילות מ-Quick Win (רמה 2–3) ומתקדמות ל-Enterprise (4–5).',
    when: 'תכנון POC.',
    where: 'כל Command Center.',
    how: 'יום 1: Clients+Scan+Findings. שבוע 1: Cloud/IaC Hub. חודש 1: Kill Chain + Council + Agent fleet.',
    howMuch: 'POC מומלץ: 1 client, 5–10 מנועים, 30 scans/month (Starter)',
    who: 'Sales, CSM',
    output: 'תוכנית POC מדורגת',
  },
  {
    id: 'billing-overview',
    title: 'מודל מסחרי ומכסות',
    what: 'Multi-tenant SaaS עם Paddle Billing: Starter / Professional / Enterprise.',
    why: 'גמישות MSSP — מכסות לפי לקוחות וסריקות חודשיות.',
    when: 'לפני scale או חתימה.',
    where: '/command-center/billing',
    how: 'Admin → Billing → Checkout Paddle → webhook מעדכן subscription.',
    howMuch: 'Starter: 5 clients · 30 scans/mo | Professional: 25 · 300 | Enterprise: 500 · 5000',
    who: 'Sales, Finance, Admin',
    output: 'מנוי פעיל + usage counters',
  },
  {
    id: 'roles-rbac',
    title: 'תפקידים והרשאות',
    what: 'RBAC: viewer, operator, admin, CEO/superadmin. MFA. SSO אופציונלי.',
    why: 'הפרדת duties — SOC מריץ, admin מנהל, CEO רואה vault.',
    when: 'Onboarding משתמשים.',
    where: '/command-center/admin, /sso-config',
    how: 'Admin → Users → role. MFA ב-login. SSO ב-OIDC/SAML.',
    howMuch: 'CEO vault + /ceo — רק CEO/superadmin',
    who: 'Admin, Security',
    output: 'משתמשים עם scope מינימלי',
  },
  {
    id: 'agent-overview',
    title: 'סוכן קצה (Endpoint Agent)',
    what: 'weissman-agent — בינארי per-OS, WebSocket לשרת, detections מקומיות.',
    why: '45+ מנועים דורשים Agent — malware, network local, exfil, hardware.',
    when: 'לפני OT/EDR/malware engagements.',
    where: '/command-center/agents, /install/agent.sh',
    how: 'Agents → token → curl install script → online → Run agent-required engine.',
    howMuch: 'Linux x64/aarch64 ב-Docker image; native: package_agent_binaries.sh',
    who: 'Endpoint team, Red Team',
    output: 'Host findings + fleet status',
  },
  {
    id: 'data-truth',
    title: 'עקרון האמת — Live Only',
    what: 'אין findings מזויפים. מנוע agent_required מציג empty state עד Agent מחובר.',
    why: 'אמינות מכירה ו-breach readiness — כל ממצא = probe אמיתי.',
    when: 'תמיד.',
    where: 'כל לוח עם EvidenceNotice / PageShell.',
    how: 'בדמו: הראו empty state → התקינו Agent → הריצו שוב → findings חיים.',
    howMuch: '0 demo data ב-production paths',
    who: 'Sales (חובה להבין!), QA',
    output: 'אמון לקוח',
  },
]

export const PLATFORM_MODULES = [
  {
    id: 'weissman-server',
    title: 'weissman-server — API + WebSocket',
    what: 'שרת Rust/Axum על פורט 8000: REST API, WS agents, SSE telemetry, billing webhooks.',
    why: 'ליבת הפלטפorma — כל ה-UI וה-Agent מתחברים לכאן.',
    when: 'תמיד — runtime חובה.',
    where: 'Docker service `backend`, `./target/debug/weissman-server`',
    how: 'docker compose up backend; health: GET /api/health',
    howMuch: '1 instance min; scale behind load balancer',
    who: 'DevOps',
    output: 'API זמין + migrations',
  },
  {
    id: 'weissman-worker',
    title: 'weissman-worker — Job Consumer',
    what: 'צורך jobs מ-Redis/DB, מריץ מנועים, שומר findings.',
    why: 'סריקות async — UI לא חוסם.',
    when: 'כל scan / mission / council job.',
    where: 'Docker `worker`',
    how: 'worker + redis + postgres; jobs ב-/jobs',
    howMuch: 'N workers לפי throughput',
    who: 'DevOps, SOC',
    output: 'jobs completed + findings',
  },
  {
    id: 'weissman-agent',
    title: 'weissman-agent — Endpoint',
    what: 'סוכן Rust: detections, telemetry, remote commands.',
    why: 'מנועים שלא ניתן להריץ remotely.',
    when: 'Endpoint / malware / local network.',
    where: 'endpoint host, /srv/bin/agents',
    how: '/install/agent.sh + WEISSMAN_AGENT_TOKEN',
    howMuch: '1 agent per host typical',
    who: 'Endpoint admin',
    output: 'WS connection + findings',
  },
  {
    id: 'postgres',
    title: 'PostgreSQL 16 — Data Layer',
    what: 'tenants, clients, findings, jobs, billing, RLS.',
    why: 'multi-tenant isolation.',
    when: 'תמיד.',
    where: 'docker postgres:5432',
    how: 'WEISSMAN_MIGRATE_URL on boot',
    howMuch: 'managed PG recommended prod',
    who: 'DBA',
    output: 'persistent state',
  },
  {
    id: 'redis',
    title: 'Redis 7 — Queue + Cache',
    what: 'job queue, rate limits, sessions cache.',
    why: 'async pipeline.',
    when: 'scans, worker.',
    where: 'docker redis:6379',
    how: 'REDIS_URL in .env',
    howMuch: '1 instance typical',
    who: 'DevOps',
    output: 'job dispatch',
  },
  {
    id: 'paddle-billing',
    title: 'Paddle Billing',
    what: 'checkout, subscriptions, webhooks, pri_* price IDs.',
    why: 'SaaS revenue.',
    when: 'production strict billing.',
    where: 'Paddle dashboard + /api/billing/*',
    how: 'PADDLE_* env + billing_plans.paddle_price_id',
    howMuch: '3 plans — see intro billing page',
    who: 'Finance, Admin',
    output: 'active subscription',
  },
  {
    id: 'smtp',
    title: 'SMTP — Signup & Alerts',
    what: 'WEISSMAN_SMTP_* — verification email, alerts.',
    why: 'self-serve signup.',
    when: 'onboarding tenants.',
    where: 'env + Mailpit staging',
    how: 'WEISSMAN_SMTP_HOST/PORT/FROM',
    howMuch: 'transactional volume',
    who: 'DevOps',
    output: 'emails delivered',
  },
  {
    id: 'llm',
    title: 'LLM — Council & AI',
    what: 'OpenAI-compatible: WEISSMAN_LLM_BASE_URL.',
    why: 'Council debate, General Mission, Ask Weissman, AI Analysis.',
    when: 'AI features enabled.',
    where: 'external vLLM/Ollama',
    how: 'env + /council-queue, /ask',
    howMuch: 'token cost external',
    who: 'AI ops',
    output: 'LLM responses',
  },
  {
    id: 'oast-server',
    title: 'OAST Server — Out-of-Band',
    what: 'weissman-oast-server: HTTP/DNS interaction logging.',
    why: 'SSRF, fuzz, OOB verification.',
    when: 'web fuzz / OAST engines.',
    where: 'profile oast, separate host prod',
    how: 'WEISSMAN_OAST_DOMAIN + LISTENER_URL',
    howMuch: 'wildcard DNS required prod',
    who: 'Red team infra',
    output: 'oast_interaction_hits',
  },
  {
    id: 'frontend',
    title: 'Command Center — React SPA',
    what: 'Vite/React/Tailwind — 94+ pages, i18n HE/EN.',
    why: 'UX מכירה + SOC.',
    when: 'כל גישת משתמש.',
    where: '/command-center/',
    how: 'npm run build → nginx or vite dev',
    howMuch: '94/94 UI audit pass',
    who: 'All users',
    output: 'interactive UI',
  },
]

/** @type {Record<string, Partial<{title,what,why,when,where,how,howMuch,who,output,engines,apis,group,role}>} */
export const ROUTE_META = {
  login: {
    title: 'התחברות',
    group: 'כניסה',
    what: 'מסך Login — JWT session, MFA optional.',
    why: 'שער כניסה מאובטח ל-Command Center.',
    when: 'כל session.',
    where: '/command-center/login',
    how: 'POST /api/login → cookie → redirect Cockpit.',
    howMuch: 'lockout after failed attempts',
    who: 'כל משתמש',
    output: 'authenticated session',
    apis: 'POST /api/login',
  },
  status: {
    title: 'דף סטטוס',
    group: 'כניסה',
    what: 'בריאות ציבורית — uptime, גרסה.',
    why: 'SLA transparency.',
    when: 'monitoring.',
    where: '/command-center/status',
    how: 'GET /api/health',
    howMuch: 'public read',
    who: 'NOC, customer',
    output: 'health JSON',
  },
  '/': {
    title: 'תא הפיקוד (Cockpit)',
    group: 'פיקוד',
    what: 'דף הבית — KPI, SSE telemetry, client selector, quick links.',
    why: 'תמונת מצב אחת לכל engagement.',
    when: 'כל כניסה.',
    where: '/command-center/',
    how: 'בחר client → KPIs → קפיצה ל-Findings/Jobs/Scan.',
    howMuch: 'real-time SSE',
    who: 'SOC lead, CISO',
    output: 'operational dashboard',
  },
  clients: {
    title: 'לקוחות',
    group: 'סביבת עבודה',
    what: 'רשימת ארגוני לקוח + scope (domains/IPs).',
    why: 'Weissman לא סורק בלי scope מוגדר — compliance.',
    when: 'תמיד לפני סריקה.',
    where: '/command-center/clients',
    how: 'Clients → Add → domains → Create.',
    howMuch: 'max_clients per plan; strict billing blocks',
    who: 'Operator+, Sales (view)',
    output: 'client records',
    apis: 'GET/POST /api/clients',
  },
  'clients/new': {
    title: 'לקוח חדש',
    group: 'סביבת עבודה',
    what: 'טופס onboarding לקוח.',
    why: 'הקמת scope ראשון.',
    when: 'engagement חדש.',
    where: '/command-center/clients/new',
    how: 'מלא שם, email, domains → Create → Client Detail.',
    howMuch: '1 client slot',
    who: 'Operator+',
    output: 'new client_id',
  },
  'clients/:id': {
    title: 'פרטי לקוח',
    group: 'סביבת עבודה',
    what: 'מרכז שליטה: Launch Scan, config engines, findings, report.',
    why: 'hub מרכזי לכל engagement.',
    when: 'יום-יום SOC.',
    where: '/command-center/clients/:id',
    how: 'Launch Scan → Jobs → Findings → Generate Report.',
    howMuch: 'Launch Scan = N engines × 1 quota each',
    who: 'Operator+',
    output: 'jobs, findings, PDF',
    apis: 'POST scan, GET findings',
  },
  'clients/:id/engagements': {
    title: 'Engagements',
    group: 'סביבת עבודה',
    what: 'תקופות engagement, ROE, milestones.',
    why: 'MSSP מנהל מספר תקופות ללקוח.',
    when: 'contract phases.',
    where: '/command-center/clients/:id/engagements',
    how: 'Create engagement → dates → link findings.',
    howMuch: 'unlimited per client',
    who: 'CSM, PM',
    output: 'engagement timeline',
  },
  'clients/:id/evidence': {
    title: 'Evidence Vault',
    group: 'סביבת עבודה',
    what: 'אחסון ראיות: screenshots, logs, exports.',
    why: 'audit trail + compliance.',
    when: 'post-assessment.',
    where: '/command-center/clients/:id/evidence',
    how: 'Upload / attach from findings.',
    howMuch: 'storage per deployment',
    who: 'Analyst, Auditor',
    output: 'evidence bundle',
  },
  'clients/:id/discovery/saas-idp': {
    title: 'SaaS & IdP Discovery',
    group: 'סביבת עבודה',
    what: 'גילוי SaaS shadow IT + IdP footprint.',
    why: 'attack surface beyond owned domains.',
    when: 'identity assessments.',
    where: '.../discovery/saas-idp',
    how: 'Run discovery → review services.',
    howMuch: '1 scan quota',
    who: 'Identity team',
    output: 'SaaS inventory findings',
  },
  engines: {
    title: 'Engine Matrix — חדר המנועים',
    group: 'סביבת עבודה',
    what: 'מטריצת כל המנועים לפי קבוצות — enable, filter, navigate.',
    why: 'שליטה granular על 533 מנועים.',
    when: 'בחירת מנוע / run-all config.',
    where: '/command-center/engines',
    how: 'Filter group → click engine → Engine Detail → Run.',
    howMuch: '533 engines in registry',
    who: 'Red team, SOC',
    output: 'engine runs',
  },
  'engines/:engineId': {
    title: 'פרופיל מנוע',
    group: 'מנועים',
    what: 'דף מנוע בודד — history, run, export, MITRE.',
    why: 'בדיקה ממוקדת (JWT, asm, …).',
    when: 'targeted test.',
    where: '/command-center/engines/:engineId',
    how: 'Select client → target → Run → Jobs.',
    howMuch: '1 scan per run; agent if required',
    who: 'Operator+',
    output: 'engine-specific findings',
  },
  'engines/top-tier': {
    title: 'Top-Tier Engines Hub',
    group: 'מנועים',
    what: 'מנועי APT / nation-state grade.',
    why: 'differentiator — יכולות שלא קיימות אצל מתחרים.',
    when: 'advanced red team.',
    where: '/command-center/engines/top-tier',
    how: 'Pick engine → profile → Run.',
    howMuch: 'subset of apt group',
    who: 'Elite red team',
    output: 'APT-grade findings',
  },
  'engines/top-tier/:engineId': {
    title: 'Top-Tier Engine Profile',
    group: 'מנועים',
    what: 'פרופיל מפורט למנוע top-tier.',
    why: 'deep dive APT module.',
    when: 'specialized engagement.',
    where: '/command-center/engines/top-tier/:id',
    how: 'Same as engine detail + enhanced metadata.',
    howMuch: '1 scan',
    who: 'Red team lead',
    output: 'specialized findings',
  },
  'engines/strategic': {
    title: 'Strategic Engine Program',
    group: 'מנועים',
    what: 'תוכנית מנועים אסטרטגית — roadmap client.',
    why: 'Enterprise multi-quarter planning.',
    when: 'strategic accounts.',
    where: '/command-center/engines/strategic',
    how: 'Review program → schedule waves.',
    howMuch: 'program-level',
    who: 'VP Security, CSM',
    output: 'engine roadmap',
  },
  'engines/business/:engineId': {
    title: 'Business Engine Profile',
    group: 'מנועים',
    what: 'מנוע עם framing עסקי — risk, compliance mapping.',
    why: 'מכירות ל-CISO non-technical.',
    when: 'executive briefing.',
    where: '/command-center/engines/business/:id',
    how: 'Present business impact → run demo.',
    howMuch: '1 scan',
    who: 'Sales, CISO',
    output: 'business-aligned report',
  },
  'engines/osint': {
    title: 'OSINT Engine Profile',
    group: 'מנועים',
    what: 'OSINT ממוקד — public data gathering.',
    why: 'recon phase zero intrusion.',
    when: 'assessment kickoff.',
    where: '/command-center/engines/osint',
    how: 'Target domain → Run osint.',
    howMuch: '1 scan',
    who: 'Intel analyst',
    output: 'OSINT findings',
    engines: 'osint',
  },
  billing: {
    title: 'חיוב ושימוש',
    group: 'סביבת עבודה',
    what: 'Paddle subscription, usage meters, checkout.',
    why: 'SaaS monetization + quota visibility.',
    when: 'before scale; on 402/429.',
    where: '/command-center/billing',
    how: 'View usage → Upgrade → Paddle checkout.',
    howMuch: 'Starter 5/30 · Pro 25/300 · Ent 500/5000',
    who: 'Admin',
    output: 'active plan',
  },
  playbooks: {
    title: 'מדריכי SOAR',
    group: 'סביבת עבודה',
    what: 'when {conditions} do [actions] on new findings.',
    why: 'automation — Slack, webhook, status.',
    when: 'after first findings.',
    where: '/command-center/playbooks',
    how: 'Create → conditions → actions → dry-run.',
    howMuch: 'unlimited playbooks',
    who: 'SOC automation',
    output: 'automated responses',
  },
  ask: {
    title: 'שאל את Weissman',
    group: 'סביבת עבודה',
    what: 'NL→SQL read-only queries on tenant data.',
    why: 'instant answers without SQL skills.',
    when: 'ad-hoc questions.',
    where: '/command-center/ask',
    how: 'Type question → audit logged → table result.',
    howMuch: '15s timeout; LLM required',
    who: 'Analyst, manager',
    output: 'query results',
  },
  'vuln-intel': {
    title: 'מודיעין חולשות',
    group: 'סביבת עבודה',
    what: 'CVE, KEV, EPSS dashboard.',
    why: 'prioritize by exploitability.',
    when: 'triage.',
    where: '/command-center/vuln-intel',
    how: 'Browse KEV → correlate findings.',
    howMuch: 'feeds updated live',
    who: 'Vuln management',
    output: 'intel context',
  },
  findings: {
    title: 'ממצאים',
    group: 'פיקוד',
    what: 'כל findings cross-client — filter, triage, export.',
    why: 'יום-יום SOC workbench.',
    when: 'daily triage.',
    where: '/command-center/findings',
    how: 'Filter severity → status workflow → CSV export.',
    howMuch: 'unlimited findings storage',
    who: 'Analyst',
    output: 'triage state',
  },
  jobs: {
    title: 'משימות (Jobs)',
    group: 'פיקוד',
    what: 'Async job queue — queued/running/done/failed.',
    why: 'track every scan pipeline.',
    when: 'after every Run.',
    where: '/command-center/jobs',
    how: 'Auto-refresh → click job → status.',
    howMuch: '1 job per scan enqueue',
    who: 'Operator',
    output: 'job completion',
  },
  cloud: {
    title: 'Cloud Control Tower',
    group: 'מעבדות מנועים',
    what: 'Hub: AWS, Azure, GCP, K8s, IaC, Serverless tabs.',
    why: 'single pane cloud offensive security.',
    when: 'cloud assessments.',
    where: '/command-center/cloud',
    how: 'Tab → select client → Run engine.',
    howMuch: '6 engines minimum per tab',
    who: 'Cloud security',
    output: 'cloud findings',
    engines: 'aws_attack, azure_attack, gcp_attack, k8s_container, iac_misconfig, serverless_attack',
  },
  'supply-chain': {
    title: 'Supply Chain Hub',
    group: 'מעבדות מנועים',
    what: 'SBOM, registry, CI/CD, dependency attacks.',
    why: 'SolarWinds-era risk coverage.',
    when: 'DevSecOps assessments.',
    where: '/command-center/supply-chain',
    how: 'Pick panel → Run per engine.',
    howMuch: 'multi-engine hub',
    who: 'AppSec',
    output: 'supply chain findings',
  },
  'iac-security': {
    title: 'IaC Security Center',
    group: 'מעבדות מנועים',
    what: 'Terraform, K8s, Helm, GitOps misconfig — 50+ IaC parsers.',
    why: 'shift-left + drift + live blast radius.',
    when: 'infra review.',
    where: '/command-center/iac-security',
    how: 'Upload/repo connect → scan → compliance reports.',
    howMuch: 'iac_misconfig engine family',
    who: 'Platform eng',
    output: 'IaC findings + compliance PDFs',
    engines: 'iac_misconfig',
  },
  agents: {
    title: 'ניהול סוכנים',
    group: 'תפעול',
    what: 'Fleet status, tokens, install script, online hosts.',
    why: '45 agent-required engines depend on this.',
    when: 'before endpoint tests.',
    where: '/command-center/agents',
    how: 'Generate token → install.sh → verify online.',
    howMuch: 'N agents = N hosts',
    who: 'Endpoint admin',
    output: 'connected fleet',
  },
  'council-queue': {
    title: 'Council Queue (HITL)',
    group: 'תפעול',
    what: 'AI Council debates — human-in-the-loop approval.',
    why: 'high-stakes AI decisions with governance.',
    when: 'General Mission / Council jobs.',
    where: '/command-center/council-queue',
    how: 'Review debate → Approve/Reject.',
    howMuch: 'LLM + billing quota per mission',
    who: 'Senior analyst, admin',
    output: 'approved AI actions',
  },
  ceo: {
    title: 'CEO Command Center',
    group: 'ניהול מערכת',
    what: 'Executive dashboard — strategic KPIs, restricted.',
    why: 'C-suite visibility.',
    when: 'board reporting.',
    where: '/command-center/ceo',
    how: 'CEO login → strategic view.',
    howMuch: 'CEO role only',
    who: 'CEO',
    output: 'executive summary',
  },
  'dark-web': {
    title: 'Dark Web Monitor',
    group: 'מודיעין',
    what: 'ניטור dark web, paste sites, credential leaks — correlation ללקוח.',
    why: 'זיהוי דליפות לפני exploit — ערך מכירה גבוה ל-executive.',
    when: 'continuous monitoring / assessment.',
    where: '/command-center/dark-web',
    how: 'Configure feeds → Run ingest → correlate client domains.',
    howMuch: 'feeds/API keys; threat_ingest consumes quota',
    who: 'Threat intel, SOC',
    output: 'leak findings',
  },
  'ceo-vault': {
    title: 'CEO Vault',
    group: 'ניהול מערכת',
    what: 'Highly restricted sensitive data vault.',
    why: 'executive-only intel.',
    when: 'classified engagements.',
    where: '/command-center/ceo-vault',
    how: 'CEO/superadmin only.',
    howMuch: 'strictest RBAC',
    who: 'CEO',
    output: 'vault contents',
  },
}

/** Friendly Hebrew titles for dynamic / nested routes */
export const ROUTE_TITLES = {
  'ai-arena': 'AI Red Team Arena',
  'ai-arena/:clientId': 'AI Red Team Arena — לקוח',
  'attack-chain/:clientId': 'Attack Chain — שרשרת תקיפה ללקוח',
  'attack-surface-graph/:clientId': 'Attack Surface Graph — גraf לקוח',
  'cicd-matrix/:clientId': 'CI/CD Threat Matrix — לקוח',
  'digital-twin/:clientId': 'Digital Twin — סimulation לקוח',
  'memory-lab/:clientId': 'Memory Forensics Lab — לקוח',
  'report/:clientId': 'דוח PDF — לקוח',
  'semantic-logic/:clientId': 'Semantic Logic Engine — לקוח',
  'timing-profiler': 'Quantum Timing Profiler',
  'timing-profiler/:clientId': 'Quantum Timing Profiler — לקוח',
  operations: 'Operations View — תצוגת תפעול',
  'system-core': 'System Core — ליבת מערכת',
  'verification/oob': 'OOB Verification — אימות Out-of-Band',
  admin: 'ניהול מערכת (Admin)',
  'intel-map': 'Global Intel Map — מפת מודיעין',
  'engine-catalog': 'קטalog מנועים ללקוח',
  'zero-day-radar': 'Zero-Day Radar',
  'threat-intel': 'Threat Intel Hub',
  'threat-hunting': 'Threat Hunting Workbench',
  'threat-analysis': 'Threat Analysis Center',
  'dark-web': 'Dark Web Monitor',
  'incident-response': 'Incident Response Center',
  'cloud-posture': 'Cloud Posture (CSPM)',
  'network-protocols': 'Network Protocols Lab',
  'mobile-security': 'Mobile Security Hub',
  'ot-ics': 'OT/ICS Security Hub',
  'social-engineering': 'Social Engineering Hub',
  'risk-graph': 'Risk Graph Visualization',
  'baseline-drift': 'Baseline & Drift',
  'rate-limits': 'Rate Limit Analytics',
  'scan-scheduler': 'Scan Scheduler',
  'alert-rules': 'Alert Rules Engine',
  'containment-rules': 'Containment Rules Builder',
  'identity-context': 'Identity Context Manager',
  'sso-config': 'SSO Configuration',
  'engine-management': 'Engine Management Console',
  'system-config': 'System Configuration',
  metrics: 'Metrics Dashboard',
  integrations: 'Integration Manager',
  compliance: 'Compliance Frameworks',
  sbom: 'SBOM Browser',
  remediation: 'Remediation Hub',
  'kill-chain': 'Kill Chain Orchestrator',
  'ai-analysis': 'AI Analysis Engine',
  'exploit-lab': 'Exploit Research Lab',
  'nexus-swarm': 'Nexus Sovereign Swarm',
  'roe-approvals': 'RoE Approvals',
  'template-engine': 'Template Engine Workbench',
  'ast-fuzzing': 'AST Fuzzing Studio',
  'feedback-loop': 'Feedback Loop Verification',
  'domain-discovery': 'Domain Discovery',
  network: 'Network Intelligence Hub',
  'attack-surface': 'Attack Surface Management (EASM)',
  'graphql-security': 'GraphQL Security Command Center',
  'cicd-security': 'CI/CD Pipeline Security',
  'serverless-security': 'Serverless Security',
  'transport-security': 'Transport Security Command Center',
  'c2-covert-exfil': 'C2 & Covert Exfiltration Command Center',
  'websocket-security': 'WebSocket Security',
  'file-upload-lab': 'File Upload Security Lab',
  'jwt-lab': 'JWT Attack Lab',
  'waf-bypass': 'WAF Bypass Lab',
  'pqc-radar': 'PQC Radar',
  oast: 'OAST Dashboard',
  'engine-reliability': 'Engine Reliability Telemetry',
}

export const GROUP_DEFAULTS = {
  primary: {
    group: 'סביבת עבודה',
    why: 'ליבת העבודה היומיומית — לקוחות, מנועים, חיוב.',
    who: 'Operator, Sales (read)',
  },
  command: {
    group: 'פיקוד',
    why: 'שליטה תפעולית — ממצאים, jobs, cockpit.',
    who: 'SOC',
  },
  intelligence: {
    group: 'מודיעין',
    why: 'הקשר איומים — intel, hunting, IR.',
    who: 'Threat intel, SOC',
  },
  operations: {
    group: 'תפעול',
    why: 'הרצה активית — emulation, agents, remediation.',
    who: 'Red team, SOC',
  },
  engines: {
    group: 'מעבדות מנועים',
    why: 'מנועי offensive security מקובצים ל-Hub.',
    who: 'AppSec, Cloud, Red team',
  },
  governance: {
    group: 'ממשל',
    why: 'compliance, scheduling, containment.',
    who: 'GRC, SOC lead',
  },
  administration: {
    group: 'ניהול מערכת',
    why: 'platform admin, SSO, metrics.',
    who: 'Admin, DevOps',
  },
}

export const GROUP_HE = {
  recon: 'מודיעין ו-Recon',
  web: 'Web / API',
  ai: 'AI / LLM',
  cloud: 'ענן ותשתית',
  ot: 'OT / ICS / IoT',
  stealth: 'Stealth / Evasion',
  crypto: 'קריפטו וזהות',
  network: 'רשת ופרוטוקולים',
  supply_chain: 'Supply Chain',
  apt: 'APT / Top-Tier',
  malware: 'Malware ו-Ransomware',
  social: 'הנדסה חברתית',
  mobile: 'מובייל',
  data: 'דליפת מידע',
}

/** Surfaces outside standard nav — install, WS, legal, webhooks */
export const EXTRA_SURFACES = [
  {
    id: 'install-agent',
    title: 'Agent Install Script — /install/agent.sh',
    what: 'סקרipt התקנה one-liner ל-weissman-agent (Linux x64/aarch64).',
    why: 'Onboarding endpoint ב-30 שניות — ללא MDM מורכב.',
    when: 'לפני מנועי Agent-required.',
    where: 'GET /install/agent.sh · WEISSMAN_AGENT_BIN_DIR',
    how: 'Agents → token → curl -fsSL https://host/install/agent.sh | WEISSMAN_AGENT_TOKEN=… bash',
    howMuch: 'Linux gnu/musl; Docker image includes x64+aarch64',
    who: 'Endpoint admin',
    output: 'agent online ב-/agents',
    apis: 'GET /install/agent.sh · GET /api/agents/download/:platform',
  },
  {
    id: 'ws-command-center',
    title: 'WebSocket — /ws/command-center',
    what: 'SSE/WS telemetry: jobs, agent status, cockpit live updates.',
    why: 'Real-time SOC — ללא polling.',
    when: 'Cockpit, Jobs, Agents, Nexus Swarm.',
    where: 'wss://<host>/ws/command-center',
    how: 'Frontend מתחבר אוטומטית אחרי login.',
    howMuch: 'persistent connection per session',
    who: 'All authenticated users',
    output: 'live events',
    apis: 'WS /ws/command-center',
  },
  {
    id: 'ws-agents',
    title: 'WebSocket — Agent Fleet',
    what: 'Agent ↔ server bidirectional: detections, commands, heartbeat.',
    why: '45+ מנועים endpoint-only.',
    when: 'כל agent מותקן.',
    where: 'Agent config WEISSMAN_SERVER_URL',
    how: 'agent.sh → WS register → detections push.',
    howMuch: '1 connection per host',
    who: 'Agent binary',
    output: 'findings + fleet status',
    apis: 'WS agent protocol · POST /api/agents/dispatch',
  },
  {
    id: 'paddle-webhook',
    title: 'Paddle Billing Webhook',
    what: 'POST webhook מ-Paddle — subscription lifecycle.',
    why: 'SaaS revenue automation.',
    when: 'checkout / renew / cancel.',
    where: 'POST /api/billing/paddle/webhook',
    how: 'Paddle dashboard → URL + PADDLE_WEBHOOK_SECRET.',
    howMuch: '3 plans: Starter/Pro/Enterprise',
    who: 'Paddle, Finance',
    output: 'tenant_subscriptions updated',
    apis: 'POST /api/billing/paddle/webhook',
  },
  {
    id: 'legal-terms',
    title: 'Legal — Terms of Service',
    what: 'תנאי שימוש SaaS.',
    why: 'Enterprise procurement.',
    when: 'contract signing.',
    where: 'deploy/public/terms.html',
    how: 'Link from marketing / checkout.',
    howMuch: 'static HTML',
    who: 'Legal, Sales',
    output: 'signed agreement',
  },
  {
    id: 'legal-privacy',
    title: 'Legal — Privacy Policy',
    what: 'מדיניות פרטיות GDPR-ready.',
    why: 'EU/US customers.',
    when: 'onboarding.',
    where: 'deploy/public/privacy.html',
    how: 'Linked from signup.',
    howMuch: 'static HTML',
    who: 'Legal, DPO',
    output: 'compliance doc',
  },
  {
    id: 'legal-dpa',
    title: 'Legal — DPA',
    what: 'Data Processing Agreement.',
    why: 'Enterprise B2B.',
    when: 'Enterprise tier.',
    where: 'deploy/public/dpa.html',
    how: 'Attach to contract.',
    howMuch: 'static HTML',
    who: 'Legal',
    output: 'DPA signed',
  },
  {
    id: 'metrics-prom',
    title: 'Prometheus Metrics',
    what: 'GET /api/metrics — Prometheus scrape (token optional).',
    why: 'SRE observability.',
    when: 'production monitoring.',
    where: '/api/metrics',
    how: 'Prometheus job + WEISSMAN_METRICS_TOKEN.',
    howMuch: 'standard prom format',
    who: 'DevOps',
    output: 'Grafana dashboards',
    apis: 'GET /api/metrics',
  },
  {
    id: 'openapi',
    title: 'OpenAPI / API Health',
    what: 'GET /api/health — public health; API surface documented in serve.rs.',
    why: 'SLA + load balancer probes.',
    when: 'always.',
    where: '/api/health · /command-center/status',
    how: 'curl -sf /api/health',
    howMuch: 'no auth',
    who: 'NOC, customer',
    output: '200 OK JSON',
    apis: 'GET /api/health',
  },
  {
    id: 'self-serve-signup',
    title: 'Self-Serve Signup',
    what: 'הרשמת tenant חדש + email verification (SMTP).',
    why: 'PLG motion — ללא sales call.',
    when: 'WEISSMAN_SELF_SERVE_SIGNUP=1.',
    where: 'POST /api/onboarding/signup',
    how: 'Signup form → Mailpit/SMTP → verify → tenant.',
    howMuch: 'WEISSMAN_SMTP_* required',
    who: 'New customer',
    output: 'new tenant + admin user',
    apis: 'POST /api/onboarding/signup · verify endpoints',
  },
]

/** API domain groupings for part ה׳ */
export const API_DOMAIN_PAGES = [
  {
    id: 'api-auth',
    title: 'API — Auth & Sessions',
    prefixes: ['/api/login', '/api/auth', '/api/logout', '/api/mfa'],
    what: 'Login JWT, MFA, session, me, RBAC.',
    why: 'Zero-trust access.',
    when: 'כל request.',
    where: '/api/login · /api/auth/me',
    how: 'POST login → HttpOnly cookie → role checks.',
    who: 'All users',
    output: 'authenticated session',
  },
  {
    id: 'api-clients',
    title: 'API — Clients & Scope',
    prefixes: ['/api/clients'],
    what: 'CRUD clients, domains, config, engagements, evidence, graphs.',
    why: 'Scope boundary — legal + technical.',
    when: 'before any scan.',
    where: '/api/clients/*',
    how: 'Create client → domains → config engines.',
    who: 'Operator+',
    output: 'client records',
  },
  {
    id: 'api-scans',
    title: 'API — Scans & Jobs',
    prefixes: ['/api/command-center/scan', '/api/scan', '/api/jobs', '/api/poe-scan'],
    what: 'Enqueue engines, run-all, job status, POE scans.',
    why: 'Async pipeline core.',
    when: 'every Run / Launch Scan.',
    where: '/api/command-center/scan · /api/jobs/:id',
    how: 'POST scan → worker → GET job → findings.',
    who: 'Operator+',
    output: 'completed jobs',
  },
  {
    id: 'api-findings',
    title: 'API — Findings & Reports',
    prefixes: ['/api/findings', '/api/reports', '/api/export'],
    what: 'Findings list, triage, CSV/PDF export, clusters.',
    why: 'Deliverable to customer.',
    when: 'post-scan.',
    where: '/api/findings · /api/reports/*',
    how: 'GET findings → PATCH status → export.',
    who: 'Analyst',
    output: 'PDF/CSV reports',
  },
  {
    id: 'api-engines',
    title: 'API — Engines & Telemetry',
    prefixes: ['/api/engines', '/api/engines/'],
    what: 'Production list, capabilities, history, export, top-tier, telemetry.',
    why: '533 engines registry truth.',
    when: 'Engine Matrix, profiles.',
    where: '/api/engines/production · /api/engines/capabilities',
    how: 'GET production → dispatch by id.',
    who: 'Red team, SOC',
    output: 'engine metadata + runs',
  },
  {
    id: 'api-agents',
    title: 'API — Agents & Swarm',
    prefixes: ['/api/agents', '/api/swarm', '/api/edge-'],
    what: 'Fleet status, dispatch, download, swarm events, edge nodes.',
    why: 'Endpoint + distributed fuzz.',
    when: 'agent-required engines.',
    where: '/api/agents/* · /api/swarm/*',
    how: 'install → online → dispatch command.',
    who: 'Endpoint admin',
    output: 'host findings',
  },
  {
    id: 'api-billing',
    title: 'API — Billing & Usage',
    prefixes: ['/api/billing'],
    what: 'Usage meters, checkout, Paddle webhook.',
    why: 'SaaS monetization.',
    when: 'strict billing production.',
    where: '/api/billing/*',
    how: 'GET usage → checkout → webhook sync.',
    who: 'Admin',
    output: 'subscription state',
  },
  {
    id: 'api-intel',
    title: 'API — Threat Intel & SOC',
    prefixes: ['/api/threat-intel', '/api/soc', '/api/intel', '/api/ueba', '/api/baseline'],
    what: 'Intel feeds, incidents, hunting, UEBA, baseline drift.',
    why: 'Context beyond raw findings.',
    when: 'SOC operations.',
    where: '/api/threat-intel/* · /api/soc/*',
    how: 'Ingest → correlate → UI hubs.',
    who: 'Threat intel, SOC',
    output: 'intel-enriched view',
  },
  {
    id: 'api-ai',
    title: 'API — AI, Council, Ask',
    prefixes: ['/api/ask', '/api/council', '/api/ai-', '/api/general-mission'],
    what: 'NL query, Council debate, General Mission, AI red team.',
    why: 'AI-native SOC.',
    when: 'LLM configured.',
    where: '/api/ask · /api/council/*',
    how: 'WEISSMAN_LLM_BASE_URL → POST → audit log.',
    who: 'Senior analyst, admin',
    output: 'AI responses + HITL queue',
  },
  {
    id: 'api-admin',
    title: 'API — Admin & Enterprise',
    prefixes: ['/api/admin', '/api/enterprise', '/api/system', '/api/ceo', '/api/dashboard'],
    what: 'Users, settings, backup, CEO vault, exec KPIs.',
    why: 'Governance + executive view.',
    when: 'admin/CEO roles.',
    where: '/api/admin/* · /api/ceo/*',
    how: 'RBAC-gated endpoints.',
    who: 'Admin, CEO',
    output: 'platform control',
  },
  {
    id: 'api-integrations',
    title: 'API — Integrations & Webhooks',
    prefixes: ['/api/integrations', '/api/webhooks', '/api/playbooks', '/api/ndr', '/api/itdr'],
    what: 'CI webhooks, SOAR playbooks, NDR/ITDR ingest.',
    why: 'Ecosystem fit.',
    when: 'automation phase.',
    where: '/api/playbooks/* · /api/integrations/*',
    how: 'Configure → fire on finding.',
    who: 'DevOps, SOC automation',
    output: 'external actions',
  },
]
