#!/usr/bin/env bash
# Align Grafana + Prometheus UI credentials with WEISSMAN_ADMIN_EMAIL / WEISSMAN_ADMIN_PASSWORD.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if [[ -f .env ]]; then
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi

EMAIL="${WEISSMAN_ADMIN_EMAIL:-admin@localhost}"
PASSWORD="${WEISSMAN_ADMIN_PASSWORD:-}"
GRAFANA_CONTAINER="${WEISSMAN_GRAFANA_CONTAINER:-weissman-cybersecurity-grafana-1}"

if [[ -z "$PASSWORD" ]]; then
  echo "WEISSMAN_ADMIN_PASSWORD is required" >&2
  exit 1
fi

gen_prometheus_web_config() {
  local out="${ROOT}/monitoring/prometheus-web.generated.yml"
  local hash line
  line="$(docker run --rm httpd:2.4-alpine htpasswd -nbBC 12 "$EMAIL" "$PASSWORD")"
  hash="${line#*:}"
  cat >"$out" <<EOF
# Generated by scripts/sync_monitoring_admin.sh — do not commit.
basic_auth_users:
  ${EMAIL}: ${hash}
EOF
  chmod 644 "$out"
  echo "Wrote ${out}"
}

sync_grafana_password() {
  if ! docker ps --format '{{.Names}}' | grep -qx "$GRAFANA_CONTAINER"; then
    echo "Grafana container ${GRAFANA_CONTAINER} not running — skip CLI reset"
    return 0
  fi
  docker exec "$GRAFANA_CONTAINER" grafana-cli admin reset-admin-password "$PASSWORD" >/dev/null
  echo "Grafana admin password synced (login user: admin — set GF_SECURITY_ADMIN_USER=${EMAIL} on fresh installs)"
}

case "${1:-all}" in
  prometheus)
    gen_prometheus_web_config
    ;;
  grafana)
    sync_grafana_password
    ;;
  all)
    gen_prometheus_web_config
    sync_grafana_password
    ;;
  *)
    echo "Usage: $0 [all|grafana|prometheus]" >&2
    exit 1
    ;;
esac
