#!/usr/bin/env node
// sync_doc_metrics.mjs — single source of truth for the platform's headline
// numbers. Computes them from source (never hand-maintained) and writes
// docs/METRICS.md. Run with --check in CI to fail on drift.
//
//   node scripts/sync_doc_metrics.mjs           # regenerate docs/METRICS.md
//   node scripts/sync_doc_metrics.mjs --check    # exit 1 if docs/METRICS.md is stale
//
// Rationale: test/route/migration/engine counts were previously copied by hand
// into README / AGENTS.md / compliance docs and drifted badly (e.g. "≈100 tests"
// vs 1,199 real). Generate them instead.

import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const METRICS_PATH = join(ROOT, 'docs', 'METRICS.md');

function sh(cmd) {
  return execSync(cmd, { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] });
}

// Reuse the canonical engine audit (parses source; already CI-gated).
function engineMetrics() {
  try {
    const out = sh('node scripts/engine_reality_audit.mjs');
    const j = JSON.parse(out);
    const p = j.production || {};
    return {
      total: p.total ?? null,
      real_probe: p.real_probe ?? null,
      distinct_real_implementations: p.distinct_real_implementations ?? null,
      alias: p.alias ?? null,
      agent_required: p.agent_required ?? null,
    };
  } catch {
    return { total: null, real_probe: null, distinct_real_implementations: null, alias: null, agent_required: null };
  }
}

// Count matches of an (extended) regex across the tree, robust to zero matches.
function countMatches(pattern, globPaths) {
  try {
    const out = sh(`grep -rIE --include='*.rs' -h '${pattern}' ${globPaths} | wc -l`);
    return parseInt(out.trim(), 10) || 0;
  } catch {
    return 0;
  }
}

function rustTestCount() {
  // #[test] and #[tokio::test] attributes across the Rust workspace.
  return countMatches('^\\s*#\\[(tokio::)?test\\]', 'fingerprint_engine backend crates fuzz_core');
}

function routeCount() {
  // Axum `.route(` registrations (HTTP surface).
  return countMatches('\\.route\\(', 'fingerprint_engine/src backend');
}

function migrationCount() {
  const trees = [
    join('crates', 'weissman-db', 'migrations'),
    join('fingerprint_engine', 'migrations'),
  ];
  const counts = {};
  for (const t of trees) {
    const abs = join(ROOT, t);
    counts[t] = existsSync(abs)
      ? readdirSync(abs).filter((f) => f.endsWith('.sql')).length
      : 0;
  }
  return counts;
}

function render() {
  const e = engineMetrics();
  const tests = rustTestCount();
  const routes = routeCount();
  const migs = migrationCount();
  const migLines = Object.entries(migs)
    // Third cell is required: the table declares three columns, and a two-cell row is a
    // malformed table (markdownlint MD056) that renders with a missing trailing column.
    .map(([t, n]) => `| Migrations — \`${t}\` | ${n} | \`ls ${t}\` |`)
    .join('\n');

  return `<!-- GENERATED by scripts/sync_doc_metrics.mjs — do not edit by hand. Run: node scripts/sync_doc_metrics.mjs -->
# Platform metrics (code-derived)

These numbers are generated from source by \`scripts/sync_doc_metrics.mjs\`.
Do not hand-edit. CI runs \`--check\` to fail the build on drift. Other docs
should link here rather than copying figures.

| Metric | Value | Source of truth |
|--------|-------|-----------------|
| Production engine IDs | ${e.total} | \`scripts/engine_reality_audit.mjs\` |
| — real live probes | ${e.real_probe} | same (${e.distinct_real_implementations} distinct impls) |
| — aliases | ${e.alias} | same |
| — agent-required | ${e.agent_required} | same |
| Rust test fns (\`#[test]\`/\`#[tokio::test]\`) | ${tests} | grep over workspace |
| HTTP route registrations (\`.route(\`) | ${routes} | grep over \`fingerprint_engine/src\` + \`backend\` |
${migLines}

**Reading the engine count honestly:** the ${e.total} catalog IDs resolve to
**${e.distinct_real_implementations} distinct probe implementations** — ${e.alias} are
aliases that re-tag a canonical probe, ${e.agent_required} are agent-required host
techniques, and several "real" IDs delegate to a shared runner (e.g. APT-group
surface profiles). The catalog number reflects breadth of technique coverage, not
${e.total} independent scanners. Every ID still maps to a real execution path
(\`engine_reality_audit.mjs\` fails on any \`no_path\`).

> Verify locally: \`node scripts/sync_doc_metrics.mjs --check\`.
`;
}

const generated = render();

if (process.argv.includes('--check')) {
  const current = existsSync(METRICS_PATH) ? readFileSync(METRICS_PATH, 'utf8') : '';
  if (current.trim() !== generated.trim()) {
    console.error('❌ docs/METRICS.md is stale. Run: node scripts/sync_doc_metrics.mjs');
    console.error('--- expected (from source) ---');
    console.error(generated);
    process.exit(1);
  }
  console.log('✅ docs/METRICS.md is in sync with source.');
} else {
  writeFileSync(METRICS_PATH, generated);
  console.log(`Wrote ${METRICS_PATH}`);
  console.log(generated);
}
