// Route handler implementations split across `.inc` fragments (large blocks).
// This file is `include!`d from `serve.rs` so all handlers share the same module scope
// (`AppState`, auth helpers, `crate::` paths). Only the wiring lives here; review the `.inc` files.

include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_mfa.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_agents.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_onboarding_stub.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_ui_aliases.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_auth.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_sqlx.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_rest.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_rest2.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_rest3.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_rest4.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_engagements.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_evidence_vault.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_saas_idp_discovery.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_roe_approvals.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_phase3.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_phase4.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_phase5.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_phase6.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_phase7.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_onboarding_billing.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_jobs.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_ceo.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/server_handlers_advanced.inc"
));
