[package]
name = "fuzz_core-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.fuzz_core]
path = ".."

[[bin]]
name = "mutate"
path = "fuzz_targets/mutate.rs"
test = false
doc = false
bench = false

[[bin]]
name = "analyze"
path = "fuzz_targets/analyze.rs"
test = false
doc = false
bench = false

[profile.release]
debug = 1

# Detach from the parent Cargo workspace so the main (stable) build never tries to compile
# these nightly-only libFuzzer targets.
[workspace]
