export const GROUP_PARAMS = {
  recon:        [{ key:'stealth_mode',     label:'Stealth Mode',                   type:'select',   options:['off','low','high'], defaultVal:'low' }],
  web:          [{ key:'cookies',          label:'Session Cookies (optional)',      type:'password', placeholder:'session=abc; token=xyz', defaultVal:'' },
                { key:'stealth_mode',     label:'Stealth Mode',                     type:'select',   options:['off','low','high'], defaultVal:'low' }],
  ai:           [{ key:'llm_base_url',     label:'LLM Base URL',                   type:'text',     placeholder:'http://127.0.0.1:11434/v1', defaultVal:'' },
                { key:'llm_model',        label:'LLM Model',                        type:'text',     placeholder:'llama3', defaultVal:'' }],
  cloud:        [{ key:'stealth_mode',     label:'Stealth Mode',                   type:'select',   options:['off','low','high'], defaultVal:'low' }],
  ot:           [{ key:'protocol_strict',  label:'Protocol Strict Mode',           type:'select',   options:['true','false'], defaultVal:'true' }],
  stealth:      [{ key:'stealth_level',    label:'Stealth Level (1-5)',            type:'number',   placeholder:'3', defaultVal:'3', min:1, max:5 }],
  crypto:       [{ key:'stealth_mode',     label:'Stealth Mode',                   type:'select',   options:['off','low','high'], defaultVal:'low' }],
  network:      [{ key:'stealth_mode',     label:'Stealth Mode',                   type:'select',   options:['off','low','high'], defaultVal:'low' },
                { key:'ports',            label:'Port Range',                       type:'text',     placeholder:'1-1024', defaultVal:'1-1024' }],
  supply_chain: [{ key:'deep_scan',        label:'Deep Scan',                      type:'select',   options:['true','false'], defaultVal:'false' }],
  apt:          [{ key:'stealth_level',    label:'Stealth Level (1-5)',            type:'number',   placeholder:'4', defaultVal:'4', min:1, max:5 },
                { key:'techniques_filter',label:'Techniques Filter (MITRE IDs)',    type:'text',     placeholder:'T1566,T1059', defaultVal:'' }],
  malware:      [{ key:'safe_mode',        label:'Safe Mode (no real execution)',  type:'select',   options:['true','false'], defaultVal:'true' }],
  social:       [{ key:'campaign_name',    label:'Campaign Name',                  type:'text',     placeholder:'Red Team', defaultVal:'' }],
  mobile:       [{ key:'platform',         label:'Platform',                       type:'select',   options:['both','android','ios'], defaultVal:'both' }],
  data:         [{ key:'stealth_mode',     label:'Stealth Mode',                   type:'select',   options:['off','low','high'], defaultVal:'low' },
                { key:'max_findings',     label:'Max Findings',                   type:'number',   placeholder:'200', defaultVal:'200', min:1, max:5000 }],
  defense:      [{ key:'intensity',        label:'Scan Intensity',                 type:'select',   options:['light','normal','aggressive'], defaultVal:'normal' },
                { key:'evidence_mode',    label:'Evidence Mode',                  type:'select',   options:['standard','strict','forensic'], defaultVal:'standard' },
                { key:'max_findings',     label:'Max Findings',                   type:'number',   placeholder:'200', defaultVal:'200', min:1, max:5000 }],
}

