/**
 * Master registry of all 253 attack engines.
 *
 * Each engine entry:
 *   id           — backend engine identifier (used in API calls)
 *   label        — human-readable display name
 *   group        — one of ENGINE_GROUPS keys
 *   mitre        — primary MITRE ATT&CK technique ID
 *   description  — one-line description shown on engine card
 *   requiresTarget — whether a domain/URL is required to run this engine
 */

export const ENGINE_GROUP_DEFS = [
  { id: 'recon',        label: 'Recon & OSINT',       color: '#06b6d4' },
  { id: 'web',          label: 'Web / API',            color: '#8b5cf6' },
  { id: 'ai',           label: 'AI / LLM',             color: '#ec4899' },
  { id: 'cloud',        label: 'Cloud / Infra',        color: '#3b82f6' },
  { id: 'ot',           label: 'OT / ICS / IoT',       color: '#f59e0b' },
  { id: 'stealth',      label: 'Stealth / Evasion',    color: '#6366f1' },
  { id: 'crypto',       label: 'Crypto / Identity',    color: '#10b981' },
  { id: 'network',      label: 'Network / Protocol',   color: '#f97316' },
  { id: 'supply_chain', label: 'Supply Chain',         color: '#84cc16' },
  { id: 'apt',          label: 'APT / Top-Tier',       color: '#ef4444' },
]

/** Flat map of groupId → group definition for quick lookup */
export const ENGINE_GROUPS = Object.fromEntries(ENGINE_GROUP_DEFS.map((g) => [g.id, g]))

/** All 253 engines in registry order */
export const ENGINES_REGISTRY = [
  // ── GROUP 1: Recon & OSINT ──────────────────────────────────────────────────
  {
    id: 'osint',
    label: 'OSINT',
    group: 'recon',
    mitre: 'T1589',
    description: 'Open-source intelligence gathering across all public data sources',
    requiresTarget: true,
  },
  {
    id: 'asm',
    label: 'ASM',
    group: 'recon',
    mitre: 'T1595',
    description: 'Attack Surface Management — enumerate all internet-exposed assets',
    requiresTarget: true,
  },
  {
    id: 'leak_hunter',
    label: 'Leak Hunter',
    group: 'recon',
    mitre: 'T1530',
    description: 'Dark web & paste-site credential and data leak detection',
    requiresTarget: true,
  },
  {
    id: 'discovery_engine',
    label: 'Discovery Engine',
    group: 'recon',
    mitre: 'T1046',
    description: 'Automated service and endpoint discovery via passive and active probing',
    requiresTarget: true,
  },
  {
    id: 'recon',
    label: 'Deep Recon',
    group: 'recon',
    mitre: 'T1592',
    description: 'Comprehensive host, domain, WHOIS, and certificate reconnaissance',
    requiresTarget: true,
  },

  // ── GROUP 2: Web / API ───────────────────────────────────────────────────────
  {
    id: 'bola_idor',
    label: 'BOLA / IDOR',
    group: 'web',
    mitre: 'T1548',
    description: 'Broken Object-Level Authorization and Insecure Direct Object Reference attacks',
    requiresTarget: true,
  },
  {
    id: 'graphql_attack',
    label: 'GraphQL Attack',
    group: 'web',
    mitre: 'T1190',
    description: 'Introspection abuse, query depth-limit bypass, batching amplification',
    requiresTarget: true,
  },
  {
    id: 'jwt_attack',
    label: 'JWT Attack',
    group: 'web',
    mitre: 'T1550.001',
    description: 'alg:none bypass, key confusion, weak-secret brute-force, header injection',
    requiresTarget: true,
  },
  {
    id: 'oauth_oidc',
    label: 'OAuth / OIDC',
    group: 'web',
    mitre: 'T1550.001',
    description: 'Authorization code flow hijacking, PKCE bypass, open redirect abuse',
    requiresTarget: true,
  },
  {
    id: 'http_smuggling',
    label: 'HTTP Smuggling',
    group: 'web',
    mitre: 'T1190',
    description: 'CL.TE / TE.CL request smuggling, desync attacks, cache poisoning chains',
    requiresTarget: true,
  },
  {
    id: 'prototype_pollution',
    label: 'Prototype Pollution',
    group: 'web',
    mitre: 'T1059.007',
    description: 'Server-side prototype pollution via JSON merge, query params, body keys',
    requiresTarget: true,
  },
  {
    id: 'ssrf_advanced',
    label: 'SSRF Advanced',
    group: 'web',
    mitre: 'T1190',
    description: 'Multi-hop SSRF, cloud metadata exfil, DNS rebinding, open redirect chains',
    requiresTarget: true,
  },
  {
    id: 'xxe',
    label: 'XXE',
    group: 'web',
    mitre: 'T1190',
    description: 'XML External Entity injection via DTD, parameter entities, out-of-band channels',
    requiresTarget: true,
  },
  {
    id: 'ssti',
    label: 'SSTI',
    group: 'web',
    mitre: 'T1190',
    description: 'Server-Side Template Injection across Jinja2, Twig, Freemarker, Handlebars',
    requiresTarget: true,
  },
  {
    id: 'file_upload',
    label: 'File Upload',
    group: 'web',
    mitre: 'T1190',
    description: 'Polyglot bypass, extension confusion, MIME-type mismatch, path traversal upload',
    requiresTarget: true,
  },
  {
    id: 'websocket_attack',
    label: 'WebSocket Attack',
    group: 'web',
    mitre: 'T1071.001',
    description: 'Origin spoofing, WS injection, race conditions, hijacking via CSRF',
    requiresTarget: true,
  },
  {
    id: 'cache_poisoning',
    label: 'Cache Poisoning',
    group: 'web',
    mitre: 'T1557',
    description: 'Web cache deception, unkeyed header poisoning, CDN edge cache manipulation',
    requiresTarget: true,
  },

  // ── GROUP 3: AI / LLM ────────────────────────────────────────────────────────
  {
    id: 'llm_path_fuzz',
    label: 'LLM Path Fuzz',
    group: 'ai',
    mitre: 'T1190',
    description: 'LLM-generated endpoint path fuzzing tailored to detected tech stack',
    requiresTarget: true,
  },
  {
    id: 'semantic_ai_fuzz',
    label: 'Semantic AI Fuzz',
    group: 'ai',
    mitre: 'T1059',
    description: 'Semantically-aware fuzzing using language models to infer application logic',
    requiresTarget: true,
  },
  {
    id: 'ai_adversarial_redteam',
    label: 'AI Adversarial Red Team',
    group: 'ai',
    mitre: 'T1059',
    description: 'Adversarial prompt injection, jailbreak, and model output manipulation',
    requiresTarget: true,
  },
  {
    id: 'llm_redteam',
    label: 'LLM Red Team',
    group: 'ai',
    mitre: 'T1059',
    description: 'Structured LLM red-teaming: role confusion, data leakage, context overflow',
    requiresTarget: true,
  },
  {
    id: 'adversarial_ml',
    label: 'Adversarial ML',
    group: 'ai',
    mitre: 'T1562',
    description: 'Evasion attacks against ML-based WAF, IDS, and anomaly detection models',
    requiresTarget: true,
  },
  {
    id: 'autonomous_pentest',
    label: 'Autonomous Pentest',
    group: 'ai',
    mitre: 'T1595',
    description: 'Fully autonomous multi-step penetration test orchestrated by AI planner',
    requiresTarget: true,
  },

  // ── GROUP 4: Cloud / Infra ───────────────────────────────────────────────────
  {
    id: 'aws_attack',
    label: 'AWS Attack',
    group: 'cloud',
    mitre: 'T1580',
    description: 'IAM privilege escalation, S3 bucket exposure, Lambda event injection',
    requiresTarget: false,
  },
  {
    id: 'azure_attack',
    label: 'Azure Attack',
    group: 'cloud',
    mitre: 'T1580',
    description: 'Azure AD token abuse, Blob SAS exposure, Function App command injection',
    requiresTarget: false,
  },
  {
    id: 'gcp_attack',
    label: 'GCP Attack',
    group: 'cloud',
    mitre: 'T1580',
    description: 'GCP service account key exposure, Cloud Run abuse, IAM over-permission scan',
    requiresTarget: false,
  },
  {
    id: 'k8s_container',
    label: 'K8s Container',
    group: 'cloud',
    mitre: 'T1610',
    description: 'Kubernetes RBAC misconfig, privileged pod escape, API server exposure',
    requiresTarget: false,
  },
  {
    id: 'iac_misconfig',
    label: 'IaC Misconfig',
    group: 'cloud',
    mitre: 'T1059',
    description: 'Terraform, CloudFormation, Pulumi misconfiguration and drift detection',
    requiresTarget: false,
  },
  {
    id: 'serverless_attack',
    label: 'Serverless Attack',
    group: 'cloud',
    mitre: 'T1648',
    description: 'Serverless event injection, function chaining, cold-start timing attacks',
    requiresTarget: true,
  },

  // ── GROUP 5: OT / ICS / IoT ──────────────────────────────────────────────────
  {
    id: 'scada_ics',
    label: 'SCADA / ICS',
    group: 'ot',
    mitre: 'T0855',
    description: 'Modbus, DNP3, IEC 61850 protocol fuzzing and unauthorized command detection',
    requiresTarget: true,
  },
  {
    id: 'iot_firmware',
    label: 'IoT Firmware',
    group: 'ot',
    mitre: 'T1542',
    description: 'Firmware extraction, hardcoded credential detection, update stream hijacking',
    requiresTarget: true,
  },
  {
    id: 'ble_rf',
    label: 'BLE / RF',
    group: 'ot',
    mitre: 'T1011',
    description: 'Bluetooth LE pairing bypass, RF replay attacks, spectrum analysis',
    requiresTarget: false,
  },

  // ── GROUP 6: Stealth / Evasion ────────────────────────────────────────────────
  {
    id: 'edr_evasion',
    label: 'EDR Evasion',
    group: 'stealth',
    mitre: 'T1562.001',
    description: 'Endpoint detection bypass via process hollowing, AMSI patching, syscall proxying',
    requiresTarget: false,
  },
  {
    id: 'waf_bypass',
    label: 'WAF Bypass',
    group: 'stealth',
    mitre: 'T1027',
    description: 'WAF rule evasion via encoding, chunking, Unicode normalization, payload mutation',
    requiresTarget: true,
  },
  {
    id: 'timing_sidechannel',
    label: 'Timing Side-Channel',
    group: 'stealth',
    mitre: 'T1600',
    description: 'Microsecond-precision timing attacks against auth, crypto, and rate limiters',
    requiresTarget: true,
  },
  {
    id: 'antiforensics',
    label: 'Anti-Forensics',
    group: 'stealth',
    mitre: 'T1070',
    description: 'Log tampering, timestomping, artifact deletion, and evidence destruction sim',
    requiresTarget: false,
  },
  {
    id: 'stealth_engine',
    label: 'Stealth Engine',
    group: 'stealth',
    mitre: 'T1027',
    description: 'Covert channel operations: DNS tunneling, ICMP exfil, low-and-slow scanning',
    requiresTarget: true,
  },

  // ── GROUP 7: Crypto / Identity ────────────────────────────────────────────────
  {
    id: 'pki_tls',
    label: 'PKI / TLS',
    group: 'crypto',
    mitre: 'T1557.002',
    description: 'Certificate transparency abuse, weak cipher enumeration, TLS downgrade',
    requiresTarget: true,
  },
  {
    id: 'pqc_scanner',
    label: 'PQC Scanner',
    group: 'crypto',
    mitre: 'T1600',
    description: 'Post-quantum readiness: RSA key size, algorithm inventory, NIST PQC gap',
    requiresTarget: true,
  },
  {
    id: 'password_spray',
    label: 'Password Spray',
    group: 'crypto',
    mitre: 'T1110.003',
    description: 'Low-rate distributed password spraying against SSO, OWA, ADFS, M365',
    requiresTarget: true,
  },
  {
    id: 'kerberoasting',
    label: 'Kerberoasting',
    group: 'crypto',
    mitre: 'T1558.003',
    description: 'Service principal name enumeration and TGS ticket offline cracking',
    requiresTarget: true,
  },
  {
    id: 'saml_attack',
    label: 'SAML Attack',
    group: 'crypto',
    mitre: 'T1550.004',
    description: 'XML Signature Wrapping, metadata exposure, SHA-1 weak signature detection',
    requiresTarget: true,
  },
  {
    id: 'crypto_engine',
    label: 'Crypto Engine',
    group: 'crypto',
    mitre: 'T1600',
    description: 'Cipher suite analysis, padding oracle, ECB mode detection, entropy audit',
    requiresTarget: true,
  },

  // ── GROUP 8: Network / Protocol ───────────────────────────────────────────────
  {
    id: 'bgp_dns_hijacking',
    label: 'BGP / DNS Hijacking',
    group: 'network',
    mitre: 'T1584.005',
    description: 'DNS resolver discrepancy (DoH vs DoG), BGP prefix hijack via RIPE API',
    requiresTarget: true,
  },
  {
    id: 'ipv6_attack',
    label: 'IPv6 Attack',
    group: 'network',
    mitre: 'T1018',
    description: 'AAAA record enumeration, link-local leak detection, IPv6 RA flood surface',
    requiresTarget: true,
  },
  {
    id: 'mtls_grpc',
    label: 'mTLS / gRPC',
    group: 'network',
    mitre: 'T1552',
    description: 'gRPC reflection abuse, missing client-cert enforcement, mTLS cert validation',
    requiresTarget: true,
  },
  {
    id: 'smb_netbios',
    label: 'SMB / NetBIOS',
    group: 'network',
    mitre: 'T1021.002',
    description: 'TCP port 445/139/137 exposure, EternalBlue/SMBGhost CVE surface mapping',
    requiresTarget: true,
  },

  // ── GROUP 9: Supply Chain ─────────────────────────────────────────────────────
  {
    id: 'supply_chain',
    label: 'Supply Chain',
    group: 'supply_chain',
    mitre: 'T1195',
    description: 'Third-party dependency and vendor supply chain compromise detection',
    requiresTarget: true,
  },
  {
    id: 'cicd_pipeline',
    label: 'CI/CD Pipeline',
    group: 'supply_chain',
    mitre: 'T1195.002',
    description: 'Unauthenticated ArgoCD, Jenkins, GitLab CI, Azure DevOps API exposure',
    requiresTarget: true,
  },
  {
    id: 'container_registry',
    label: 'Container Registry',
    group: 'supply_chain',
    mitre: 'T1525',
    description: 'DockerHub org exposure, ECR public gallery, /v2/_catalog unauthorized listing',
    requiresTarget: true,
  },
  {
    id: 'sbom_analyzer',
    label: 'SBOM Analyzer',
    group: 'supply_chain',
    mitre: 'T1195.001',
    description: 'CycloneDX/SPDX/lockfile exposure scan with inline CVE pattern matching',
    requiresTarget: true,
  },
  {
    id: 'typosquatting_monitor',
    label: 'Typosquatting Monitor',
    group: 'supply_chain',
    mitre: 'T1195.001',
    description: 'Levenshtein typo generation and NPM/PyPI package impersonation detection',
    requiresTarget: true,
  },

  // ── GROUP 10: APT / Top-Tier ─────────────────────────────────────────────────
  {
    id: 'kill_chain',
    label: 'Kill Chain',
    group: 'apt',
    mitre: 'T1210',
    description: 'Full Cyber Kill Chain execution across Recon → Exfiltration phases',
    requiresTarget: true,
  },
  {
    id: 'oast_oob',
    label: 'OAST / OOB',
    group: 'apt',
    mitre: 'T1071',
    description: 'Out-of-band callbacks via Log4Shell JNDI, blind XSS, XXE, SSRF canaries',
    requiresTarget: true,
  },
  {
    id: 'deception_honeypot',
    label: 'Deception Honeypot',
    group: 'apt',
    mitre: 'T1219',
    description: 'Honeypot detection heuristics, canary token exposure, fake asset fingerprint',
    requiresTarget: true,
  },
  {
    id: 'digital_twin',
    label: 'Digital Twin',
    group: 'apt',
    mitre: 'T1588',
    description: 'Environment simulation with XSS, SQLi, MITM, CORS attack path modeling',
    requiresTarget: true,
  },
  {
    id: 'zero_day_prediction',
    label: 'Zero-Day Prediction',
    group: 'apt',
    mitre: 'T1212',
    description: 'Component fingerprint + historical CVE frequency + live NVD feed analysis',
    requiresTarget: false,
  },
  {
    id: 'threat_emulation',
    label: 'APT Threat Emulation',
    group: 'apt',
    mitre: 'T1583',
    description: 'Nation-state TTP emulation: Lazarus, APT28/29/41, Sandworm, Kimsuky, Equation',
    requiresTarget: true,
  },
  {
    id: 'poe_synthesis',
    label: 'PoE Synthesis',
    group: 'apt',
    mitre: 'T1588',
    description: 'Proof-of-Exploitation synthesis — AI-generated PoC from raw findings',
    requiresTarget: true,
  },

  // ── GROUP 10 (continued): APT / Top-Tier — 20 elite additions ────────────────
  {
    id: 'rce_chain',
    label: 'RCE Chain',
    group: 'apt',
    mitre: 'T1203',
    description: 'Multi-vector Remote Code Execution via deserialization, EL injection, shell metacharacter chains',
    requiresTarget: true,
  },
  {
    id: 'active_directory',
    label: 'Active Directory Attack',
    group: 'apt',
    mitre: 'T1558',
    description: 'DCSync, Pass-the-Hash, Golden/Silver Ticket, NTLM relay, AS-REP Roasting, BloodHound path abuse',
    requiresTarget: true,
  },
  {
    id: 'c2_emulation',
    label: 'C2 Framework Emulation',
    group: 'apt',
    mitre: 'T1071.001',
    description: 'Cobalt Strike Beacon, Sliver, Mythic, Havoc C2 simulation — beacon detection and listener fingerprinting',
    requiresTarget: false,
  },
  {
    id: 'ransomware_emulation',
    label: 'Ransomware Emulation',
    group: 'apt',
    mitre: 'T1486',
    description: 'Ransomware TTP emulation: staged encryption, shadow-copy wipe, ransom note delivery, backup deletion',
    requiresTarget: false,
  },
  {
    id: 'lateral_movement',
    label: 'Lateral Movement',
    group: 'network',
    mitre: 'T1021',
    description: 'WMI/DCOM, PsExec, SSH key reuse, RDP hijacking, token impersonation, credential re-spray',
    requiresTarget: true,
  },
  {
    id: 'data_exfiltration',
    label: 'Data Exfiltration',
    group: 'stealth',
    mitre: 'T1048',
    description: 'Multi-channel covert exfiltration: DNS-over-HTTPS tunnelling, ICMP covert, SMTP, S3 presigned URL',
    requiresTarget: true,
  },
  {
    id: 'memory_corruption',
    label: 'Memory Corruption',
    group: 'apt',
    mitre: 'T1203',
    description: 'Heap spray, use-after-free, ROP-chain detection, format-string, and integer overflow surface mapping',
    requiresTarget: true,
  },
  {
    id: 'browser_exploitation',
    label: 'Browser Exploitation',
    group: 'apt',
    mitre: 'T1189',
    description: 'JS engine RCE chains, sandbox escape, drive-by download emulation, renderer exploit surface',
    requiresTarget: true,
  },
  {
    id: 'deepfake_genai',
    label: 'Deepfake / GenAI Attack',
    group: 'ai',
    mitre: 'T1566',
    description: 'AI-generated deepfake voice/video phishing, synthetic identity creation, vishing simulation',
    requiresTarget: false,
  },
  {
    id: 'zero_trust_bypass',
    label: 'Zero Trust Bypass',
    group: 'stealth',
    mitre: 'T1078',
    description: 'Conditional access bypass, device-posture spoofing, MFA fatigue bombing, token exfiltration',
    requiresTarget: true,
  },
  {
    id: 'container_escape',
    label: 'Container Escape',
    group: 'cloud',
    mitre: 'T1611',
    description: 'Docker socket abuse, privileged container breakout, cgroups v1/v2 escape, host PID namespace takeover',
    requiresTarget: false,
  },
  {
    id: 'wireless_attack',
    label: 'Wireless Attack',
    group: 'network',
    mitre: 'T1465',
    description: 'WiFi PMKID cracking, 802.11 deauth flood, evil-twin AP, KRACK replay, WPA2 handshake capture',
    requiresTarget: false,
  },
  {
    id: 'mobile_attack',
    label: 'Mobile Attack',
    group: 'recon',
    mitre: 'T1421',
    description: 'APK reversing, iOS plist credential leak, deep-link hijacking, MDM bypass, mobile OAuth PKCE theft',
    requiresTarget: true,
  },
  {
    id: 'cloud_ransomware',
    label: 'Cloud Ransomware',
    group: 'cloud',
    mitre: 'T1486',
    description: 'S3 object encryption via SSE-C key rotation, RDS snapshot hijacking, Glacier vault lock abuse',
    requiresTarget: false,
  },
  {
    id: 'firmware_exploit',
    label: 'Firmware Exploit',
    group: 'ot',
    mitre: 'T1542.001',
    description: 'UART/JTAG boot extraction, secure-boot bypass, bootloader signature spoofing, OTA update hijacking',
    requiresTarget: true,
  },
  {
    id: 'dns_rebinding',
    label: 'DNS Rebinding',
    group: 'network',
    mitre: 'T1557',
    description: 'Same-origin policy bypass via DNS rebind, intranet pivot, browser-as-proxy, rebind-SSRF chaining',
    requiresTarget: true,
  },
  {
    id: 'physical_security',
    label: 'Physical Security Emulation',
    group: 'stealth',
    mitre: 'T1200',
    description: 'RFID/NFC badge clone detection, HID proximity card analysis, physical intrusion path mapping',
    requiresTarget: false,
  },
  {
    id: 'vuln_chaining',
    label: 'Vuln Chain Synthesis',
    group: 'apt',
    mitre: 'T1210',
    description: 'Multi-CVE exploit chain synthesis: N-day stacking, CVSS-weighted kill-path scoring, auto-PoC linking',
    requiresTarget: true,
  },
  {
    id: 'sqli_advanced',
    label: 'Advanced SQLi',
    group: 'web',
    mitre: 'T1190',
    description: 'Time-based blind, error-based, OOB DNS exfil, second-order SQLi, stored procedure abuse',
    requiresTarget: true,
  },
  {
    id: 'log4shell_scan',
    label: 'Log4Shell / Log4J',
    group: 'apt',
    mitre: 'T1190',
    description: 'CVE-2021-44228 JNDI injection scan across HTTP headers, user-agents, JSON fields, XML payloads',
    requiresTarget: true,
  },

  // ── GROUP 11: Elite 10 — World-Class Attack Engines ──────────────────────────
  {
    id: 'kernel_exploit',
    label: 'Kernel Exploit',
    group: 'apt',
    mitre: 'T1068',
    description: 'Kernel privilege escalation: Dirty Pipe, eBPF program abuse, io_uring UAF, SELinux/AppArmor bypass, SUID chain exploitation',
    requiresTarget: false,
  },
  {
    id: 'credential_stuffing',
    label: 'Credential Stuffing',
    group: 'web',
    mitre: 'T1110.004',
    description: 'Large-scale breach corpus replay, distributed credential stuffing, legacy-protocol MFA bypass (Basic Auth, IMAP, ActiveSync)',
    requiresTarget: true,
  },
  {
    id: 'spear_phishing',
    label: 'Spear Phishing / BEC',
    group: 'recon',
    mitre: 'T1566.002',
    description: 'AI-crafted spear phishing, BEC wire-fraud simulation, SPF/DKIM spoofing, domain lookalike generation, smishing/vishing',
    requiresTarget: true,
  },
  {
    id: 'vlan_bypass',
    label: 'VLAN Bypass',
    group: 'network',
    mitre: 'T1599',
    description: 'VLAN double-tagging (802.1Q/802.1ad), DTP trunk negotiation, native VLAN abuse, inter-VLAN pivot and ARP poisoning',
    requiresTarget: true,
  },
  {
    id: 'malware_persistence',
    label: 'Malware Persistence',
    group: 'stealth',
    mitre: 'T1542.003',
    description: 'Advanced persistence via UEFI bootkit, kernel rootkit implant, COM hijacking, scheduled task/service abuse, boot sector manipulation',
    requiresTarget: false,
  },
  {
    id: 'insider_threat',
    label: 'Insider Threat Emulation',
    group: 'stealth',
    mitre: 'T1078.002',
    description: 'Insider TTP simulation: DLP bypass, excessive-privilege abuse, data staging to cloud storage, shadow-IT and rogue device detection',
    requiresTarget: true,
  },
  {
    id: 'post_exploitation',
    label: 'Post-Exploitation',
    group: 'apt',
    mitre: 'T1003',
    description: 'Automated post-exploitation: LSASS dump, SAM/NTDS.dit extraction, credential cache scraping, privilege-escalation chain enumeration',
    requiresTarget: true,
  },
  {
    id: 'cloud_lateral',
    label: 'Cloud Lateral Movement',
    group: 'cloud',
    mitre: 'T1552.005',
    description: 'Cloud-to-cloud lateral movement: IMDSv1 SSRF, IAM role chaining, cross-account pivot, EC2/GCE instance-profile credential theft',
    requiresTarget: false,
  },
  {
    id: 'process_injection',
    label: 'Process Injection',
    group: 'stealth',
    mitre: 'T1055',
    description: 'Advanced process injection: DLL hijacking, reflective loading, process hollowing, APC queue injection, thread hijacking, ghostwriting',
    requiresTarget: false,
  },
  {
    id: 'api_fuzzing',
    label: 'Intelligent API Fuzzing',
    group: 'web',
    mitre: 'T1190',
    description: 'OpenAPI/Swagger-guided API fuzzing: mass assignment, business-logic bypass, rate-limit evasion, hidden endpoint discovery, parameter pollution',
    requiresTarget: true,
  },

  // ── GROUP 12: 30 New Attack Engines ──────────────────────────────────────────
  {
    id: 'smb_relay',
    label: 'SMB / NTLM Relay',
    group: 'network',
    mitre: 'T1557.001',
    description: 'SMB/NTLM relay attacks: NTLMv2 capture, relay-to-LDAP/SMB/HTTP, ADCS ESC8, shadow-credential injection via RBCD',
    requiresTarget: true,
  },
  {
    id: 'graphql_injection',
    label: 'GraphQL Injection',
    group: 'web',
    mitre: 'T1190',
    description: 'GraphQL introspection enumeration, query batching abuse, nested query DoS, field-level authorization bypass, alias injection',
    requiresTarget: true,
  },
  {
    id: 'container_k8s_escape',
    label: 'Container / K8s Escape',
    group: 'cloud',
    mitre: 'T1611',
    description: 'Container breakout via privileged mode, runc CVEs, cgroup namespace escape, K8s API server abuse, kubelet exploitation',
    requiresTarget: false,
  },
  {
    id: 'web_cache_poison',
    label: 'Web Cache Poisoning',
    group: 'web',
    mitre: 'T1584',
    description: 'Cache poisoning via unkeyed headers, fat-GET injection, CDN cache-buster bypass, DOM-based cache deception, response splitting',
    requiresTarget: true,
  },
  {
    id: 'xxe_injection',
    label: 'XXE / XML Injection',
    group: 'web',
    mitre: 'T1190',
    description: 'XML External Entity injection: blind OOB exfiltration, DTD-based SSRF pivot, billion-laugh DoS, SVG/DOCX XXE vector exploitation',
    requiresTarget: true,
  },
  {
    id: 'ldap_injection',
    label: 'LDAP / AD Injection',
    group: 'network',
    mitre: 'T1078.002',
    description: 'LDAP injection for authentication bypass, directory enumeration, AD attribute harvesting, Kerberoasting, AS-REP roasting',
    requiresTarget: true,
  },
  {
    id: 'side_channel',
    label: 'Side-Channel Attack',
    group: 'crypto',
    mitre: 'T1600',
    description: 'Timing side-channels on crypto primitives, cache-timing (Flush+Reload), speculative execution leakage, power-analysis emulation',
    requiresTarget: false,
  },
  {
    id: 'ssrf_chain',
    label: 'SSRF Chain Pivot',
    group: 'web',
    mitre: 'T1090.001',
    description: 'SSRF chaining: protocol-scheme confusion (gopher/dict/ftp), IMDS v1 metadata theft, internal-service enumeration, cloud SSRF to RCE',
    requiresTarget: true,
  },
  {
    id: 'jwt_attacks',
    label: 'JWT / Token Attacks',
    group: 'crypto',
    mitre: 'T1552.001',
    description: 'JWT algorithm confusion (RS256→HS256), none-alg bypass, weak secret brute-force, jwk injection, kid header path traversal',
    requiresTarget: true,
  },
  {
    id: 'bgp_hijacking',
    label: 'BGP Route Hijacking',
    group: 'network',
    mitre: 'T1584.005',
    description: 'BGP prefix hijack simulation, RPKI validation bypass, route leak detection, AS-path poisoning, BGP session reset via ICMP',
    requiresTarget: false,
  },
  {
    id: 'rce_deserialization',
    label: 'Deserialization RCE',
    group: 'web',
    mitre: 'T1059',
    description: 'Java/PHP/.NET deserialization gadget chain exploitation: ysoserial payloads, ViewState tampering, Pickle/YAML RCE injection',
    requiresTarget: true,
  },
  {
    id: 'active_directory_enum',
    label: 'Active Directory Enum',
    group: 'recon',
    mitre: 'T1087.002',
    description: 'BloodHound-style AD attack-path mapping: ACL abuse, DCSync simulation, delegation misconfig, AdminSDHolder exploitation, LAPS bypass',
    requiresTarget: true,
  },
  {
    id: 'ransomware_sim',
    label: 'Ransomware Simulation',
    group: 'apt',
    mitre: 'T1486',
    description: 'Ransomware TTP emulation: file enumeration, shadow-copy deletion, encryption key management audit, network-share traversal, ransom-note drop',
    requiresTarget: false,
  },
  {
    id: 'waf_ids_bypass',
    label: 'WAF / IDS Bypass',
    group: 'stealth',
    mitre: 'T1562.001',
    description: 'WAF fingerprinting and evasion: unicode normalization, chunked encoding tricks, header injection, HTTP/2 cleartext, regex de-anchoring',
    requiresTarget: true,
  },
  {
    id: 'siem_evasion',
    label: 'SIEM Log Evasion',
    group: 'stealth',
    mitre: 'T1562.006',
    description: 'SIEM/EDR evasion: event log tampering, Sysmon rule bypass, ETW provider disabling, audit-policy manipulation, log rotation abuse',
    requiresTarget: false,
  },
  {
    id: 'mobile_pentest',
    label: 'Mobile App Pentest',
    group: 'web',
    mitre: 'T1421',
    description: 'iOS/Android app security: insecure data storage, deeplink hijacking, certificate pinning bypass, WebView XSS, intent redirection',
    requiresTarget: true,
  },
  {
    id: 'cors_exploit',
    label: 'CORS Misconfiguration',
    group: 'web',
    mitre: 'T1539',
    description: 'CORS origin-reflection bypass, null-origin exploit, wildcard credential leakage, pre-flight abuse, cross-origin cookie harvesting',
    requiresTarget: true,
  },
  {
    id: 'js_prototype_pollution',
    label: 'Prototype Pollution',
    group: 'web',
    mitre: 'T1059.007',
    description: 'Server-side and client-side JavaScript prototype pollution: gadget chain to RCE via lodash/jQuery, template injection escalation',
    requiresTarget: true,
  },
  {
    id: 'ipsec_vpn_audit',
    label: 'IPSec / VPN Audit',
    group: 'network',
    mitre: 'T1133',
    description: 'VPN configuration audit: IKEv1/v2 aggressive-mode fingerprint, weak cipher enumeration, split-tunnel bypass, EAP credential capture',
    requiresTarget: true,
  },
  {
    id: '5g_security',
    label: '5G / Cellular Security',
    group: 'network',
    mitre: 'T1040',
    description: 'Cellular network assessment: IMSI catcher simulation, NAS signaling fuzzing, GTP-U tunnel hijacking, 5G slice isolation bypass',
    requiresTarget: false,
  },
  {
    id: 'firmware_emulation',
    label: 'Firmware Emulation',
    group: 'ot',
    mitre: 'T1542',
    description: 'Firmware extraction and QEMU-based emulation: hardcoded credential extraction, debug interface discovery, binary diffing for N-days',
    requiresTarget: false,
  },
  {
    id: 'cloud_storage_audit',
    label: 'Cloud Storage Audit',
    group: 'cloud',
    mitre: 'T1530',
    description: 'S3/GCS/Azure Blob misconfiguration: unauthenticated bucket listing, ACL bypass, presigned URL abuse, object versioning data recovery',
    requiresTarget: false,
  },
  {
    id: 'llm_jailbreak',
    label: 'LLM Jailbreak / Prompt Extraction',
    group: 'ai',
    mitre: 'T1059',
    description: 'LLM jailbreak techniques: system-prompt extraction, role-play injection, indirect prompt injection via RAG, training data reconstruction',
    requiresTarget: true,
  },
  {
    id: 'devsecops_scan',
    label: 'CI/CD Pipeline Attack',
    group: 'supply_chain',
    mitre: 'T1195.002',
    description: 'CI/CD security: poisoned pipeline execution, secret leakage from env vars, GitHub Actions workflow injection, artifact registry tampering',
    requiresTarget: true,
  },
  {
    id: 'wasm_reverse',
    label: 'WebAssembly Reverse Engineering',
    group: 'stealth',
    mitre: 'T1027.002',
    description: 'WASM binary reverse engineering: obfuscated logic extraction, anti-debug bypass, hidden API key recovery, memory-layout side-channel',
    requiresTarget: true,
  },
  {
    id: 'bluetooth_attack',
    label: 'Bluetooth / BLE Attack',
    group: 'network',
    mitre: 'T1011.001',
    description: 'Bluetooth and BLE attack suite: BLESA spoofing, BIAS authentication bypass, BLE MITM, HID injection, proximity-based device enumeration',
    requiresTarget: false,
  },
  {
    id: 'oauth_abuse',
    label: 'OAuth / OIDC Abuse',
    group: 'crypto',
    mitre: 'T1550.001',
    description: 'OAuth/OIDC attack chain: authorization-code interception, implicit-flow token theft, state-param CSRF, device-code phishing, token replay',
    requiresTarget: true,
  },
  {
    id: 'heap_exploitation',
    label: 'Heap Exploitation',
    group: 'apt',
    mitre: 'T1203',
    description: 'Heap memory exploitation: use-after-free, tcache poisoning, double-free, heap grooming, ASLR/PIE bypass via heap leak chaining',
    requiresTarget: false,
  },
  {
    id: 'clickjacking',
    label: 'Clickjacking / UI Redress',
    group: 'web',
    mitre: 'T1185',
    description: 'Clickjacking via iframe overlay, X-Frame-Options bypass, CSP frame-ancestors evasion, drag-and-drop exfiltration, double-click hijack',
    requiresTarget: true,
  },
  {
    id: 'email_spoofing',
    label: 'Email Spoofing / DMARC Bypass',
    group: 'recon',
    mitre: 'T1566.001',
    description: 'Email authentication bypass: SPF/DKIM/DMARC misconfiguration, homoglyph lookalike domains, display-name spoofing, ARC chain forgery',
    requiresTarget: true,
  },

  // ── GROUP 13: 31 World-Class Elite Engines ────────────────────────────────────
  {
    id: 'satellite_attack',
    label: 'Satellite / Space Security',
    group: 'network',
    mitre: 'T1498',
    description: 'Satellite link interception, GPS spoofing, Starlink dish exploitation, ground station protocol fuzzing, space-segment downlink hijacking',
    requiresTarget: false,
  },
  {
    id: 'ai_poisoning',
    label: 'AI Training Data Poisoning',
    group: 'ai',
    mitre: 'T1565',
    description: 'ML model supply chain attack: training data manipulation, backdoor injection via poisoned datasets, federated-learning Byzantine attack emulation',
    requiresTarget: false,
  },
  {
    id: 'smart_contract_audit',
    label: 'Smart Contract / Blockchain Exploit',
    group: 'web',
    mitre: 'T1496',
    description: 'Solidity reentrancy, integer overflow, flash loan attacks, front-running MEV exploitation, ERC-20/721 approval drain, oracle manipulation',
    requiresTarget: true,
  },
  {
    id: 'automotive_can_bus',
    label: 'Automotive / CAN Bus Attack',
    group: 'ot',
    mitre: 'T1498',
    description: 'CAN bus frame injection, ECU firmware extraction, OBD-II exploit surface, V2X protocol fuzzing, OTA update MITM, remote keyless entry relay',
    requiresTarget: false,
  },
  {
    id: 'zero_click_exploit',
    label: 'Zero-Click Exploit Emulation',
    group: 'apt',
    mitre: 'T1203',
    description: 'Zero-interaction exploitation: iMessage/NSO Pegasus-style vector analysis, FORCEDENTRY-pattern ImageIO parsing, baseband zero-click surface mapping',
    requiresTarget: true,
  },
  {
    id: 'biometric_spoofing',
    label: 'Biometric Bypass',
    group: 'crypto',
    mitre: 'T1556',
    description: 'Biometric authentication bypass: 3D-printed fingerprint, IR face-liveness defeat, palm/iris presentation attack, voice deepfake auth bypass',
    requiresTarget: false,
  },
  {
    id: 'quantum_attack',
    label: 'Quantum Threat Emulation',
    group: 'crypto',
    mitre: 'T1600',
    description: "Grover's/Shor's algorithm threat modeling against RSA/ECC/AES-128, harvest-now-decrypt-later HNDL attack simulation, quantum-safe migration gap analysis",
    requiresTarget: false,
  },
  {
    id: 'devsecops_secrets',
    label: 'Secrets & Key Exposure',
    group: 'supply_chain',
    mitre: 'T1552.001',
    description: 'Source code secret scanning: hardcoded API keys, AWS credentials, JWT signing secrets in git history, .env file exposure, vault misconfiguration',
    requiresTarget: true,
  },
  {
    id: 'threat_hunting_apt',
    label: 'Threat Hunting Automation',
    group: 'apt',
    mitre: 'T1078',
    description: 'Automated threat hunting: IOC correlation, YARA-rule-based artifact detection, MITRE ATT&CK heat-map generation, anomalous beacon detection',
    requiresTarget: false,
  },
  {
    id: 'cloud_identity_attack',
    label: 'Cloud Identity & IAM Attack',
    group: 'cloud',
    mitre: 'T1078.004',
    description: 'Cloud IAM privilege escalation: assume-role abuse, cross-service confused deputy, service-linked role backdoor, ABAC policy bypass, STS token theft',
    requiresTarget: false,
  },
  {
    id: 'ci_cd_poisoning',
    label: 'Poisoned Pipeline Execution',
    group: 'supply_chain',
    mitre: 'T1195.002',
    description: 'PPE attack variants: direct PPE via forked PR workflow, indirect PPE via poisoned dependencies, 3PP via build tool plugin injection, self-hosted runner compromise',
    requiresTarget: true,
  },
  {
    id: 'llm_agent_hijack',
    label: 'LLM Agent Hijacking',
    group: 'ai',
    mitre: 'T1059',
    description: 'Autonomous AI agent exploitation: indirect prompt injection via tool outputs, memory poisoning, goal hijacking, sandbox escape via code interpreter, MCP server abuse',
    requiresTarget: true,
  },
  {
    id: 'api_gateway_attack',
    label: 'API Gateway / Microservice Attack',
    group: 'web',
    mitre: 'T1190',
    description: 'API gateway bypass: internal service impersonation, JWT-less microservice direct access, service mesh SPIFFE/SVID spoofing, Envoy xDS hijacking',
    requiresTarget: true,
  },
  {
    id: 'deception_evasion',
    label: 'Anti-Deception Evasion',
    group: 'stealth',
    mitre: 'T1497',
    description: 'Sandbox and honeypot evasion: timing-based VM detection, user-interaction checks, hardware fingerprint anomaly bypass, canary token avoidance',
    requiresTarget: false,
  },
  {
    id: 'multi_cloud_pivot',
    label: 'Multi-Cloud Pivot',
    group: 'cloud',
    mitre: 'T1552.005',
    description: 'Cross-cloud lateral movement: AWS-to-GCP federation abuse, Azure Arc exploitation, cross-tenant OAuth token pivot, cloud federation trust chain attack',
    requiresTarget: false,
  },
  {
    id: 'rag_poisoning',
    label: 'RAG / Vector DB Poisoning',
    group: 'ai',
    mitre: 'T1565',
    description: 'Retrieval-Augmented Generation attack: adversarial document injection, embedding space poisoning, context window stuffing, semantic similarity bypass',
    requiresTarget: true,
  },
  {
    id: 'browser_extension_attack',
    label: 'Malicious Browser Extension',
    group: 'web',
    mitre: 'T1176',
    description: 'Browser extension threat: manifest-v3 bypass, cross-origin cookie theft, session token harvest, tab-capture spyware emulation, Chrome DevTools protocol abuse',
    requiresTarget: false,
  },
  {
    id: 'graphene_os_bypass',
    label: 'Mobile OS Hardening Bypass',
    group: 'stealth',
    mitre: 'T1404',
    description: 'Hardened mobile OS bypass: exploit chain against GrapheneOS/CopperheadOS attestation, Android verified-boot bypass, iOS PAC/BTI defeat emulation',
    requiresTarget: false,
  },
  {
    id: 'obfuscated_c2',
    label: 'Obfuscated / Domain-Fronted C2',
    group: 'apt',
    mitre: 'T1090.004',
    description: 'Domain-fronted C2 detection: CDN SNI mismatch, encrypted DNS beacon, Tor/I2P hidden service C2, JA3/JA3S fingerprint evasion, HTTPS certificate impersonation',
    requiresTarget: false,
  },
  {
    id: 'hardware_implant',
    label: 'Hardware Implant / Supply Chain',
    group: 'ot',
    mitre: 'T1195.003',
    description: 'Hardware supply chain attack emulation: PCB-level implant detection, JTAG/SWD debug port enumeration, BIOS/UEFI SPI flash tampering, BMC/iDRAC exploit surface',
    requiresTarget: false,
  },
  {
    id: 'serverless_cold_start',
    label: 'Serverless Cold-Start Race',
    group: 'cloud',
    mitre: 'T1648',
    description: 'Serverless race conditions: function cold-start shared-memory exploitation, concurrent invocation TOCTOU, ephemeral storage credential theft, layer injection',
    requiresTarget: true,
  },
  {
    id: 'multimodal_ai_attack',
    label: 'Multimodal AI Attack',
    group: 'ai',
    mitre: 'T1059',
    description: 'Vision-language model attacks: adversarial patch injection into images, audio transcription jailbreak, video-based prompt injection, CLIP embedding manipulation',
    requiresTarget: true,
  },
  {
    id: 'active_directory_cs',
    label: 'AD Certificate Services Abuse',
    group: 'crypto',
    mitre: 'T1649',
    description: 'ADCS ESC1-8 attack chain: misconfigured certificate templates, NTAuth store manipulation, shadow credentials via PKINIT, certificate persistence (ESC3/ESC7)',
    requiresTarget: true,
  },
  {
    id: 'data_pipeline_attack',
    label: 'Data Pipeline / ETL Attack',
    group: 'supply_chain',
    mitre: 'T1565.001',
    description: 'Data pipeline tampering: Apache Airflow DAG injection, Kafka consumer MITM, dbt model poisoning, Spark job hijacking, stream processing SQL injection',
    requiresTarget: true,
  },
  {
    id: 'exfil_ai_inference',
    label: 'Model Inversion / Exfiltration',
    group: 'ai',
    mitre: 'T1048',
    description: 'AI model exfiltration: membership inference attacks, model stealing via repeated queries, gradient-based training data reconstruction, embedding inversion',
    requiresTarget: true,
  },
  {
    id: 'cloud_waf_bypass',
    label: 'Cloud WAF / Shield Bypass',
    group: 'cloud',
    mitre: 'T1562',
    description: 'AWS Shield/WAF, Azure Front Door, Cloudflare bypass: IP rotation, TLS fingerprint cycling, ALB direct-IP access, origin IP exposure via DNS history',
    requiresTarget: true,
  },
  {
    id: 'telco_ss7_attack',
    label: 'Telecom / SS7 Attack',
    group: 'network',
    mitre: 'T1040',
    description: 'SS7/Diameter/GTP protocol attack emulation: SMS interception, call forwarding hijacking, IMSI tracking, SIM swap fraud path, VoIP toll fraud simulation',
    requiresTarget: false,
  },
  {
    id: 'deepweb_intel',
    label: 'Dark / Deep Web Intelligence',
    group: 'recon',
    mitre: 'T1597',
    description: 'Automated dark-web intelligence gathering: Tor hidden service enumeration, paste-site credential monitoring, ransomware leak site tracking, threat actor profiling',
    requiresTarget: false,
  },
  {
    id: 'network_tap_implant',
    label: 'Network TAP / SPAN Implant',
    group: 'network',
    mitre: 'T1557',
    description: 'Passive network interception emulation: SPAN port misconfiguration, VLAN tapping, ARP poisoning for MITM, passive SSL/TLS session interception, rogue DHCP',
    requiresTarget: false,
  },
  {
    id: 'gitops_attack',
    label: 'GitOps / IaC Drift Attack',
    group: 'supply_chain',
    mitre: 'T1195',
    description: 'GitOps attack surface: ArgoCD app-of-apps injection, Flux image automation abuse, Helm chart dependency confusion, Terraform state file secret exposure',
    requiresTarget: true,
  },
  {
    id: 'compliance_gap_scan',
    label: 'Compliance Gap Scanner',
    group: 'recon',
    mitre: 'T1592',
    description: 'Automated compliance gap analysis: PCI-DSS, HIPAA, SOC2, ISO 27001, GDPR control mapping against discovered assets, misconfiguration to regulation cross-reference',
    requiresTarget: true,
  },

  // ── NEW 100 ENGINES (batch 4) ────────────────────────────────────────────────

  // ── Recon & OSINT ────────────────────────────────────────────────────────────
  {
    id: 'dns_enum',
    label: 'DNS Zone Enumeration',
    group: 'recon',
    mitre: 'T1590.002',
    description: 'Full DNS enumeration: AXFR/IXFR zone transfer, brute-force subdomain discovery, NSEC3 walking, wildcard detection, DNS history pivoting',
    requiresTarget: true,
  },
  {
    id: 'social_media_recon',
    label: 'Social Media OSINT',
    group: 'recon',
    mitre: 'T1593.001',
    description: 'Cross-platform social media intelligence: LinkedIn org-chart extraction, Twitter/X employee discovery, GitHub org member enumeration, Facebook graph search',
    requiresTarget: true,
  },
  {
    id: 'shodan_mass_scan',
    label: 'Shodan / Censys Mass Scan',
    group: 'recon',
    mitre: 'T1595.001',
    description: 'Internet-wide asset discovery via Shodan, Censys, and FOFA: open port mapping, banner grabbing, default credential identification, exposed admin panel detection',
    requiresTarget: false,
  },
  {
    id: 'cert_transparency',
    label: 'Certificate Transparency Mining',
    group: 'recon',
    mitre: 'T1596.003',
    description: 'CT log enumeration for subdomain discovery, SAN certificate mapping, historical certificate pivoting, wildcard cert abuse detection, expired cert takeover',
    requiresTarget: true,
  },
  {
    id: 'email_harvest',
    label: 'Email Address Harvester',
    group: 'recon',
    mitre: 'T1589.002',
    description: 'Automated email harvesting from OSINT sources: Hunter.io, Phonebook.cz, breach databases, corporate domain MX record analysis, email pattern derivation',
    requiresTarget: true,
  },
  {
    id: 'github_recon',
    label: 'GitHub / GitLab OSINT',
    group: 'recon',
    mitre: 'T1593.003',
    description: 'Code repository intelligence: GitHub org member enumeration, hardcoded secret discovery in public commits, internal hostname/API endpoint leakage, gist scraping',
    requiresTarget: true,
  },
  {
    id: 'geoint',
    label: 'Geospatial Intelligence (GEOINT)',
    group: 'recon',
    mitre: 'T1591',
    description: 'Geospatial OSINT: EXIF GPS extraction from public images, satellite imagery analysis, datacenter location mapping, physical access vector identification',
    requiresTarget: false,
  },
  {
    id: 'network_topology_map',
    label: 'Passive Network Topology Mapper',
    group: 'recon',
    mitre: 'T1590.004',
    description: 'Passive network topology reconstruction: BGP route analysis, traceroute-based path mapping, ISP peering identification, CDN origin IP leakage detection',
    requiresTarget: true,
  },
  {
    id: 'employee_profiling',
    label: 'Employee Profiling Engine',
    group: 'recon',
    mitre: 'T1589.003',
    description: 'Deep corporate employee profiling: role/title enumeration, technical stack inference from job posts, personal device BYOD risk scoring, insider threat modeling',
    requiresTarget: true,
  },
  {
    id: 'wayback_recon',
    label: 'Historical Asset Recon',
    group: 'recon',
    mitre: 'T1593',
    description: 'Wayback Machine and CommonCrawl mining: retired endpoint discovery, legacy API key exposure, JavaScript source map recovery, historical credentials in cached pages',
    requiresTarget: true,
  },

  // ── Web / API ────────────────────────────────────────────────────────────────
  {
    id: 'xss_advanced',
    label: 'Advanced XSS Engine',
    group: 'web',
    mitre: 'T1059.007',
    description: 'Comprehensive XSS exploitation: DOM-based, stored, reflected, mutation-based, polyglot payload bypass, CSP bypass techniques, XSS-to-account-takeover chain',
    requiresTarget: true,
  },
  {
    id: 'csrf_exploit',
    label: 'CSRF Token Bypass',
    group: 'web',
    mitre: 'T1185',
    description: 'CSRF attack vectors: token prediction, SameSite bypass, subdomain-based origin confusion, flash-based CSRF, multipart CSRF, SPA-specific state forgery',
    requiresTarget: true,
  },
  {
    id: 'path_traversal',
    label: 'Path Traversal / LFI / RFI',
    group: 'web',
    mitre: 'T1083',
    description: 'Directory traversal exploitation: LFI-to-RCE via log poisoning, PHP wrapper chains, ZIP slip, null byte injection, Unicode normalization bypass, RFI via DNS rebinding',
    requiresTarget: true,
  },
  {
    id: 'business_logic_flaw',
    label: 'Business Logic Vulnerability',
    group: 'web',
    mitre: 'T1548',
    description: 'Business logic exploitation: price manipulation, quantity rollover, coupon abuse, account enumeration via timing difference, workflow state machine bypass',
    requiresTarget: true,
  },
  {
    id: 'race_condition_web',
    label: 'Web Race Condition (TOCTOU)',
    group: 'web',
    mitre: 'T1499.003',
    description: 'HTTP-level race condition exploitation: single-packet attack, limit overrun, TOCTOU in payment flows, concurrent request state corruption, Turbo Intruder automation',
    requiresTarget: true,
  },
  {
    id: 'oauth_pkce_attack',
    label: 'OAuth 2.0 / PKCE Attack',
    group: 'web',
    mitre: 'T1550.001',
    description: 'OAuth 2.0 advanced attacks: PKCE code_verifier downgrade, authorization code interception, redirect_uri bypass, nonce reuse, refresh token theft, implicit flow leak',
    requiresTarget: true,
  },
  {
    id: 'mass_assignment',
    label: 'Mass Assignment / HPP',
    group: 'web',
    mitre: 'T1190',
    description: 'Mass assignment and HTTP parameter pollution: JSON body parameter injection, hidden admin fields, privilege escalation via unprotected fields, HPP query-string override',
    requiresTarget: true,
  },
  {
    id: 'web_cache_deception',
    label: 'Web Cache Deception',
    group: 'web',
    mitre: 'T1185',
    description: 'Cache deception attacks: path confusion to cache authenticated responses, CDN cache key manipulation, response header injection for cache poisoning, URL normalization abuse',
    requiresTarget: true,
  },
  {
    id: 'api_versioning_attack',
    label: 'Shadow / Deprecated API Attack',
    group: 'web',
    mitre: 'T1190',
    description: 'Hidden and deprecated API exploitation: version enumeration (v0/v1/beta), undocumented admin endpoint discovery, changelog-based endpoint reconstruction, WSDL/Swagger leakage',
    requiresTarget: true,
  },
  {
    id: 'nosql_injection',
    label: 'NoSQL Injection Engine',
    group: 'web',
    mitre: 'T1190',
    description: 'NoSQL injection exploitation: MongoDB operator injection ($where, $regex), CouchDB Mango query bypass, Redis command injection, Elasticsearch DSL injection, Cassandra CQL injection',
    requiresTarget: true,
  },
  {
    id: 'deserialization_java',
    label: 'Java Deserialization Gadget Chain',
    group: 'web',
    mitre: 'T1059',
    description: 'Java deserialization RCE: ysoserial gadget chain generation, CommonsCollections exploits, Spring/Struts deserialization, XStream XML deserialization, JMX RMI exploitation',
    requiresTarget: true,
  },
  {
    id: 'open_redirect',
    label: 'Open Redirect Chain',
    group: 'web',
    mitre: 'T1190',
    description: 'Open redirect exploitation chain: phishing pre-text, OAuth redirect_uri bypass, SSRF amplification via trusted redirect, browser history manipulation',
    requiresTarget: true,
  },
  {
    id: 'host_header_injection',
    label: 'Host Header Injection',
    group: 'web',
    mitre: 'T1190',
    description: 'HTTP Host header attacks: cache poisoning via X-Forwarded-Host, password reset poisoning, routing-based SSRF, absolute URL injection, virtual host confusion',
    requiresTarget: true,
  },
  {
    id: 'cors_misconfiguration',
    label: 'CORS Misconfiguration Exploit',
    group: 'web',
    mitre: 'T1185',
    description: 'CORS misconfiguration exploitation: null origin bypass, trusted subdomain pivot, wildcard with credentials, Vary header cache poisoning via CORS, pre-flight bypass',
    requiresTarget: true,
  },
  {
    id: 'graphql_batching',
    label: 'GraphQL Batching / DoS',
    group: 'web',
    mitre: 'T1499',
    description: 'GraphQL attack vectors: query batching for rate-limit bypass, deep recursive query DoS, field suggestion enumeration, introspection-based schema mapping, alias brute-force',
    requiresTarget: true,
  },

  // ── AI / LLM ─────────────────────────────────────────────────────────────────
  {
    id: 'ai_model_backdoor',
    label: 'AI Model Backdoor / Trojan',
    group: 'ai',
    mitre: 'T1195.001',
    description: 'Neural network trojan insertion: BadNets trigger implantation, latent-space backdoor via fine-tuning, model card poisoning, ONNX model tampering, torchscript backdoor',
    requiresTarget: false,
  },
  {
    id: 'llm_context_overflow',
    label: 'LLM Context Window Overflow',
    group: 'ai',
    mitre: 'T1499',
    description: 'Context window manipulation: token flooding to displace system prompt, attention dilution attack, long-context hallucination induction, context confusion between sessions',
    requiresTarget: true,
  },
  {
    id: 'ai_supply_chain',
    label: 'AI/ML Supply Chain Attack',
    group: 'ai',
    mitre: 'T1195',
    description: 'ML supply chain exploitation: malicious HuggingFace model injection, PyPI/conda ML package typosquatting, pickle deserialization in model loading, ONNX model RCE',
    requiresTarget: false,
  },
  {
    id: 'adversarial_image',
    label: 'Adversarial Image Attack',
    group: 'ai',
    mitre: 'T1036',
    description: 'Computer vision adversarial attacks: FGSM/PGD perturbation for classifier evasion, patch-based physical adversarial examples, style-transfer-based camouflage, deepfake detection bypass',
    requiresTarget: false,
  },
  {
    id: 'llm_dos',
    label: 'LLM Resource Exhaustion',
    group: 'ai',
    mitre: 'T1499.004',
    description: 'LLM denial-of-service: sponge example token amplification, repetition loop injection, recursive self-reference prompt, token budget exhaustion, concurrent API flooding',
    requiresTarget: true,
  },
  {
    id: 'llm_privacy_leak',
    label: 'LLM Training Data Extraction',
    group: 'ai',
    mitre: 'T1530',
    description: 'Membership inference and data extraction: verbatim training data recall prompts, differential privacy leakage measurement, canary string extraction, PII reconstruction from embeddings',
    requiresTarget: true,
  },
  {
    id: 'ai_watermark_bypass',
    label: 'AI Watermark / Fingerprint Removal',
    group: 'ai',
    mitre: 'T1036',
    description: 'AI output watermark defeat: paraphrase-based watermark removal, statistical watermark detection and stripping, model fingerprint evasion, semantic-preserving adversarial rewriting',
    requiresTarget: false,
  },
  {
    id: 'agentic_ai_escape',
    label: 'Agentic AI Sandbox Escape',
    group: 'ai',
    mitre: 'T1611',
    description: 'AI agent tool abuse: code interpreter sandbox escape via subprocess, file system exfiltration through tool calls, MCP server privilege abuse, agent goal hijacking via environment manipulation',
    requiresTarget: true,
  },
  {
    id: 'llm_system_prompt_leak',
    label: 'System Prompt Extraction',
    group: 'ai',
    mitre: 'T1530',
    description: 'System prompt leakage: direct prompt disclosure via roleplay, token-by-token probability extraction, many-shot jailbreak for prompt revelation, cross-conversation context leakage',
    requiresTarget: true,
  },
  {
    id: 'ai_bias_exploit',
    label: 'AI Bias / Fairness Exploitation',
    group: 'ai',
    mitre: 'T1565',
    description: 'Exploiting ML model bias: demographic parity bypass for access control evasion, adversarial query crafting to trigger biased decisions, audit trail manipulation via fairness metric gaming',
    requiresTarget: true,
  },

  // ── Cloud / Infra ────────────────────────────────────────────────────────────
  {
    id: 's3_bucket_enum',
    label: 'Cloud Storage Bucket Takeover',
    group: 'cloud',
    mitre: 'T1530',
    description: 'Cloud object storage exploitation: S3/GCS/Azure blob enumeration, subdomain takeover via unclaimed bucket, public ACL misconfiguration, pre-signed URL abuse, bucket policy injection',
    requiresTarget: true,
  },
  {
    id: 'imds_ssrf',
    label: 'Cloud IMDS SSRF',
    group: 'cloud',
    mitre: 'T1552.005',
    description: 'Cloud metadata service exploitation: IMDSv1 SSRF credential theft, IMDSv2 hop-limit bypass, GCP metadata service token retrieval, Azure IMDS identity token abuse, container IMDS pivot',
    requiresTarget: true,
  },
  {
    id: 'lambda_layer_inject',
    label: 'Lambda / Cloud Function Layer Inject',
    group: 'cloud',
    mitre: 'T1525',
    description: 'Serverless function poisoning: Lambda layer dependency injection, Cloud Function environment variable hijacking, shared /tmp persistence across invocations, function URL CORS abuse',
    requiresTarget: true,
  },
  {
    id: 'cloud_trail_disable',
    label: 'Cloud Audit Log Tampering',
    group: 'cloud',
    mitre: 'T1562.008',
    description: 'Cloud logging evasion: CloudTrail event deletion, GuardDuty suppressor rule injection, Azure Monitor diagnostic setting removal, GCP audit log exclusion filter abuse',
    requiresTarget: false,
  },
  {
    id: 'cross_account_pivot',
    label: 'Cross-Account Role Pivot',
    group: 'cloud',
    mitre: 'T1199',
    description: 'AWS cross-account attacks: overly permissive trust policy exploitation, confused deputy via resource-based policies, cross-account S3 exfiltration, Organization SCP bypass',
    requiresTarget: false,
  },
  {
    id: 'gke_rbac_exploit',
    label: 'Kubernetes RBAC Exploit',
    group: 'cloud',
    mitre: 'T1613',
    description: 'Kubernetes RBAC privilege escalation: ClusterRole wildcard abuse, create-pod-to-root, impersonation attack, API server anonymous access, etcd direct access, service account token theft',
    requiresTarget: true,
  },
  {
    id: 'azure_ad_attack',
    label: 'Azure AD / Entra ID Attack',
    group: 'cloud',
    mitre: 'T1078.004',
    description: 'Entra ID exploitation: Primary Refresh Token (PRT) theft, device code phishing flow, Conditional Access policy bypass, guest account tenant enumeration, Azure SSPR abuse',
    requiresTarget: true,
  },
  {
    id: 'terraform_state_steal',
    label: 'Terraform State Exfiltration',
    group: 'cloud',
    mitre: 'T1552',
    description: 'IaC state file attack: Terraform S3 backend credential extraction, Atlantis webhook hijacking, Terragrunt config poisoning, CDK bootstrap role takeover, state locking race condition',
    requiresTarget: true,
  },
  {
    id: 'cloud_cost_dos',
    label: 'Cloud Cost Amplification DoS',
    group: 'cloud',
    mitre: 'T1499',
    description: 'Economic denial-of-sustainability (EDoS): Lambda invocation flooding, DynamoDB scan amplification, Cognito identity pool exhaustion, API Gateway cost spike via unauthenticated calls',
    requiresTarget: true,
  },
  {
    id: 'cloud_logging_blind',
    label: 'Cloud Logging Blind Spot Exploit',
    group: 'cloud',
    mitre: 'T1562',
    description: 'Exploiting cloud logging gaps: data plane events not logged by default, Athena query exfiltration without S3 access log, CloudWatch Logs deletion, blind spot enumeration via error responses',
    requiresTarget: false,
  },
  {
    id: 'ecr_image_poison',
    label: 'Container Image Poisoning',
    group: 'cloud',
    mitre: 'T1525',
    description: 'Registry-level supply chain attack: ECR/GCR/GHCR malicious layer injection, image tag mutable redirect, Docker Hub automated build hook abuse, cosign signature bypass',
    requiresTarget: true,
  },
  {
    id: 'cloud_function_escape',
    label: 'Cloud Function Runtime Escape',
    group: 'cloud',
    mitre: 'T1611',
    description: 'Container/VM escape from cloud function runtime: cgroup namespace breakout, kernel exploit via shared kernel, /proc filesystem abuse, runc CVE exploitation in Lambda/Cloud Run',
    requiresTarget: true,
  },

  // ── OT / ICS / IoT ───────────────────────────────────────────────────────────
  {
    id: 'modbus_exploit',
    label: 'Modbus TCP Exploitation',
    group: 'ot',
    mitre: 'T0836',
    description: 'Modbus TCP/RTU attack emulation: unauthenticated register read/write, coil manipulation, forced exception injection, broadcast command flooding, function code enumeration',
    requiresTarget: true,
  },
  {
    id: 'dnp3_attack',
    label: 'DNP3 Protocol Attack',
    group: 'ot',
    mitre: 'T0855',
    description: 'DNP3 attack emulation: unsolicited response injection, application layer auth bypass, master station spoofing, trip/close relay commands, data integrity attack via replay',
    requiresTarget: true,
  },
  {
    id: 'iec61850_attack',
    label: 'IEC 61850 GOOSE / SV Spoofing',
    group: 'ot',
    mitre: 'T0856',
    description: 'IEC 61850 protocol exploitation: GOOSE message injection and spoofing, sampled value (SV) replay, MMS service enumeration, logical node manipulation, substation protection relay bypass',
    requiresTarget: true,
  },
  {
    id: 'plc_logic_bomb',
    label: 'PLC Logic Bomb Injection',
    group: 'ot',
    mitre: 'T0873',
    description: 'PLC program manipulation: Stuxnet-style ladder logic injection, time-triggered sabotage routine, safety system override simulation, rung modification without HMI visibility, covert state machine alteration',
    requiresTarget: true,
  },
  {
    id: 'bacnet_attack',
    label: 'BACnet Building Automation Attack',
    group: 'ot',
    mitre: 'T0830',
    description: 'BACnet/IP exploitation: unauthenticated device enumeration, HVAC setpoint manipulation, fire alarm system interference, building access control bypass, WhoIs/IAm broadcast abuse',
    requiresTarget: true,
  },
  {
    id: 'zigbee_attack',
    label: 'Zigbee Protocol Attack',
    group: 'ot',
    mitre: 'T0860',
    description: 'Zigbee security exploitation: network key extraction via commissioning sniff, replay attack, coordinator impersonation, routing table poisoning, smart home device takeover chain',
    requiresTarget: false,
  },
  {
    id: 'lorawan_attack',
    label: 'LoRaWAN IoT Network Attack',
    group: 'ot',
    mitre: 'T0860',
    description: 'LoRaWAN exploitation: join request replay, devNonce brute force, bit-flipping attack on encrypted payload, rogue gateway MITM, ADR manipulation for device exhaustion',
    requiresTarget: false,
  },
  {
    id: 'hmi_exploit',
    label: 'HMI / SCADA Interface Exploit',
    group: 'ot',
    mitre: 'T0817',
    description: 'HMI software exploitation: Inductive Automation Ignition RCE, Wonderware thin client path traversal, GENESIS64 authentication bypass, OPC-UA session hijacking, VNC default credential access',
    requiresTarget: true,
  },
  {
    id: 'can_fd_attack',
    label: 'CAN / CAN FD Bus Attack',
    group: 'ot',
    mitre: 'T0838',
    description: 'Automotive CAN bus exploitation: UDS diagnostic command injection, ECU firmware spoofing, DoS via error frame flooding, CAN FD spoofing without physical access via OBD-II port',
    requiresTarget: false,
  },
  {
    id: 'ics_historian_attack',
    label: 'ICS Historian Database Attack',
    group: 'ot',
    mitre: 'T0832',
    description: 'ICS historian exploitation: OSIsoft PI SQL injection, Aspentech IP.21 credential brute force, historian data manipulation for false safety readings, time-series data exfiltration',
    requiresTarget: true,
  },

  // ── Stealth / Evasion ────────────────────────────────────────────────────────
  {
    id: 'living_off_land',
    label: 'LOLBins / LOLBAS Abuse',
    group: 'stealth',
    mitre: 'T1218',
    description: 'Living-off-the-land binary exploitation: MSBuild/CertUtil payload execution, WMIC lateral movement, regsvr32 COM scriptlet bypass, Squiblydoo technique, BITSAdmin download-exec',
    requiresTarget: false,
  },
  {
    id: 'rootkit_implant',
    label: 'Kernel / User Rootkit Implant',
    group: 'stealth',
    mitre: 'T1014',
    description: 'Rootkit implantation: DKOM process/file hiding, eBPF-based kernel rootkit, UEFI bootkit persistence, user-mode API hooking via IAT/EAT patching, hypervisor-level rootkit emulation',
    requiresTarget: false,
  },
  {
    id: 'timestomping',
    label: 'Timestomping & Metadata Falsification',
    group: 'stealth',
    mitre: 'T1070.006',
    description: 'Forensic timeline manipulation: NTFS timestamp modification, MFT entry manipulation, journal/USN log clearing, PE compile timestamp spoofing, Linux ext4 inode time falsification',
    requiresTarget: false,
  },
  {
    id: 'log_wiping',
    label: 'Forensic Log Wiping',
    group: 'stealth',
    mitre: 'T1070',
    description: 'Evidence destruction: Windows event log clearing (wevtutil), Linux syslog/auth.log truncation, bash history erasure, Sysmon rule disable, prefetch/shimcache clearing, SIEM source blackout',
    requiresTarget: false,
  },
  {
    id: 'dll_hijacking',
    label: 'DLL Hijacking / Side-Loading',
    group: 'stealth',
    mitre: 'T1574.002',
    description: 'DLL search order and side-loading exploitation: phantom DLL hijacking, known-DLL override, COM object hijacking, AppDomainManager injection, CWD DLL plant for privilege escalation',
    requiresTarget: false,
  },
  {
    id: 'process_hollowing',
    label: 'Process Hollowing / Ghosting',
    group: 'stealth',
    mitre: 'T1055.012',
    description: 'Advanced process injection: classic process hollowing, process ghosting (NTFS delete-on-open), process herpaderping, transacted hollowing, Doppelgänging, module stomping',
    requiresTarget: false,
  },
  {
    id: 'fileless_malware',
    label: 'Fileless Malware Execution',
    group: 'stealth',
    mitre: 'T1059.001',
    description: 'Fileless attack chain: PowerShell in-memory execution, .NET reflective loading, WMI subscription persistence, registry-resident shellcode, macro-less DDEAUTO, LOLBin-hosted payload',
    requiresTarget: false,
  },
  {
    id: 'syscall_evasion',
    label: 'Direct Syscall / NTAPI Evasion',
    group: 'stealth',
    mitre: 'T1562.001',
    description: 'AV/EDR evasion via direct syscalls: Heaven\'s Gate (WoW64 bypass), SysWhispers indirect syscalls, SSN dynamic resolution, kernel callback unhooking, ETW patching for telemetry blindness',
    requiresTarget: false,
  },
  {
    id: 'amsi_bypass',
    label: 'AMSI / EDR Bypass',
    group: 'stealth',
    mitre: 'T1562.001',
    description: 'AMSI and EDR bypass techniques: AMSI provider DLL patching, hardware breakpoint-based AMSI bypass, kernel handle stripping, PPL (Protected Process Light) abuse, EDR driver callback removal',
    requiresTarget: false,
  },
  {
    id: 'polymorphic_payload',
    label: 'Polymorphic / Metamorphic Payload',
    group: 'stealth',
    mitre: 'T1027.002',
    description: 'Signature evasion via code transformation: polymorphic XOR/RC4 payload encryption, metamorphic instruction substitution, LLVM-based obfuscation passes, compile-time mutation, import hashing',
    requiresTarget: false,
  },

  // ── Crypto / Identity ────────────────────────────────────────────────────────
  {
    id: 'password_crack',
    label: 'GPU Hash Cracking Engine',
    group: 'crypto',
    mitre: 'T1110.002',
    description: 'Offline password hash cracking: Hashcat GPU-accelerated attack, rainbow table lookup, rule-based mangling (best64, OneRuleToRuleThemAll), PRINCE attack, combinator attack chains',
    requiresTarget: false,
  },
  {
    id: 'tls_downgrade',
    label: 'TLS / SSL Downgrade Attack',
    group: 'crypto',
    mitre: 'T1600.001',
    description: 'Protocol downgrade exploitation: BEAST, POODLE (SSLv3/TLS1.0), DROWN (SSLv2), FREAK (export cipher), Logjam (DHE512), ROBOT (Bleichenbacher), SWEET32 birthday attack emulation',
    requiresTarget: true,
  },
  {
    id: 'totp_bruteforce',
    label: 'TOTP / MFA Brute Force',
    group: 'crypto',
    mitre: 'T1110',
    description: 'Multi-factor authentication attacks: TOTP timing window brute force, OTP SMS interception via SS7, MFA fatigue push bombing, backup code enumeration, recovery flow bypass',
    requiresTarget: true,
  },
  {
    id: 'ntlm_relay',
    label: 'NTLM Relay / Pass-the-Hash',
    group: 'crypto',
    mitre: 'T1557.001',
    description: 'NTLM exploitation: Responder-based credential capture, SMB/HTTP NTLM relay to LDAP, Pass-the-Hash lateral movement, NTLM coercion (PetitPotam, PrinterBug, DFSCoerce)',
    requiresTarget: true,
  },
  {
    id: 'golden_ticket',
    label: 'Kerberos Golden / Silver Ticket',
    group: 'crypto',
    mitre: 'T1558.001',
    description: 'Kerberos ticket forgery: Golden Ticket via KRBTGT hash, Silver Ticket for service impersonation, Diamond Ticket for detection evasion, Sapphire Ticket, AS-REP roasting, S4U2Self abuse',
    requiresTarget: true,
  },
  {
    id: 'hsm_attack',
    label: 'HSM Side-Channel / Fault Attack',
    group: 'crypto',
    mitre: 'T1552.004',
    description: 'Hardware Security Module attack emulation: PKCS#11 key extraction via oracle, electromagnetic side-channel key recovery, differential fault analysis, HSM firmware downgrade, PKCS#11 session hijacking',
    requiresTarget: false,
  },
  {
    id: 'pki_cert_forge',
    label: 'PKI Certificate Forgery',
    group: 'crypto',
    mitre: 'T1553.004',
    description: 'Certificate-based attack: rogue CA installation, MITM via forged leaf cert, CT log omission detection bypass, certificate pinning bypass (reverse engineering + dynamic patching), OCSP stapling manipulation',
    requiresTarget: true,
  },
  {
    id: 'key_derivation_flaw',
    label: 'Weak Key Derivation Exploit',
    group: 'crypto',
    mitre: 'T1600',
    description: 'KDF misconfiguration exploitation: low-iteration PBKDF2 cracking, bcrypt cost-1 rainbow table, Argon2 low-memory parameter abuse, IV reuse in AES-CBC, ECB mode penguin attack, nonce reuse in AES-GCM',
    requiresTarget: false,
  },

  // ── Network / Protocol ───────────────────────────────────────────────────────
  {
    id: 'arp_spoofing',
    label: 'ARP Spoofing / LAN MITM',
    group: 'network',
    mitre: 'T1557.002',
    description: 'Layer-2 man-in-the-middle: ARP cache poisoning, gratuitous ARP flooding, DHCP spoofing, IPv6 router advertisement spoofing (SLAAC), LLMNR/NBT-NS poisoning',
    requiresTarget: true,
  },
  {
    id: 'icmp_covert_channel',
    label: 'ICMP / DNS Covert Channel',
    group: 'network',
    mitre: 'T1095',
    description: 'Protocol-tunneled exfiltration: ICMP echo payload C2, DNS TXT/NULL record tunneling (dnscat2), HTTP long-poll covert channel, TCP ISN steganography, IPv6 extension header covert channel',
    requiresTarget: false,
  },
  {
    id: 'snmp_attack',
    label: 'SNMP Community String Attack',
    group: 'network',
    mitre: 'T1040',
    description: 'SNMP exploitation: community string brute force, SNMPv1/v2c write-community device reconfiguration, SNMP trap spoofing, MIB walking for topology disclosure, SNMPv3 auth bypass',
    requiresTarget: true,
  },
  {
    id: 'ospf_bgp_manipulation',
    label: 'OSPF / BGP Route Manipulation',
    group: 'network',
    mitre: 'T1557',
    description: 'Routing protocol exploitation: OSPF LSA injection for traffic redirection, BGP route hijacking via AS path manipulation, IBGP session MD5 bypass, route leak amplification',
    requiresTarget: true,
  },
  {
    id: 'rdp_exploit',
    label: 'RDP Exploitation Engine',
    group: 'network',
    mitre: 'T1021.001',
    description: 'Remote Desktop Protocol exploitation: BlueKeep (CVE-2019-0708), DejaBlue, RDP credential brute force, NLA bypass, RDP session hijacking, PrintNightmare via RDP printer driver',
    requiresTarget: true,
  },
  {
    id: 'voip_sip_attack',
    label: 'VoIP / SIP Protocol Attack',
    group: 'network',
    mitre: 'T1040',
    description: 'VoIP security exploitation: SIP REGISTER hijacking, call interception via RTP injection, SIP digest authentication bypass, toll fraud via fake gateway, VLAN hopping to voice VLAN',
    requiresTarget: true,
  },
  {
    id: 'dns_tunneling',
    label: 'DNS Tunneling C2',
    group: 'network',
    mitre: 'T1071.004',
    description: 'DNS-based C2 and exfiltration: Iodine/dnscat2 protocol emulation, low-and-slow DNS beacon, TXT/NULL/A record data encoding, DNS-over-HTTPS (DoH) tunnel, authoritative resolver abuse',
    requiresTarget: true,
  },
  {
    id: 'dhcp_starvation',
    label: 'DHCP Starvation / Rogue Server',
    group: 'network',
    mitre: 'T1557',
    description: 'DHCP-based attacks: starvation via MAC flooding, rogue DHCP server for default gateway redirect, DHCP option 121 route injection, IPv6 DHCPv6 rogue server, WPAD proxy poisoning via DHCP',
    requiresTarget: true,
  },
  {
    id: 'ntp_amplification',
    label: 'NTP / UDP Amplification DDoS',
    group: 'network',
    mitre: 'T1498.002',
    description: 'Reflection/amplification DDoS emulation: NTP monlist (600x amplification), DNS ANY amplification, memcached UDP (51000x), SSDP/CLDAP reflection, QUIC amplification attack',
    requiresTarget: false,
  },
  {
    id: 'wifi_attack',
    label: 'Wi-Fi / 802.11 Attack Suite',
    group: 'network',
    mitre: 'T1491',
    description: 'Wireless LAN attacks: WPA2/WPA3 PMKID capture, PMKID cracking, deauth/disassoc flooding, evil twin AP, KRACK WPA2 key reinstallation, WPS PIN brute force, captive portal bypass',
    requiresTarget: false,
  },

  // ── Supply Chain ─────────────────────────────────────────────────────────────
  {
    id: 'npm_typosquatting',
    label: 'npm / PyPI Typosquatting Attack',
    group: 'supply_chain',
    mitre: 'T1195.001',
    description: 'Package registry typosquatting: lookalike package name generation, install-time malicious postinstall script, dependency hijacking via unpublished packages, scope confusion (@corp/pkg vs corp-pkg)',
    requiresTarget: false,
  },
  {
    id: 'dependency_confusion',
    label: 'Dependency Confusion Attack',
    group: 'supply_chain',
    mitre: 'T1195.001',
    description: 'Dependency confusion exploitation: internal package name enumeration from error messages, public registry package squatting with higher version, pip/npm/NuGet resolver priority abuse',
    requiresTarget: true,
  },
  {
    id: 'open_source_backdoor',
    label: 'Open-Source Project Backdoor',
    group: 'supply_chain',
    mitre: 'T1195.001',
    description: 'OSS supply chain attack: social engineering maintainer account takeover (XZ Utils-style), malicious PR injection, GitHub Actions workflow compromise, npm account hijacking via stale maintainer',
    requiresTarget: false,
  },
  {
    id: 'build_artifact_tamper',
    label: 'Build Artifact Tampering',
    group: 'supply_chain',
    mitre: 'T1195.002',
    description: 'Build artifact integrity attack: SLSA level 1/2 bypass, artifact checksum mismatch injection, release binary substitution, unsigned artifact delivery, reproducible build defeat',
    requiresTarget: true,
  },
  {
    id: 'package_signing_bypass',
    label: 'Package Signing Bypass',
    group: 'supply_chain',
    mitre: 'T1553',
    description: 'Code signing defeat: GPG key impersonation, Sigstore/Cosign verification bypass, weak SHA1-signed package acceptance, certificate chain validation skip, timestamp signature replay',
    requiresTarget: false,
  },
  {
    id: 'vendored_code_attack',
    label: 'Vendored Code / Git Submodule Attack',
    group: 'supply_chain',
    mitre: 'T1195',
    description: 'Vendored dependency attack: git submodule URL redirect, .gitmodules tampering, vendor directory diff injection, go.sum hash bypass, Cargo lock file manipulation, Maven wrapper script poisoning',
    requiresTarget: true,
  },
  {
    id: 'code_review_bypass',
    label: 'Code Review / PR Bypass',
    group: 'supply_chain',
    mitre: 'T1195.002',
    description: 'CODEOWNERS and branch protection bypass: unicode homoglyph in code review, hidden Unicode bidirectional control characters (Trojan Source), case-sensitive reviewer confusion, LGTM bot manipulation',
    requiresTarget: true,
  },
  {
    id: 'update_mechanism_hijack',
    label: 'Software Update Mechanism Hijack',
    group: 'supply_chain',
    mitre: 'T1195.002',
    description: 'Auto-update exploitation: insecure HTTP update URL MITM, TUF (The Update Framework) metadata tampering, version rollback attack, unsigned update package delivery, Electron auto-updater path hijack',
    requiresTarget: true,
  },

  // ── APT / Top-Tier ───────────────────────────────────────────────────────────
  {
    id: 'advanced_persistence',
    label: 'Advanced Persistence (UEFI / Bootkit)',
    group: 'apt',
    mitre: 'T1542',
    description: 'Nation-state grade persistence: UEFI SPI firmware implant (MosaicRegressor-style), Secure Boot bypass via UEFI variable manipulation, MBR/VBR bootkit, EFI System Partition implant, SMM rootkit emulation',
    requiresTarget: false,
  },
  {
    id: 'apt_lateral_movement',
    label: 'APT Lateral Movement Playbook',
    group: 'apt',
    mitre: 'T1021',
    description: 'Advanced lateral movement TTPs: DCOM lateral movement, WMI remote execution, PSExec-less service creation, SSH agent forwarding abuse, Kerberos S4U constrained delegation pivot',
    requiresTarget: true,
  },
  {
    id: 'nation_state_ttps',
    label: 'Nation-State TTP Emulation',
    group: 'apt',
    mitre: 'T1588',
    description: 'Emulation of top APT playbooks: NOBELIUM (SolarWinds-style SWC), APT41 supply chain + espionage dual mission, Lazarus SWIFT heist TTPs, Sandworm destructive wiper emulation, APT29 OAuth abuse',
    requiresTarget: false,
  },
  {
    id: 'zero_day_chain',
    label: 'Zero-Day Exploit Chain',
    group: 'apt',
    mitre: 'T1203',
    description: 'Multi-vulnerability zero-day chain simulation: browser renderer RCE → sandbox escape → kernel privilege escalation → persistence chain, following in-the-wild exploit development methodology',
    requiresTarget: true,
  },
  {
    id: 'apt_c2_infra',
    label: 'APT-Grade C2 Infrastructure',
    group: 'apt',
    mitre: 'T1583',
    description: 'APT C2 infrastructure emulation: Cobalt Strike malleable profile detection, Brute Ratel/Sliver evasive C2, Azure/AWS-hosted redirectors, certificate impersonation, fast-flux DNS rotation',
    requiresTarget: false,
  },
  {
    id: 'long_haul_exfil',
    label: 'Long-Haul Slow Exfiltration',
    group: 'apt',
    mitre: 'T1030',
    description: 'APT dwell-time data exfiltration simulation: 200-byte/hour slow-leak over DNS, HTTPS traffic blending with legitimate patterns, staged collection to encrypted dead-drop, data chunking and reconstruction',
    requiresTarget: true,
  },
  {
    id: 'full_breach_sim',
    label: 'Full End-to-End Breach Simulation',
    group: 'apt',
    mitre: 'T1650',
    description: 'Complete kill chain emulation: recon → initial access → execution → persistence → privilege escalation → defense evasion → credential access → lateral movement → collection → exfiltration → impact',
    requiresTarget: true,
  },
  {
    id: 'watering_hole',
    label: 'Watering Hole Attack',
    group: 'apt',
    mitre: 'T1189',
    description: 'Strategic web compromise: target-profile-based website compromise, browser exploit delivery via malicious ad/iframe, SWC with profiling (only deliver payload to target fingerprint), TA redirect chain',
    requiresTarget: true,
  },
  {
    id: 'supply_chain_apt',
    label: 'Supply Chain APT Implant',
    group: 'apt',
    mitre: 'T1195',
    description: 'SolarWinds/3CX-style supply chain implant: build server compromise, DLL sideload via signed installer, delayed activation via dead-drop resolver, X509 certificate-based victim validation',
    requiresTarget: false,
  },
  {
    id: 'destructive_wiper',
    label: 'Destructive Wiper Emulation',
    group: 'apt',
    mitre: 'T1485',
    description: 'Disk-wiping destructive payload emulation: MBR overwrite, partition table destruction, recursive file encryption without key storage, OT process disruption commands, ATA SECURE ERASE simulation',
    requiresTarget: false,
  },
]

/** Engines that do not need a URL target to run (tenant/global scope) */
export const TARGETLESS_ENGINE_IDS = new Set(
  ENGINES_REGISTRY.filter((e) => !e.requiresTarget).map((e) => e.id),
)

/** Get a single engine by ID */
export function getEngine(engineId) {
  return ENGINES_REGISTRY.find((e) => e.id === engineId) ?? null
}

/** Get all engines in a given group */
export function getEnginesByGroup(groupId) {
  return ENGINES_REGISTRY.filter((e) => e.group === groupId)
}

/** Quick-lookup map: engineId → engine */
export const ENGINES_BY_ID = Object.fromEntries(ENGINES_REGISTRY.map((e) => [e.id, e]))
