export const STRATEGIC_ENGINE_PROGRAM = [
  {
    id: 'osint',
    priority: 'P0',
    requiresDedicatedPage: true,
    reason: 'Executive intelligence feed and stakeholder-facing threat posture baseline.',
    status: 'planned_wave_1',
    route: '/engines/business/osint',
  },
  {
    id: 'asm',
    priority: 'P0',
    requiresDedicatedPage: true,
    reason: 'Board-level attack surface KPIs and external exposure deltas.',
    status: 'planned_wave_1',
    route: '/engines/business/asm',
  },
  {
    id: 'supply_chain',
    priority: 'P0',
    requiresDedicatedPage: true,
    reason: 'Vendor/package risk governance requires dedicated lifecycle view.',
    status: 'planned_wave_1',
    route: '/engines/business/supply_chain',
  },
  {
    id: 'leak_hunter',
    priority: 'P1',
    requiresDedicatedPage: true,
    reason: 'Credential leak tracking and incident follow-up workflow.',
    status: 'planned_wave_2',
    route: '/engines/business/leak_hunter',
  },
  {
    id: 'semantic_ai_fuzz',
    priority: 'P1',
    requiresDedicatedPage: true,
    reason: 'High-cost AI scan operations with entitlement/quota controls.',
    status: 'planned_wave_2',
    route: '/engines/business/semantic_ai_fuzz',
  },
  {
    id: 'ai_adversarial_redteam',
    priority: 'P1',
    requiresDedicatedPage: true,
    reason: 'Model risk owners need dedicated adversarial campaign timeline.',
    status: 'planned_wave_2',
    route: '/engines/business/ai_adversarial_redteam',
  },
  {
    id: 'k8s_container',
    priority: 'P1',
    requiresDedicatedPage: true,
    reason: 'Cloud platform teams need container/K8s compliance posture board.',
    status: 'planned_wave_2',
    route: '/engines/business/k8s_container',
  },
  {
    id: 'scada_ics',
    priority: 'P1',
    requiresDedicatedPage: true,
    reason: 'OT environments require isolated UX and explicit safety context.',
    status: 'planned_wave_2',
    route: '/engines/business/scada_ics',
  },
  {
    id: 'oast_oob',
    priority: 'P1',
    requiresDedicatedPage: true,
    reason: 'OAST correlation evidence needs dedicated callback proof panel.',
    status: 'implemented_top_tier',
    route: '/engines/top-tier/oast_oob',
  },
  {
    id: 'kill_chain',
    priority: 'P1',
    requiresDedicatedPage: true,
    reason: 'Security leadership needs lifecycle narrative and mitigation choke points.',
    status: 'implemented_top_tier',
    route: '/engines/top-tier/kill_chain',
  },
  {
    id: 'zero_day_prediction',
    priority: 'P1',
    requiresDedicatedPage: true,
    reason: 'Predictive risk must be presented with confidence and evidence lineage.',
    status: 'implemented_top_tier',
    route: '/engines/top-tier/zero_day_prediction',
  },
  {
    id: 'deception_honeypot',
    priority: 'P1',
    requiresDedicatedPage: true,
    reason: 'Deception scoring and operator confidence require specialized context.',
    status: 'implemented_top_tier',
    route: '/engines/top-tier/deception_honeypot',
  },
]

export function strategicEnginesNeedingDedicatedPage() {
  return STRATEGIC_ENGINE_PROGRAM.filter((e) => e.requiresDedicatedPage)
}
