import { ENGINES_BY_ID } from './enginesRegistry'

export const TOP_TIER_ENGINE_IDS = [
  'nexus_sovereign_swarm',
  'kill_chain',
  'oast_oob',
  'deception_honeypot',
  'digital_twin',
  'zero_day_prediction',
  'threat_emulation',
  'poe_synthesis',
  'risk_superposition_collapse',
  'satellite_recon',
  'darkweb_intel',
  'financial_osint',
  'blockchain_trace',
  'metadata_harvest',
  'patent_recon',
  'telecom_osint',
  'iot_shodan_scan',
  'job_posting_osint',
  'github_secret_scan',
  'graphql_deep_attack',
  'websocket_attack',
  'grpc_reflection_attack',
  'http2_attack',
  'pki_tls',
  'mtls_grpc',
  'edr_evasion',
  'waf_bypass',
  'cicd_pipeline',
  'oauth_oidc',
  'web_http_intel',
  'web_identity_surface',
  'password_spray',
]

const BASE_EXPECTED_OUTPUTS = [
  'Actionable findings with severity and remediation context',
  'Evidence trail suitable for analyst review and report generation',
  'Machine-readable JSON fields for downstream orchestration',
]

const PROFILES = {
  nexus_sovereign_swarm: {
    mission: 'Deploy thousands of autonomous AI micro-agents across the full attack surface with emergent hive-mind consensus — breakthrough swarm intelligence no competitor offers.',
    intelligenceFocus: 'Multi-archetype agent coordination (Scout/Exploiter/Correlator/Stealth/Oracle), cross-signal consensus, endpoint agent bridging, edge POP distribution, Swarm IQ scoring.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'Swarm metrics with SIQ score', 'Hive-mind consensus findings', 'Oracle LLM strategic synthesis'],
    samplePayload: {
      engine: 'nexus_sovereign_swarm',
      target: 'https://target.example',
      agent_count: 2048,
      hive_mode: 'emergent',
      llm_strategy: 'adaptive',
      endpoint_bridge: 'true',
      edge_distribution: 'true',
      convergence_threshold: '0.85',
    },
  },
  kill_chain: {
    mission: 'Build full adversary path from recon to impact to prioritize breakpoints.',
    intelligenceFocus: 'Attack-path sequencing, choke points, lateral movement opportunities.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'Mapped kill-chain stage transitions'],
    samplePayload: { engine: 'kill_chain', target: 'https://target.example' },
  },
  oast_oob: {
    mission: 'Detect blind injection channels using out-of-band callbacks.',
    intelligenceFocus: 'DNS/HTTP callback signals, token correlation, proof-of-exploit evidence.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'Verified OAST callback events'],
    samplePayload: { engine: 'oast_oob', target: 'https://target.example' },
  },
  deception_honeypot: {
    mission: 'Identify deception infrastructure and honeypot signatures before deeper ops.',
    intelligenceFocus: 'Header fingerprints, interaction anomalies, environment consistency checks.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'Honeypot likelihood score and indicators'],
    samplePayload: { engine: 'deception_honeypot', target: 'https://target.example' },
  },
  digital_twin: {
    mission: 'Build a live digital twin of the web surface and simulate XSS, SQLi, MITM, and CORS attack paths with Wiz-style toxic-combination synthesis.',
    intelligenceFocus: 'Security-header posture, TLS/transport facts, differential injection probes, CORS origin reflection, attack-path graph, posture grade A+–F.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'Twin profile snapshot', 'Scenario verdicts with evidence', 'Attack-path chains', 'Posture grade + remediation roadmap'],
    samplePayload: {
      engine: 'digital_twin',
      target: 'https://target.example',
      scenario: 'all',
      probe_depth: 'standard',
      check_xss: true,
      check_sqli: true,
      check_mitm: true,
      check_cors: true,
      strict_mode: false,
      include_http_cleartext: true,
      canary_only: true,
      max_probe_urls: 32,
      timeout_ms: 8000,
    },
  },
  zero_day_prediction: {
    mission: 'Estimate high-probability emerging risk areas from stack and behavior telemetry.',
    intelligenceFocus: 'Technology fingerprinting, weak hardening patterns, exploitability hints.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'Prediction rationale with confidence signals'],
    samplePayload: { engine: 'zero_day_prediction', target: 'https://target.example' },
  },
  threat_emulation: {
    mission: 'Simulate adversary tradecraft to stress controls across the attack lifecycle.',
    intelligenceFocus: 'Control bypass likelihood, detection gaps, response readiness.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'Emulation scenario trace and outcomes'],
    samplePayload: { engine: 'threat_emulation', target: 'https://target.example' },
  },
  poe_synthesis: {
    mission: 'Generate proof-of-exploit synthesis package with structured verification context.',
    intelligenceFocus: 'PoE narrative quality, reproducibility cues, validation artifacts.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'PoE synthesis stream and status timeline'],
    samplePayload: { engine: 'poe_synthesis', target: 'https://target.example' },
  },
  risk_superposition_collapse: {
    mission: 'Collapse hundreds of weak multi-engine signals into high-confidence MITRE attack chains no single scanner can emit.',
    intelligenceFocus: 'Bayesian belief fusion (noisy-or / cumulative-odds / hybrid), STRIPS planning, toxic combinations, temporal kill-chain correlation, risk-graph paths, FAIR ALE.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'Superposition posture grade A+–F', 'Collapsed MITRE chains with weak-signal provenance', 'Toxic combination alerts', 'Graph choke points'],
    samplePayload: {
      engine: 'risk_superposition_collapse',
      target: 'https://target.example',
      fusion_mode: 'hybrid',
      collapsed_belief_threshold: 0.55,
      include_toxic_combinations: true,
      include_strips_collapse: true,
      include_financial_ale: true,
    },
  },
  satellite_recon: {
    mission: 'Extended external reconnaissance for broad surface expansion signals.',
    intelligenceFocus: 'Domain and infrastructure expansion from multi-source recon.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'Expanded recon entities and links'],
    samplePayload: { engine: 'satellite_recon', target: 'https://target.example' },
  },
  darkweb_intel: {
    mission: 'Track threat chatter and exposed assets in darkweb-adjacent intelligence flows.',
    intelligenceFocus: 'Credential leakage, actor mentions, exposed references to tenant assets.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'Leak/intel correlation summary'],
    samplePayload: { engine: 'darkweb_intel', target: 'https://target.example' },
  },
  financial_osint: {
    mission: 'Extract finance-adjacent public exposure intelligence relevant to attack planning.',
    intelligenceFocus: 'Public filings, vendor exposure, organizational risk signals.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'Finance-risk intelligence snapshot'],
    samplePayload: { engine: 'financial_osint', target: 'https://target.example' },
  },
  blockchain_trace: {
    mission: 'Correlate blockchain artifacts with threat infrastructure indicators.',
    intelligenceFocus: 'Wallet/address clues linked to campaigns and laundering paths.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'Trace graph hints and linked indicators'],
    samplePayload: { engine: 'blockchain_trace', target: 'https://target.example' },
  },
  metadata_harvest: {
    mission: 'Harvest metadata leaks to enrich target context and attack-path hypotheses.',
    intelligenceFocus: 'Document, header, and service metadata footprints.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'Metadata leak inventory'],
    samplePayload: { engine: 'metadata_harvest', target: 'https://target.example' },
  },
  patent_recon: {
    mission: 'Use patent/public innovation signals to infer likely technology stack and risks.',
    intelligenceFocus: 'Technology disclosures and inferred architecture patterns.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'Tech inference summary from public records'],
    samplePayload: { engine: 'patent_recon', target: 'https://target.example' },
  },
  telecom_osint: {
    mission: 'Collect telecom exposure intelligence around network and provider dependencies.',
    intelligenceFocus: 'Carrier signals, telecom metadata, dependency attack surface clues.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'Telecom exposure matrix'],
    samplePayload: { engine: 'telecom_osint', target: 'https://target.example' },
  },
  iot_shodan_scan: {
    mission: 'Identify internet-visible IoT footprint and weak posture indicators.',
    intelligenceFocus: 'Exposed devices, protocol posture, firmware/service banners.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'IoT external exposure list'],
    samplePayload: { engine: 'iot_shodan_scan', target: 'https://target.example' },
  },
  job_posting_osint: {
    mission: 'Infer internal stack and process exposure from hiring signal intelligence.',
    intelligenceFocus: 'Tech stack clues from role requirements and public hiring trends.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'Hiring-derived technology profile'],
    samplePayload: { engine: 'job_posting_osint', target: 'https://target.example' },
  },
  github_secret_scan: {
    mission: 'Hunt secret leakage and repository exposure linked to target domain and org.',
    intelligenceFocus: 'Credential patterns, token leaks, hardcoded key references.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'Leak indicators mapped to repos/entities'],
    samplePayload: { engine: 'github_secret_scan', target: 'https://target.example' },
  },
  graphql_deep_attack: {
    mission: 'Perform deep GraphQL abuse scenarios mapped to modern API attack patterns.',
    intelligenceFocus: 'Schema abuse, depth/cost bypass, nested authorization weaknesses.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'GraphQL exploitation traces and weak nodes'],
    samplePayload: { engine: 'graphql_deep_attack', target: 'https://target.example' },
  },
  websocket_attack: {
    mission: 'Weissman Standard WebSocket DAST — stateful conversational fuzz, binary protobuf mutation, barrier-sync race execution, cross-protocol Intelligence Bus.',
    intelligenceFocus: 'CSWSH session-riding, graphql-ws/SignalR/Socket.IO chains, protobuf gateways, HTTP token replay proof.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'Posture grade 0–100', 'Attack-path synthesis', 'intelligence_artifacts for downstream engines'],
    samplePayload: {
      engine: 'websocket_attack',
      target: 'https://target.example',
      check_stateful_fuzz: 'true',
      check_binary_mutation: 'true',
      check_race_conditions: 'true',
      check_cross_protocol_chain: 'true',
    },
  },
  grpc_reflection_attack: {
    mission: 'Probe gRPC reflection and service exposure to identify high-risk entry points.',
    intelligenceFocus: 'Reflection exposure, service enumeration, transport hardening gaps.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'gRPC reflection and service findings'],
    samplePayload: { engine: 'grpc_reflection_attack', target: 'https://target.example' },
  },
  http2_attack: {
    mission: 'Stress HTTP/2 protocol handling for desync and request-manipulation weaknesses.',
    intelligenceFocus: 'Protocol edge cases, stream handling bugs, desynchronization behavior.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'HTTP/2 risk scenarios and evidence'],
    samplePayload: { engine: 'http2_attack', target: 'https://target.example' },
  },
  pki_tls: {
    mission: 'Deliver a deeper-than-SSL-Labs TLS/PKI verdict from live OpenSSL handshakes — full protocol matrix, exhaustive cipher enumeration, certificate-chain forensics and an A+→F grade no competitor exposes per-engine.',
    intelligenceFocus: 'Per-version handshake probing (SSLv3→TLS 1.3), iterative cipher-suite discovery, leaf+chain analysis (key/sig/validity/SAN/trust), POODLE/BEAST/SWEET32/FREAK/RC4 heuristics, OCSP stapling, HSTS, Certificate Transparency, DNS CAA, DANE/TLSA — with STARTTLS for SMTP/IMAP/POP3/FTP. Command Center: /command-center/tls-posture.',
    expectedOutputs: [
      ...BASE_EXPECTED_OUTPUTS,
      'SSL-Labs-style letter grade with full reasoning trail',
      '0–100 posture score with PCI-DSS / NIST SP 800-52 tags',
      'Complete protocol + cipher-suite matrix per port',
      'Certificate chain forensics (key, signature, validity, SAN, fingerprint, trust)',
    ],
    samplePayload: {
      engine: 'pki_tls',
      target: 'https://target.example',
      ports: '443,8443',
      starttls: 'none',
      intensity: 'aggressive',
      protocols: 'tls1.0,tls1.1,tls1.2,tls1.3',
      cipher_enumeration_limit: 120,
      check_ocsp: 'true',
      check_caa: 'true',
      check_dane: 'true',
      check_posture_score: 'true',
    },
  },
  mtls_grpc: {
    mission: 'Unified transport-security command — TLS/mTLS, gRPC/gRPC-Web/Connect, HTTP hardening, weak-crypto matrix, chain trust, h2c/HTTP/3, DANE/CAA/CT shadow hosts, attack-path synthesis and 0–100 posture grade from live probes only.',
    intelligenceFocus: 'Multi-port TLS session matrix, forced weak-cipher handshakes, gRPC reflection with real wire frames, mTLS enforcement, SNI policy, cert fingerprint drift, TRACE/CORS, redirect-chain audit, h2c prior-knowledge on gRPC ports, WebSocket upgrade, cache policy, CT vs CAA cross-check, coverage manifest. Command Center: /command-center/transport-security.',
    expectedOutputs: [
      ...BASE_EXPECTED_OUTPUTS,
      'Transport Security Posture score 0–100 with Grade A–F',
      'Wiz-style attack-path kill chains + security graph',
      'Probe coverage manifest (every module audited)',
      'PCI-DSS / NIST SP 800-52 compliance tags on crypto findings',
    ],
    samplePayload: {
      engine: 'mtls_grpc',
      target: 'https://target.example',
      scan_profile: 'full',
      intensity: 'aggressive',
      ports: '443,8443',
      grpc_ports: '50051,9090',
      check_weak_ciphers: 'on',
      check_grpc_h2c: 'on',
      check_chain_trust: 'on',
      attack_path_synthesis: 'true',
      emit_coverage_manifest: 'true',
    },
  },
  edr_evasion: {
    mission: 'Remote detection resilience — how hard is it for an adversary to operate undetected against the observable perimeter (WAF/bot matrix, rate limits, CSP/cookie gaps, RUM telemetry, debug surfaces).',
    intelligenceFocus: 'Edge WAF/CDN fingerprint, multi-UA block-rate, burst rate-limit behavior, security headers, CSP injection runway, cookie hardening, defender telemetry in HTML, debug/admin paths, JS source maps, verbose errors. Host EDR (AMSI/ETW/syscall) via honest agent bridge — never fabricated.',
    expectedOutputs: [
      ...BASE_EXPECTED_OUTPUTS,
      'Detection Resilience Score 0–100 (higher = harder to evade)',
      'WAF/vendor fingerprint with block-rate matrix',
      'CSP/cookie/telemetry gap analysis with evidence',
    ],
    samplePayload: {
      engine: 'edr_evasion',
      target: 'https://target.example',
      intensity: 'normal',
      ua_matrix_limit: 24,
      rate_burst_count: 12,
      check_waf: true,
      check_ua_matrix: true,
      check_rate_limit: true,
      check_csp: true,
      check_telemetry: true,
      include_agent_findings: true,
    },
  },
  waf_bypass: {
    mission: 'Live WAF bypass oracle — characterize edge inspection with harmless payloads and document real evasion surfaces (encoding, headers, path normalization, verb gaps, JSON smuggling).',
    intelligenceFocus: 'Vendor fingerprint (Cloudflare→PerimeterX), multi-payload block matrix, transform oracle when blocked, header injection vectors, path normalization, GET vs POST rule gaps, JSON body inspection, 0–100 hardening score.',
    expectedOutputs: [
      ...BASE_EXPECTED_OUTPUTS,
      'WAF hardening score 0–100 with block/bypass metrics',
      'Per-transform bypass surfaces with HTTP status evidence',
      'Vendor fingerprint on baseline and block pages',
    ],
    samplePayload: {
      engine: 'waf_bypass',
      target: 'https://target.example',
      technique: 'all',
      intensity: 'normal',
      check_encoding: true,
      check_header_injection: true,
      check_path_normalization: true,
      emit_score: true,
    },
  },
  oauth_oidc: {
    mission: 'Agentless OAuth 2.0 / OpenID Connect / SSO identity-provider posture — discovery, JWKS crypto, live authorization probing, and account-takeover attack-path synthesis beyond any IdP scanner.',
    intelligenceFocus: 'Provider fingerprint (Okta, Entra, Auth0, Keycloak…), metadata posture (implicit, ROPC, PKCE, alg:none), JWKS key strength, redirect_uri validation, token-endpoint behavior, PAR/DPoP/device-flow gaps.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, '0–100 identity posture score with grade', 'Account-takeover attack paths', 'Provider fingerprint + evidence trail'],
    samplePayload: {
      engine: 'oauth_oidc',
      target: 'https://login.example.com',
      issuer: 'https://login.example.com/realms/acme',
      client_id: 'weissman-probe-client',
      probe_redirect_uri: 'https://oauth-validate.weissman.invalid/callback',
      probe_scope: 'openid',
      intensity: 'normal',
      check_discovery: true,
      check_jwks: true,
      probe_authorization: true,
      probe_implicit: true,
      probe_token_endpoint: true,
      attack_paths: true,
    },
  },
  web_http_intel: {
    mission: 'Burp-class live HTTP/DNS/TLS intelligence — header values, cookie flags, CORS preflight, HSTS/CSP, HTTP/1 vs HTTP/2 differential, CAA, and certificate posture. 401/403 are auth-gated, never public content.',
    intelligenceFocus: 'Exposure classification, security-header values (not just presence), cookie Secure/HttpOnly/SameSite, CORS OPTIONS, TLS key size, dangling CNAME correlation.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'exposure_class on every HTTP finding', 'Cookie hardening gaps without storing token values', 'DNS CAA + TLS evidence trail'],
    samplePayload: {
      engine: 'web_http_intel',
      target: 'https://www.example.com',
      intensity: 'normal',
      evidence_mode: 'forensic',
    },
  },
  web_identity_surface: {
    mission: 'Map internet-facing identity: OIDC discovery, SAML metadata, WWW-Authenticate (NTLM/Negotiate/Bearer), login forms, JWT-shaped cookies (name only), SPF/DMARC perimeter.',
    intelligenceFocus: 'Well-known identity paths, IdP fingerprinting, auth-gated vs public metadata, email-identity DNS.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'Public vs auth-gated identity endpoints', 'IdP fingerprint + WWW-Authenticate scheme', 'SPF/DMARC identity perimeter'],
    samplePayload: {
      engine: 'web_identity_surface',
      target: 'https://login.example.com',
      intensity: 'normal',
      evidence_mode: 'forensic',
    },
  },
  password_spray: {
    mission: 'World-first agentless credential-attack intelligence — Entra AADSTS taxonomy, subdomain login cartography, SAML metadata, OIDC ROPC/device-code, lockout-curve fingerprint, timing/breach oracles, XFF bypass surface, six-axis posture radar, and CIS-mapped remediation playbook.',
    intelligenceFocus: 'M365 GetUserRealm + live token-endpoint AADSTS codes, Exchange Autodiscover, 40+ login paths + subdomain hunter, spray simulation with friction index, browser-vs-script WAF gap, password-policy oracle, attack-path synthesis.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, '0–100 posture score + six-axis radar', 'Stuffing friction index', 'Prioritized remediation playbook', 'Entra/SAML/ROPC intelligence'],
    samplePayload: {
      engine: 'password_spray',
      target: 'https://login.corp.example.com',
      domain: 'corp.example.com',
      scan_profile: 'full',
      intensity: 'normal',
      wordlist: 'medium',
      check_m365_realm: true,
      check_entra_errors: true,
      check_oidc_ropc: true,
      check_subdomain_login: true,
      check_saml_metadata: true,
      check_timing_enum: true,
      check_browser_differential: true,
      check_xff_bypass: true,
      check_remediation_playbook: true,
      attack_path_synthesis: true,
      posture_scoring: true,
    },
  },
  cicd_pipeline: {
    mission: 'Map the full CI/CD attack surface — unauthenticated build APIs, exposed pipeline configs, and GitHub Actions supply-chain weaknesses — with toxic-combination attack paths.',
    intelligenceFocus: 'Jenkins/GitLab/ArgoCD exposure, workflow pwn-request & script-injection, runner-token leakage, DevSecOps posture scoring.',
    expectedOutputs: [...BASE_EXPECTED_OUTPUTS, 'CI/CD posture score with grade', 'Attack-path toxic combinations', 'GitHub Actions policy violations (WZ-GHA-*)'],
    samplePayload: {
      engine: 'cicd_pipeline',
      target: 'https://ci.target.example',
      repo_url: 'https://github.com/org/repo',
      probe_workflow_analysis: 'true',
      probe_jenkins_console: 'true',
      attack_path_synthesis: 'true',
      intensity: 'normal',
    },
  },
}

export function getTopTierProfile(engineId) {
  const baseEngine = ENGINES_BY_ID[engineId] || null
  const profile = PROFILES[engineId] || null
  if (!profile || !baseEngine) return null
  return {
    ...profile,
    id: engineId,
    label: baseEngine.label,
    mitre: baseEngine.mitre,
    description: baseEngine.description,
    requiresTarget: !!baseEngine.requiresTarget,
  }
}

export function isTopTierEngine(engineId) {
  return TOP_TIER_ENGINE_IDS.includes(engineId)
}
